### ISSUE TITLE
Possible to "miss" very short missions

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#118]
Most of our samples do something similar to this:
```
agent_host.startMission( my_mission, my_mission_record )
# Wait for start of mission (is_mission_running flag)
world_state = agent_host.getWorldState()
    while not world_state.is_mission_running:
        time.sleep(0.1)
        world_state = agent_host.getWorldState()
```

It's possible to create missions that can finish within 0.1 seconds - for example, in a setting where an agent must get to a goal square, but the start and end squares are randomised, it is possible for the agent's initial state to satisfy the end conditions.

In such cases, the above code can end up waiting forever, as the is_mission_running flag can be set and then unset again within the time.sleep() call.

One possible fix is to reduce the sleep time; alternatively, agent_host could have an is_mission_over flag too, instead of relying on is_mission_running.

**Comment by timhutton** [comment]
Make startMission block until mission started? New API startMissionAndWait?

Samples should use peekWorldState too.
