### ISSUE TITLE
tabular_q_learning.py integration test fails when python-tk not installed

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#151]
tutorial_6 for the same reason.

apt: `sudo apt-get install python-tk`
dnf: `sudo dnf install tkinter`

**Comment by Microsheep** [comment]
Install activetcl solved the problem for me on windows.
http://www.activestate.com/activetcl

**Comment by timhutton** [comment]
On Windows, with Python 2.7.* 64-bit from python.org, Tkinter should come already installed.

**Comment by martore** [comment]
On Windows, remove all (including 2.7, because it might be corrupted) Python versions and then install Python 2.7 (64-bit).

**Comment by timhutton** [comment]
For Linux, now added to build instructions. 816b3ac
