### ISSUE TITLE
launchClient gives (harmless) warning: "The system cannot find the path specified"

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#152]
When running Minecraft for the first time, launchClient can't find the config file, since it hasn't been written yet. This message is harmless but worries users and has been reported several times, so should be fixed.

On Windows: `The system cannot find the path specified.`
On Linux: `./launchClient.sh: line 43: run/config/malmomodCLIENT.cfg: No such file or directory`

**Comment by drtuck** [comment]
Hi.  New to GitHub - seemed that making a branch was best way to contribute, but that operation unavailable to me.  Here are the fixed files.  Good luck w/Camel.

[launchClients.zip](https://github.com/Microsoft/malmo/files/355809/launchClients.zip)

**Comment by suyashbansal** [comment]
It starts downloading Gradle. I already have it setup.

![image](https://cloud.githubusercontent.com/assets/5832436/16714245/717fdaa8-46da-11e6-81a6-33fbb19f9a94.png)

**Comment by DaveyBiggers** [comment]
Am closing this issue as it has been fixed by @drtuck in #161.
@suyashbansal - if you are still having a problem with the Gradle download behaviour, please open it as a separate issue. Thanks!
