### ISSUE TITLE
MalmoPython constantly unable to find DLLs on Windows 10 x64

### ISSUE THREAD

**Issue by DimensionsGaming** [Microsoft/malmo#156]
<img width="584" alt="2016-07-08 19_42_30-select administrator_ command prompt" src="https://cloud.githubusercontent.com/assets/19407445/16698095/8026329c-4544-11e6-981c-189d924a31b8.png">
Python 2.7.12 started off printing the error "ImportError: DLL load failed: The specified module could not be found." due to CodeSynthesis not having been installed to the Path. That was fixed by manually installing the C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin folder to the Path.

Running the Python code after installing the CodeSynthesis bin folder to the Path now results in Python printing the "ImportError: DLL load failed: %1 is not a valid Win32 application." even when running 64-bit Python.

**Comment by JezQ** [comment]
I am experiencing this issue as well.

**Comment by extremeheat** [comment]
I've encountered a similar situation, running the native C++ examples returned DLL missing errors which were fixed by adding CodeSynthesis to my user's PATH and restarting the command prompt.

Try copying over the 64-bit xerces-c_3_1_vc120.dll from C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64 to the current directory and see if it runs.

**Comment by JezQ** [comment]
I have solved the problem. Thanks to extremeheat hinting about the bin64 folder. What fixed the problem was simply adding C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64 to the path.

**Comment by timhutton** [comment]
Ah, in the gitter chat I advised @DimensionsGaming to add `C:\program files (x86)\codesynthesis xsd 4.0\bin` to the PATH. But testing it on my system I can now see that this is wrong, and it does need to be `bin64`, as suggested above. This makes sense. Please try that, @DimensionsGaming and let us know!

**Comment by DimensionsGaming** [comment]
It's worked, but now I'm getting FFMPEG not available.

**Comment by timhutton** [comment]
@DimensionsGaming Well I feel we're making progress! (Thanks @extremeheat!)

Does `ffmpeg` at a command prompt work? I'm assuming you've installed as per [here](https://github.com/Microsoft/malmo/blob/master/doc/install_windows.md).

**Comment by DimensionsGaming** [comment]
ffmpeg was missing from the path. I've installed it to the path and now everything's running perfectly.

**Comment by timhutton** [comment]
@DimensionsGaming Awesome! Glad we could get you going eventually.

**Comment by Liquidmasl** [comment]
actually i have the same problem, all paths are there, still..
![image](https://cloud.githubusercontent.com/assets/10048306/16709715/db2c2ac8-4618-11e6-869d-9cbf3e733306.png)

**Comment by DimensionsGaming** [comment]
@Liquidmasl Have you tried the fix I posted above?

**Comment by DimensionsGaming** [comment]
@Liquidmasl Would you mind uploading a screenshot of this window so I can see more clearly what you have in your path (Control Panel > System and Security > System > Advanced System Settings > Environment Variables... > Path under System Variables) 
<img width="376" alt="2016-07-09 21_15_07-edit environment variable" src="https://cloud.githubusercontent.com/assets/19407445/16710078/cb86cdba-461a-11e6-8f61-f2c268d856eb.png">
?

**Comment by Liquidmasl** [comment]
@DimensionsGaming  that window doesnt exist on my machine Oo
I have to add to the path by pasting the new path behind all the old path entries with a semicolon in between..

**Comment by DimensionsGaming** [comment]
@Liquidmasl It should do. Are you on Windows 10? If you are, right-click on the start menu and select Control Panel from the context menu that opens up.

**Comment by Liquidmasl** [comment]
yeah i am, and i found it and manipulated the path multiple times.. it just looks quite different! 

I got you a screenshot from every "stage"
the far right window is the window where i can add to the path or edit it..

everything in one line, cant really screenshot that..
But I can copy it! 

`C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64\;
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\CineForm\Tools;
D:\Program Files (x86)\GoPro\GoPro Studio\GoPro\Tools;
D:\SiudiDriver\XHardwareLibrary;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files (x86)\QuickTime\QTSystem\;
%SystemRoot%\system32;
%SystemRoot%;
%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Skype\Phone\;
C:\Program Files\OpenVPN\bin;
C:\ffmpeg\bin;
C:\Program Files\Java\jdk1.8.0_91\bin\;
C:\Python27\`

![image](https://cloud.githubusercontent.com/assets/10048306/16714063/a1270ba4-46b8-11e6-94b2-786574b6bc69.png)

**Comment by DimensionsGaming** [comment]
@Liquidmasl Good. Now click on edit once you're on path under "Systemvariablen".

**Comment by DimensionsGaming** [comment]
@Liquidmasl Alright. I'm not sure what the problem is. Let me just ping Tim because he'll be able to help you more. CC @timhutton Would you mind taking over from here.

**Comment by rahmacha** [comment]
@Liquidmasl  I am having the same issue even with "C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64;" in my path. Did you managed to solve it?

**Comment by okkhoy** [comment]
Upvote!

Does trying to use Malmo over Python 2.7 cause this problem? (Considering Windows build reads: 
`Malmo-0.31.0-Windows-64bit_Python3.6`

Versions:

```
Python 2.7.14 :: Anaconda, Inc.

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Malmo: 0.31.0
```

**Comment by zbrill** [comment]
Hi all. I've added the CodeSynthesis directory to my path, as long as all other dependencies (Python27/ffmpeg/etc). I am still having problems getting the DLL to be found.
`Traceback (most recent call last):
  File ".\run_mission.py", line 22, in <module>
    import MalmoPython
ImportError: DLL load failed: The specified module could not be found.`

Using Python2.7 on Windows 10.
If anyone can help, please let me know!

**Comment by okkhoy** [comment]
I am able to use `Malmo-0.34.0-Windows-64bit_withBoost_Python2.7` without issues 👍

**Comment by AndKram** [comment]
CodeSynthesis no longer required for Linking.

**Comment by ZombiePm** [comment]
C:\Malmo\Python_Examples>python tutorial_1.py
Traceback (most recent call last):
  File "tutorial_1.py", line 24, in <module>
    import MalmoPython
ImportError: DLL load failed: Не найден указанный модуль.
