### ISSUE TITLE
Java MalmoJava DLL not found

### ISSUE THREAD

**Issue by norvar** [Microsoft/malmo#158]
![screenshot 61](https://cloud.githubusercontent.com/assets/9779240/16709158/aa42dba6-45d6-11e6-9748-fa8cabb9051e.png)

Help needed. Thanks.

**Comment by norvar** [comment]
MalmoJava.dll is actually in the directory.

**Comment by bronydell** [comment]
Same

**Comment by bronydell** [comment]
Try to install Microsoft Visual Studio 2013 redistributable(here: https://www.microsoft.com/en-us/download/details.aspx?id=40784)

**Comment by norvar** [comment]
Thank you for replying. I had Microsoft Visual Studio 2013 redistributable (x64) installed before.

**Comment by mithunrt** [comment]
I am facing the same issue. Can anyone please help?

**Comment by mithunrt** [comment]
I had the same issue. This solution from @timhutton solved my problem: https://github.com/Microsoft/malmo/issues/156#issuecomment-231459982

**Comment by norvar** [comment]
After I set PATH to "C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64"(no quote), I still had the same problem. I checked my system doesn't have directory "C:\Program Files (x86)\CodeSynthesis XSD 4.0". What is that?

Thanks

**Comment by norvar** [comment]
After I set PATH to "C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64"(no quote), I still had the same problem. I checked my system. It doesn't have a directory "C:\Program Files (x86)\CodeSynthesis XSD 4.0". What is that?

Thanks

**Comment by HAadams** [comment]
I had the same issue,
make sure your JAVA_HOME variable is set to point to the folder of your jdk not the bin.
then add the absolute path of the bin folder of your java jdk to the PATH variable

example
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_91
PATH: C:\Program Files\Java\jdk1.8.0_91\bin

also make sure the source files are in the PATH directory as well as your python folder. so this is how my PATH looks like:
PATH: C:\Program Files\Java\jdk1.8.0_91\bin; C:\Users\Sein\Desktop\ffmpeg-latest-win64-static\bin; C:\Python27

Then restart your computer and hopefully it would work

**Comment by HAadams** [comment]
check this page:
https://github.com/Microsoft/malmo/blob/master/doc/install_windows.md

Download and install the third dependency "CodeSynthesis"

**Comment by norvar** [comment]
I have all others but not C:\Users\Sein\Desktop\ffmpeg-latest-win64-static\bin, nor C:\Python27. Do I have to all those software?

**Comment by norvar** [comment]
I have all others but not C:\Users\Sein\Desktop\ffmpeg-latest-win64-static\bin, nor C:\Python27. Do I have to install all those software?

**Comment by HAadams** [comment]
Yes. Refer to this link.
Download all non optional dependencies and the optional ones that you want to work with

**Comment by norvar** [comment]
OK. Thanks.

**Comment by norvar** [comment]
![screenshot 62](https://cloud.githubusercontent.com/assets/9779240/16718055/e68acf10-46e9-11e6-86bf-825f031ba1eb.png)

It looks worked. Does the sample only run a few steps as in the picture?

Thanks.

**Comment by HAadams** [comment]
Yes. Refer to this tutorial if you haven't already:
https://github.com/Microsoft/malmo/blob/master/Malmo/samples/Python_examples/Tutorial.pdf

**Comment by norvar** [comment]
Not yet. Thanks.
