### ISSUE TITLE
Proposal of readme update

### ISSUE THREAD

**Issue by jaspercayne** [Microsoft/malmo#162]
I'm astounded by the number of people in the gitter chat that don't realize there is a very in depth documentation included with the release and recommend adding something on the getting started section of the readme that mentions this and where it is located. A large number of the issues I'm seeing in gitter are things that are covered in the documentation and likely wouldn't come up if more people realized they had a copy of it.

**Comment by jaspercayne** [comment]
My apologies, I didn't realize this was already in there... I guess you can lead a horse to water....

**Comment by DaveyBiggers** [comment]
Indeed. Thank you for all your patient help on gitter though.
