### ISSUE TITLE
Error "your access transformers be broke"

### ISSUE THREAD

**Issue by goosehub** [Microsoft/malmo#164]
Followed steps to install including windows dependencies. Running Windows 10. Got this error after running launchClient.

> FAILURE: Build failed with an exception.
>  
> * What went wrong:
> Execution failed for task ':deobfMcMCP'.
> > Your Access Transformers be broke!

Full stacktrace.

http://pastebin.com/ZnP946BT

**Comment by suyashbansal** [comment]
I am also getting the same error.

**Comment by suyashbansal** [comment]
I closed all CMD terminals and started running launchClient again. At that time I got the error saying JAVA_HOME not set. I removed the previous java path and modified it using 
`setx JAVA_HOME "C:\Program Files\Java\jdk1.8.0_60"`
`setx PATH "%PATH%;%JAVA_HOME%\bin";`
After that, I tried running the launchClient in a new CMD terminal.
It worked!!

**Comment by geekstor** [comment]
@goosehub I'm not sure if you are using a release or are building from a clone of the repo (it seems to be the former). I believe the errors you see on the stacktrace occur generally when a build gets interrupted and dependencies are missing. 

If you are not already using a build, try cloning the repo and follow the build instructions. 

If you are already working on a build, open up a command prompt into the directory where Malmo is installed and `cd` into the `Minecraft` folder. Then  try `./gradlew clean` followed by `./gradlew build` or additionally `./gradlew cleancache --refresh-dependencies` before the build step. This basically gathers all the dependencies again and generally seems to fix the "Access Transformer be Broke" errors.

**Comment by samuelvonstachelski** [comment]
I had the same issue on debian scratch. Proper setup of JDK and JAVA_HOME fixed this.

**Comment by DaveyBiggers** [comment]
Closing this issue as it looks like it has been resolved - @goosehub, if you are still getting this problem please re-open.
