### ISSUE TITLE
downloadServer FAILED

### ISSUE THREAD

**Issue by likegun** [Microsoft/malmo#169]
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
Software caused connection abort: recv failed
:extractUserdev UP-TO-DATE
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadServer'.
> java.net.SocketException: Software caused connection abort: recv failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 9.999 secs
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:getVersionJson
Software caused connection abort: recv failed
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadServer'.
> java.net.SocketException: Software caused connection abort: recv failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 4.665 secs
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:getVersionJson
Software caused connection abort: recv failed
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadServer'.
> java.net.SocketException: Software caused connection abort: recv failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by DaveyBiggers** [comment]
Looks like you are having internet connectivity issues? Can you give us any more details (eg your OS, how you installed Malmo, etc etc?)

**Comment by timhutton** [comment]
This issue happens occasionally when internet connection is lost. Just try it again until it works. Closing.
