### ISSUE TITLE
Feature request: a way for the agent to quit the mission

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#170]
There is currently no way for an agent to bail mid mission. It might be nice to have a "quit" command, or something along those lines.

Note that this slightly breaks the notion that the configuration of the experiment is dictated by the mission XML, not by the agent. The idea behind the quit handlers is to set the requirements that the agent has to reach in order to complete the mission - rather than letting the agent control the boundaries of the experiment itself. But perhaps the agent should have the ability to quit.

Alternatively / additionally we could add a method to the AgentHost API to quit the mission?

**Comment by jorallo** [comment]
That might be useful. If this is implemented as an extra action "quit", this could be enabled or not by the experiment, in the same way other actions are included or excluded with the ModifierList, so the experiment would still have full control of whether it can be used or not.
