### ISSUE TITLE
Currently no way to press the <shift> key

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#174]
The shift key is used in Minecraft for, eg:
- Descending during flying
- Dismounting from boats/minecarts/horses etc
- Crouching

We currently have a crouch command, but it doesn't operate at the key-press level, so it can't be used for the other use cases.

**Comment by jaspercayne** [comment]
Possibly provide a command to allow the agent to send raw keypress information, allowing for a stronger level of compatibility in an environment with additional mods installed that may require more keys than what is in the default control scheme.

**Comment by DaveyBiggers** [comment]
Actually, it turns out that this works fine as is... Minecraft triggers the sneaking, descending and dismounting behaviour all off the same `sneak` flag, which we currently set using the `crouch` command.
So we can already do all of these things.
