### ISSUE TITLE
Problem with launchClient

### ISSUE THREAD

**Issue by Termi1878** [Microsoft/malmo#175]
When i'm launching "launchClient" in command prompt everything is good until this:
![2](https://cloud.githubusercontent.com/assets/20418183/16764608/69c8819c-482f-11e6-9fa0-c4e700b2f69a.png)
I don't know if i did everything well. How to run this Minecraft Bloody Hell?!
I'm trying to learn Python as my first language and on the first step I have a problem ;_;

**Comment by DaveyBiggers** [comment]
Sorry you are having a frustrating experience! Can you post the complete log of what happens? It'll help us narrow down the problem.

**Comment by geekstor** [comment]
I believe the stacktrace you see appears to be the same as that of @goosehub's. Maybe take a look at #164 and follow the steps I suggest there. I think the "Your access transformer be broke" errors are generally ones in which the dependencies for Minecraft haven't been downloaded properly as a result of a broken or interrupted build.

**Comment by Helpdesk-CS** [comment]
I have this problem, i have reinstall Java SDK a last version and update my environment variable and : ITS work !

**Comment by Termi1878** [comment]
@DaveyBiggers http://pastebin.com/kvWzbQ43 I hope it will help.

**Comment by Zootar** [comment]
I had same problem:
https://github.com/Microsoft/malmo/issues/172

**Comment by Termi1878** [comment]
@Zootar It works! Thank you!

**Comment by Termi1878** [comment]
Well. Minecraft is now opened, but when I'm typing "start tutorial_1.py" nothing is going on. I tried with opened MC, but it still doesn't work ;_;. 
![2](https://cloud.githubusercontent.com/assets/20418183/16770088/946271f8-484b-11e6-8c88-5dd2296252e1.png)
And idk if that's problem, but i can't rotate, fighting yes, rotate no. Sorry, but my english isn't very good.

**Comment by DaveyBiggers** [comment]
@Zootar - thanks for sorting this out!
@Termi1878 - I'm (re)closing this issue, since the original issue is fixed. Please open a new issue for your, er, new issue.
