### ISSUE TITLE
Problem Xml_schema

### ISSUE THREAD

**Issue by Helpdesk-CS** [Microsoft/malmo#176]
Hello,
I have a error in agent or in Malmo Human Action 
Error parsing Mission 

![parsing](https://cloud.githubusercontent.com/assets/20419080/16767022/a3427dc0-483d-11e6-8525-9d677309b636.PNG)

thanks

**Comment by DaveyBiggers** [comment]
Looks like your mission XML is malformed - if you paste it here, we can try to find the problem.

**Comment by Helpdesk-CS** [comment]
sorry but it's the original XML example ...

**Comment by DaveyBiggers** [comment]
Ha, that's a shame! Can't blame anyone else then... We'll take a look.

**Comment by timhutton** [comment]
@Helpdesk-CS What is your operating system? Can you confirm that you followed the install instructions and tried to run an agent from e.g. the `Python_Examples` folder in the unpacked zip?

**Comment by Helpdesk-CS** [comment]
Under Windows 10, and yes I tried the agents, including c#, I add the ReadLine() to have error consoles. And I got the same error: the above with HumanAction.

I think having succeeded in everything installed:
I also added two environment variables:
JAVA_HOME PATH (for ffmpeg) and MALMO_XSD_PATH


Sorry for this english ( is so bad :s ) ( i'am french)

**Comment by timhutton** [comment]
@Helpdesk-CS Could you please paste in the output of `run_mission.exe` (located in `Cpp_Examples`)? Also `CSharpExamples_RunMission.exe` (located in `CSharp_Examples`). Perhaps the exact output will give us more clues.

**Comment by Helpdesk-CS** [comment]
Error starting mission:
Internal error: the XML we generate does not validate: instance document parsing failed
:1:236 error: schemaLocation does not contain namespace-location pairs
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<MissionInit xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ProjectMalmo.microsoft.com MissionInit.xsd">
  <Mission><About><Summary/></About><ServerSection><ServerHandlers>
    <FlatWorldGenerator forceReset="false" generatorString="3;7,220*1,5*3,2;3;,biome_1" seed=""/>
<ServerQuitFromTimeUp description="" timeLimitMs="10000"/><ServerQuitWhenAnyAgentFinishes description=""/>
</ServerHandlers>
  </ServerSection>
    <AgentSection mode="Survival">
      <Name>Cristina</Name>
      <AgentStart/>
<AgentHandlers><ObservationFromFullStats/>
<VideoProducer viewpoint="0" want_depth="false">
  <Width>320</Width>
<Height>240</Height>
</VideoProducer>
<RewardForReachingPosition dimension="0">
  <Marker oneshot="true" reward="100" tolerance="1.100000023841858" x="19.5" y="0" z="19.5"/>
</RewardForReachingPosition>
<ContinuousMovementCommands turnSpeedDegs="180"/>
</AgentHandlers>
</AgentSection>
</Mission>
<ExperimentUID/>
<ClientRole>0</ClientRole>
<ClientAgentConnection>
  <ClientIPAddress>127.0.0.1</ClientIPAddress>
<ClientMissionControlPort>10000</ClientMissionControlPort>
<ClientCommandsPort>0</ClientCommandsPort>
<AgentIPAddress>127.0.0.1</AgentIPAddress>
<AgentMissionControlPort>10976</AgentMissionControlPort>
<AgentVideoPort>10004</AgentVideoPort>
<AgentObservationsPort>10155</AgentObservationsPort>
<AgentRewardsPort>10740</AgentRewardsPort>
</ClientAgentConnection>
</MissionInit>
```

**Comment by HAadams** [comment]
@Helpdesk-CS 
What specific actions did you take to get that error?
Did you try to load an xml file for "Curriculum" from MalmoHumanAction.exe?

**Comment by Helpdesk-CS** [comment]
I Want just test the programm with a example, but nothing works ...

**Comment by HAadams** [comment]
@Helpdesk-CS If by program you mean **MalmoHumanAction.exe**, then as @DaveyBiggers said, I think the problem is with the **xml** file you are trying to load.

So, if you are indeed running **MalmoHumanActin.exe**, try to load the **tutorial_6.xml** file which can be found in the python_examples folder and tell us what you get

**Comment by Helpdesk-CS** [comment]
The same problem, when i load the file tutorial_6.xml in the python_examples folder.

**Comment by Helpdesk-CS** [comment]
Ok i find this line on C#

`agentHost.startMission(mission, missionRecord); `

It is this line that throws the error.
If I put the comment line, subsequently starts correctly.

**Comment by Helpdesk-CS** [comment]
Suddenly, I got the message: "waiting for the mission to start",
It as something that I do not understand: how rules your connection from agent, Minecraft.
If from Minecraft, I create the login/password, I cannot find on the other side, the way to inform them

**Comment by Helpdesk-CS** [comment]
If I look at the changeLog, "Removed xsi::schemaLocation entries from all XML files, since not used."
Yet the Agent looking everywhere the location of this schemaLocation which does not exist in the sample XML files.

Es that the agent may not be updated relative to the file?

**Comment by DaveyBiggers** [comment]
If you remove the "startMission" line then the mission won't start, and the sample will wait at the "waiting for the mission to start" stage forever.

Can I check: how did you install Malmo?
Did you got to the release page  - https://github.com/Microsoft/malmo/releases - and install a pre-built version, or did you use the big green button at the top of GitHub to download a zip of the source? If you downloaded the source, you will also need to build it.

Also, can I ask where you installed Malmo to? What is the exact path to your Schemas folder?

**Comment by Helpdesk-CS** [comment]
I have download "Malmo-0.14.0-Windows-64bit.zip"
I have unzip in a folder, and i use direct from it.  
It as not in itself, installation to MALMÖ?

Folder 
->Malmo-0.14.0-Windows-64bit
          ->Schemas

**Comment by Helpdesk-CS** [comment]
Still the same error...
![capture](https://cloud.githubusercontent.com/assets/20419080/16950198/43f08b96-4dbf-11e6-9a11-28bf6faeacab.PNG)

**Comment by DaveyBiggers** [comment]
We still can't reproduce this error here. Can you tell us what you used to build your C# example? How exactly did you run it? And do you get the same error if you run the prebuilt one that came in the zip file - ie `CSharp_Examples\CSharpExamples_RunMission.exe`?

Do you get the same error if you run a python sample - eg

```
cd "H:\Projet Malmo\Malmo-0.14.0-Windows-64bit\Python_Examples"
H:\Projet Malmo\Malmo-0.14.0-Windows-64bit\Python_Examples>python MazeRunner.py
```

Finally, what do you see if you type `xsd version` into a command prompt?

**Comment by Helpdesk-CS** [comment]
Yes I use the pre-compiled in the ZIP, and also the version compiled with Visual-Studio 2015.

Here are trying with pyton:
And the version of xsd :
![cap2](https://cloud.githubusercontent.com/assets/20419080/16956987/d2e72ba0-4dda-11e6-87f6-503058ac92ef.PNG)
![cap1](https://cloud.githubusercontent.com/assets/20419080/16957015/f621af00-4dda-11e6-84c5-8f0fe77e7336.PNG)

**Comment by DaveyBiggers** [comment]
Thank you. The only thing I can think of is that there must be some corrupt copies of the XSD files getting picked up somehow. Can I check what your MALMO_XSD_PATH is set to?

**Comment by Helpdesk-CS** [comment]
Ok, so, I will re-download again all.

Yes my Path is : " H:\Projet Malmo\Malmo-0.14.0-Windows-64bit\Schemas "

**Comment by Helpdesk-CS** [comment]
Nothing works. I downloaded, I even tried with other version of the xsd (those of debian, and those in the source) files. I do not understand.

I tried the version 0.15, it is the same.

**Comment by DaveyBiggers** [comment]
Got it, I think - for some reason it fails if there is a space in your MALMO_XSD_PATH.
Try removing the space from "Projet Malmo", change the MALMO_XSD_PATH (remember to open a new command prompt so the change takes effect), and try again.

**Comment by Helpdesk-CS** [comment]
Yes ! Thanks ! it's WORK ! Very very congratulations!

**Comment by DaveyBiggers** [comment]
Hurrah! Glad we got there in the end!

**Comment by siolfyr** [comment]
I had this same error.  Glad this issue was here.

**Comment by jaysl** [comment]
> Got it, I think - for some reason it fails if there is a space in your MALMO_XSD_PATH.
> Try removing the space from "Projet Malmo", change the MALMO_XSD_PATH (remember to open a new command prompt so the change takes effect), and try again.

**Comment by jaysl** [comment]
> Got it, I think - for some reason it fails if there is a space in your MALMO_XSD_PATH.
> Try removing the space from "Projet Malmo", change the MALMO_XSD_PATH (remember to open a new command prompt so the change takes effect), and try again.

I'm getting an error called "Please set the MALMO_XSD_PATH environment variable" Can you please tell me how can I solve this
