### ISSUE TITLE
Mission and agent don't work.

### ISSUE THREAD

**Issue by Termi1878** [Microsoft/malmo#178]
Minecraft is now opened, but when I'm typing "start tutorial_1.py" nothing is going on. I tried with opened creative mode, but it still doesn't work. Just pop out new window for a second and everything is same.
![2](https://cloud.githubusercontent.com/assets/20418183/16771816/352f3d72-4852-11e6-9300-f3eb3688b018.png)
 I tried to open Python Agent too, but only this happens.
![3](https://cloud.githubusercontent.com/assets/20418183/16772002/c59a0586-4852-11e6-9a8d-7cf2626a73aa.png)

**Comment by DaveyBiggers** [comment]
Glad you got it sorted. What was the solution in the end?
