### ISSUE TITLE
Malmo ALE is stochastic?

### ISSUE THREAD

**Issue by lydiatliu** [Microsoft/malmo#182]
Breakout on Malmo ALE appears to be stochastic (target enters screen from different directions). Is there a way to make sure it is deterministic? @DaveyBiggers

**Comment by mcmachado** [comment]
This is not an ALE feature but a feature of the game Breakout. Stochasticity in the ALE, if implemented, is only on the time in which your action will take effect.

**Comment by lydiatliu** [comment]
ok thanks!
