### ISSUE TITLE
OSX - Using installed Python crashes immediately

### ISSUE THREAD

**Issue by FlamingFeesh** [Microsoft/malmo#188]
My issue is similar to [this](https://github.com/Microsoft/malmo/issues/36) one, where running agents through python leads to an immediate crash. Using the python from python.org crashes, returning the error `Segmentation Fault 11`, but running `/usr/bin/python/ my_agent.py` is fine. I would just use /usr/bin/python to run my agents, but the problem is I haven't found a way to install modules/packages to /usr/bin/python. So I see two solutions here:

1. Find a way to install modules/packages to /usr/bin/python.

I have not yet through googling found a solution. Installing through pip, brew, easy_install all goes to the python.org python. I've looked into commands to specify the installation location without much success.

2. Find out how to resolve `Segmentation Fault 11`.

If I am correct, is a C issue? I am not too familiar with C, so I don't know how to approach this.

**Comment by DaveyBiggers** [comment]
See also #44, #45, #46

**Comment by geekstor** [comment]
After some looking around, I have found a way around this that allows for the use of packages installed outside `/usr/bin/python`. It uses virtual environments, arguably how Python packages are meant to be managed (Though I am guilty of not using them much myself.)

First, if you do not already have `virtualenv`, go ahead and install it using `pip` or `easy_install`. Next, in the directory where you have Python scripts that use `MalmoPython`, create a new virtual environment: 
```bash 
$ virtualenv --python=/usr/bin/python2.7 env
```

Then, you can install any packages you like with: 
```bash 
$ source env/bin/activate
```
followed by:
```bash 
$ pip install ...`
```
OR
```bash 
$ easy_install ...
```
until you have all the packages you wish to use installed.

After that, you can exit the virtual environment: 
```bash 
$ deactivate
```

Finally, either create a new Python script that contains the following code at the beginning and takes in a script as an argument which it then executes (probably a much more elegant option), or add it to the beginning of any scripts you'd like to execute that require some packages not in `/usr/bin/python`:
```python
activate_this = `./env/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))
```
To run any Python scripts now, simply use `/usr/bin/python` as before.  The difference is that now packages installed in the virtual environment will automatically be searched for before visiting the system directories.

Now, there are certainly others way to go about solving this issue like modifying `PATH` variables or removing System Integrity Protection to use the system `pip`, but I think this is just a nicer way that I thought I'd share.

**Comment by timhutton** [comment]
@geekstor Yes, interesting. We had a suggestion at the workshop today to use Docker for this. We'd provide a Docker image with all the dependencies installed. (Docker uses containers which are like lightweight VMs.) We definitely need to improve the installation experience one way or another.

**Comment by FlamingFeesh** [comment]
@geekstor, based on initial testing, this method works great! Thank you very much.

**Comment by tnarik** [comment]
I am trying to set a docker container up because I prefer keeping every project as isolated as possible. is there already some ongoing work regarding this? Would be glad to help testing, etc.

**Comment by DaveyBiggers** [comment]
Hi @tnarik, a few people have mentioned docker, but as far as I know no one is maintaining a container for Malmo. A quick spot of googling found this: https://hub.docker.com/r/berlius/microsoft-malmo/ - but it looks quite out of date (v0.15).

**Comment by tnarik** [comment]
thanks. I found that but the issue for me is that `nvidia-docker` cannot be used to run from Mac. maybe @timhutton already got something else working.

I put a slightly different solution together based slightly in the suggesting from @katja-hofmann back in #291. It is not as performant as I would like on an Air, but seems to work well and allows full encapsulation of Malmo, which is what I wanted. Will play around with it a bit more and probably let you know.  and apologies for commenting on this issue regarding that. :/
