### ISSUE TITLE
Need to check Agent start coordinate in Tutorial

### ISSUE THREAD

**Issue by Vogen** [Microsoft/malmo#193]
In tutorial section 5, agent start coordinate was set to (x=0, y=56, z=0) to see the sunset. But after running sample code , the agent suffocated in a wall. It seems like agent was set into the ground.

I set start coordinate to (x=-5.5, y=227, z=-6.5) and the agent could see the sunset correctly.

**Comment by HAadams** [comment]
The coordinate (0, 56, 0) with yaw=90 assumes you use the given "More interesting generator string" for FlatWorldGenerator in tutorial_2.py and it also assumes you have the "Time" set to 12000 in order for the agent to face the sun. Basically, it assumes you follow the tutorial exactly.

**Comment by Vogen** [comment]
That's it. Tutorial is not clear enough.

**Comment by HAadams** [comment]
Yeah, I ran into the same teouble.

**Comment by DaveyBiggers** [comment]
Not going to change this - I think it's fair enough that the tutorial assumes the user is following the tutorial.
