### ISSUE TITLE
MalmoPython error

### ISSUE THREAD

**Issue by AyanGithub** [Microsoft/malmo#198]
```
Traceback (most recent call last):
  File "run_mission.py", line 20, in <module>
    import MalmoPython
ImportError: No module named MalmoPython
```

 is the error I get. I tried everything from checking the PATH and this and that... please help!

**Comment by HAadams** [comment]
@AyanGithub Are you using the source code (the files shown on the main page of this repo) or did you download the release from here [Download the latest pre-built version, for Windows, Linux or MacOSX](https://github.com/Microsoft/malmo/releases)?

**Comment by AyanGithub** [comment]
Thanks for the reply, From the source code

**Comment by AyanGithub** [comment]
Let me try the pre built version

**Comment by AyanGithub** [comment]
It's working now! I'm so dumb. Thank you so much!!!

**Comment by HAadams** [comment]
@AyanGithub No problem! Actually, if you want to play with the source code, you would have to build it to get it to work. (instructions on the main page) Otherwise, the pre-built version is what you want.
