### ISSUE TITLE
Item IDs returned from observations are not always unique

### ISSUE THREAD

**Issue by einsteinsci** [Microsoft/malmo#199]
Some items return the same string when returned from observations, even when the items have different in-game IDs. Examples:

* `minecraft:fish` and `minecraft:cooked_fish` are both observed as `item.fish`.
* The various records are all observed as `item.record`, despite their ids being `minecraft:record_SONGNAME`.

**Comment by DaveyBiggers** [comment]
Yes, this all needs rationalising. At the moment things specified through the XML, like the drawing decorator and initial inventory, use the ItemTypes and BlockTypes we provided in Types.xsd (eg "fish" and "cooked_fish") - this is nice, but specifying extra things like colour, variant and orientation (eg for block types) has to be done separately.

Commands and obeservations, however, come outside the remit of the XSD, and do things differently. The `craft` command currently only takes one parameter, which means there is no way to use the ItemTypes/BlockTypes to do something like "craft blue carpet". To get around that, the craft command also accepts strings like "tile.woolCarpet.blue", that Minecraft can parse.

The inventory observations, and entity observations, are returning something like that "tile.blahblah" string - though, as @einsteinsci points out, information is getting dropped (eg should be something like "item.fish" vs "item.fish.cooked"?)

All of this should be made consistent somehow, but we need to decide whether to:
a) Use the Types.XSD approach for everything, making sure the observations convert their string into the relevant Item/BlockType, variant, colour etc, and adding extra parameters to the craft command to specify colour etc.
b) Use the fully specified minecraft strings for everything, including the drawing decorator / initial inventory (and fixing the bug in the observations that loses information.)

What is the modding community used to? Are things like "tile.woolCarpet.blue" familiar constructs?
And what format will be easier to work with, agent side?

**Comment by DaveyBiggers** [comment]
Fixed in #226.

**Comment by einsteinsci** [comment]
@DaveyBiggers Actually, the modding community isn't used to either styles you use. We are used to the string ID and an integer damage value stored in the `ItemStack` class, which is basically anything in your inventory. Usually this is formatted as `mod_id:item_id` rather than the `tile.arbitrary_name` used by the `.lang` files. The `mod_id:item_id` format is the same one used in the `/give` in-game command, as well as when describing an item with JSON for various other in-game commands. For the case of blue carpet, the string ID would be `minecraft:carpet` with a damage value of `11`. Keep in mind that while not every block can be converted to an item for storage in the `ItemStack` class, all blocks still follow this format for the purposes of the `/setblock` in-game command.

I recommend you look at the string ID's listed on the [official wiki](https://minecraft.gamepedia.com/Data_values#Block_IDs)

**Comment by DaveyBiggers** [comment]
In the end we used the types etc in Types.xsd - which should be familiar to modders, as I believe the string IDs are the same (eg the records all have individual ids, etc). But instead of passing around the highly esoteric integer damage value we've made some attempt to parse it. Not all cases are covered, but for the majority of researchers (many of whom are new to Minecraft and have enough to worry about already), it should be powerful and intuitive enough to cover most use cases.

For example, instead of needing to know that blue dye = "dye" with a damage value of 4, you can specify type: "dye" colour: "blue".
We've extended this to other things too - eg for a creeper egg:
type: "spawn_egg" variant: "Creeper"
Or for a mob_spawner block:
type: "mob_spawner" variant: "Spider" etc.etc.

**Comment by einsteinsci** [comment]
As long as there's still support for integer values as well, I'm sure modders will be OK with it. In the case of certain blocks (such as fence posts and doors), the integer represents multiple fields combined, so your only option is an integer or bitwise or-compatible enum.
