### ISSUE TITLE
No module named MalmoPython

### ISSUE THREAD

**Issue by anindyabd30** [Microsoft/malmo#200]
When i am going to start a python example in cmd it says"D:\malmo-master\Malmo\samples\Python_examples>python run_mission.py
Traceback (most recent call last):
  File "run_mission.py", line 20, in <module>
    import MalmoPython
ImportError: No module named MalmoPython"

![capture](https://cloud.githubusercontent.com/assets/20485787/16892788/f17a893c-4b40-11e6-8c16-8d10bc7c6d62.PNG)

**Comment by farizrahman4u** [comment]
How did you install Malmo? Did you download the latest release? If git cloned the repo, you have to build the source yourself.

**Comment by chris-hawley** [comment]
i have the same problem when running the release.

**Comment by chris-hawley** [comment]
and..it seems the c# version also fails for the same reason. Can't find the DLL

**Comment by chris-hawley** [comment]
building from source solved the problem
