### ISSUE TITLE
Intermittent error in Human Action Component: "The string was not recognized as a valid DateTime."

### ISSUE THREAD

**Issue by katja-hofmann** [Microsoft/malmo#202]
The following error occurs intermittently when running missions through the HAC: "The string was not recognized as a valid DateTime. There is an unknown word starting at index 0." This occurs regularly on my setup, for example on sample mission "attic.xml" when jumping over the first obstacle. I use the HAC of the Malmo-0.14 windows release.

**Comment by DaveyBiggers** [comment]
I've seen this too. I think it's the reward signal - I wonder if we're sending malformed reward data, since the change to multidimensional rewards?
