### ISSUE TITLE
CMake Error: XSD_LIBRARY are set to NOTFOUND

### ISSUE THREAD

**Issue by wujiyoung** [Microsoft/malmo#208]
I git cloned the repo, and I build malmo myself, but there come an error:
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   iostreams
--   program_options
--   python
--   regex
--   system
--   thread
-- Found the following C# Mono versions: 4.4.1
-- Found Java: /usr/bin/java (found version "1.7.0.101") 
-- Found Java: /usr/bin/java (found version "1.7.0.101") 
-- Using Mono compiler version 4.4.1
-- Found the following C# Mono versions: 4.4.1
-- Using Mono compiler version 4.4.1
-- Found the following C# Mono versions: 4.4.1
-- Using Mono compiler version 4.4.1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XSD_LIBRARY (ADVANCED)
    linked by target "Malmo" in directory /home/tony/Documents/minecraft/malmo/Malmo/src

Any idea about it?

**Comment by DaveyBiggers** [comment]
Hi @wujiyoung, can you confirm that you installed all the dependencies, and made sure they were on the path? It looks as though CMake can't find CodeSynthesis.

**Comment by wujiyoung** [comment]
@DaveyBiggers You are right, there is no xsd library in my system. I have tried many ways to install the xsd library, but none of them worked, do you know how to install it? Thanks in advance.

**Comment by DaveyBiggers** [comment]
Did you try downloading and running this file: http://www.codesynthesis.com/download/xsd/4.0/windows/i686/xsd-4.0.msi ? (from the Code Synthesis website.)

**Comment by wujiyoung** [comment]
@DaveyBiggers , I am using ubuntu 14.04, can you give some advice in ubuntu?

**Comment by DaveyBiggers** [comment]
Did you find the build instructions? https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md

In particular, note this section:

> On Debian 7 and Ubuntu 14.04 only: Install CodeSynthesis XSD:
> 
> wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb
> sudo dpkg -i --force-all xsd_4.0.0-1_amd64.deb
> sudo apt-get install -f
> This step is needed because we require xsd version 4.0.
> (When mono-devel is updated, you will need to manually remove then reinstall xsd as above, because of the package conflicts.)

**Comment by wujiyoung** [comment]
Thank you very much, I fixed my problem.
Now there come another question, I run the run_mission.py, it come out ImportError: No module named MalmoPython, I found no file named MalmoPython.so, I want to know how to get it? I had build the project successfully.

**Comment by timhutton** [comment]
@wujiyoung If `make install` worked then `install/Python_Examples` should contain MalmoPython.so. Then the normal way to run the samples is:
```
cd install/Python_Examples
python run_mission.py
```

**Comment by wujiyoung** [comment]
I can finally ran the run_mission.py, thank you all very much

**Comment by DaveyBiggers** [comment]
Great news, thanks for persevering.

**Comment by WXFMAV** [comment]
I have met the same problem as above:
--------------------------------------------------------------------------------------------------------------------------
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XSD_LIBRARY (ADVANCED)
---------------------------------------------------------------------------------------------------------------------------
the xsd do have conflict with monodevel,and I follow the steps given by DaveyBiggers:
----------------------------------------------------------------------------------------------------------------------------
wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb
sudo dpkg -i --force-all xsd_4.0.0-1_amd64.deb
sudo apt-get install -f
-----------------------------------------------------------------------------------------------------------------------------
but the problem still occurs ? 
can some one help me?
