### ISSUE TITLE
Syntax Error in tutorial, without there being an actual error.

### ISSUE THREAD

**Issue by Spartick** [Microsoft/malmo#211]
![capture](https://cloud.githubusercontent.com/assets/20518268/16948386/ad567da8-4db4-11e6-99e3-0d70fae86ceb.JPG)

I'm trying to follow the tutorial, but failing already on the second step. The client loads up fine, but I'm unable to run missions (even examples), because python has decided it now requires parentheses everywhere?

**Comment by timhutton** [comment]
@Spartick Are you using Python version 3? You need to install Python 2.7, e.g. [python-2.7.12.amd64.msi](https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi)

**Comment by Spartick** [comment]
Thank you for responding do quickly! I'm sorry to say that this was indeed the issue. My apologies.

**Comment by timhutton** [comment]
@Spartick No problem! Glad we could help.
