### ISSUE TITLE
Stuck in a loop waiting for observations at the end of a mission

### ISSUE THREAD

**Issue by jorallo** [Microsoft/malmo#218]
I had this part of python code (copied from the tabular_q_learning.py) and I used Malmo 0.13 and worked fine. 

        # Start of the main Malmo loop (MISSION)
 
        # wait for a valid observation
        world_state = agent_host.peekWorldState()
        while world_state.is_mission_running  and all(e.text=='{}' for e in world_state.observations):
            world_state = agent_host.peekWorldState()
 
       # more stuff here, actions, rewards, etc.

Now, under Malmo 0.15, after a few actions, the mission should stop but instead it gets caught in the small loop forever. The only change I made to the code was to replace reward.value by val = reward.getValue(), but this shouldn't affect this other part of the code. I did this to accommodate for new version 0.15.

Any idea of what's going on? Thank you!

**Comment by jorallo** [comment]
An update. In another program having similar code I get this error during the previous iteration to the moment it is stuck:

Error parsing reward JSON: <unspecified file>(1): expected value:<?xml version="1.0" ...

So perhaps it has something to do with the way I parse rewards. I use this code:

        for reward2 in world_state.rewards:
 
            val = reward2.getValue()

            if val != 0:
               print " Summed reward:", val
               reward += val

which is very similar to the one found in tabular_q_learning.py; 
         current_r = sum(r.getValue() for r in world_state.rewards)

**Comment by jorallo** [comment]
@timhutton: Effectively, as you suggested. I inadvertently had an old version of MalmoPython.lib  in the directory. I'll be more careful next time I update the release. Thank you!

**Comment by timhutton** [comment]
@jorallo Glad it's working now!
