### ISSUE TITLE
ubuntu 16.04, MalmoPython.so, undefined symbol

### ISSUE THREAD

**Issue by jonygli** [Microsoft/malmo#222]
ubuntu 16.04, 

$>python run_mission.py 
Traceback (most recent call last):
  File "run_mission.py", line 20, in <module>
    import MalmoPython
ImportError: /home/jonli/Malmo-0.15.0-Linux-Ubuntu-15.10-64bit_withALE/Python_Examples/MalmoPython.so: undefined symbol: _ZN12ALEInterface7loadROMENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by DaveyBiggers** [comment]
Hi @jonygli, could you give us some more information? Did you build from source, or install the prebuilt release? And which build of the ALE are you using? Errors like this usually indicate a mismatch between the version of ALE that Malmo was built against, and the version that it's being run with.

**Comment by DaveyBiggers** [comment]
Hi @jonygli, did you get anywhere with this?

**Comment by DaveyBiggers** [comment]
Am closing this as I haven't heard anything for a while - please reopen if it's still an issue.
