### ISSUE TITLE
Malmo mod settings screen indicates that an account is validated if no password is given

### ISSUE THREAD

**Issue by JustinFletcher** [Microsoft/malmo#227]
When attempting to construct multi-agent missions, Malmo requires that each agent be authenticated. In order to authenticate a client, a valid Minecraft account username and password must be provided, and the user name must be mapped to a port - the same port through which the client will communicate. In the current release of Malmo, simply providing no password for a particular client-username pair causes Malmo to indicate that the client has been validated. This is not true, and the multi-agent mission will fail accordingly. This can be very confusing when debugging a new multi-agent mission.

**Comment by DaveyBiggers** [comment]
Fixed in a61935ea0541282b76c2611d26bd33730f2672d4
