### ISSUE TITLE
MalmoJavaJar.jar classes need non-default package

### ISSUE THREAD

**Issue by johnhainline** [Microsoft/malmo#232]
Currently the java binding classes are built with no package (and so they go into the default package). Using the default package is considered a bad practice (see http://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice). It also forces down-stream developers to either use the default package or to use Java Reflection to get access to those classes.
Please consider putting the generated Java classes into a package.

**Comment by drtuck** [comment]
Did you have a suggested pkg name?

**Comment by DaveyBiggers** [comment]
Have used `com.microsoft.msr.malmo` as a package name.

**Comment by johnhainline** [comment]
Totally realized I never said thanks. Thanks guys! It works beautifully!
