### ISSUE TITLE
Need an AgentQuitFromCollectingItem handler

### ISSUE THREAD

**Issue by FerdinandoR** [Microsoft/malmo#235]
So that a mission can be "collect that item".
This could also be used to quit after a given quantity of a given item has been collected (so that missions of the kind "collect these many red flowers, but don't collect any blue flower") can be implemented.

**Comment by timhutton** [comment]
@FerdinandoR There is one now: https://github.com/Microsoft/malmo/blob/master/Schemas/MissionHandlers.xsd#L1503

It will be in the next release (0.16.0). 

It doesn't have a quantity threshold though, which might be nice to add if people need it. Will close this issue for now.
