### ISSUE TITLE
XSD_LIBRARY are set to NOTFOUND

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#239]
I have met the same problem as above:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XSD_LIBRARY (ADVANCED)
the xsd do have conflict with monodevel,and I follow the steps given by DaveyBiggers:

wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb
sudo dpkg -i --force-all xsd_4.0.0-1_amd64.deb
sudo apt-get install -f

but the problem still occurs ?
can some one help me?

**Comment by WXFMAV** [comment]
search in Ubuntu App Store and intstall xercesc fixed this problem.
thanks.

**Comment by cverdes** [comment]
Thank you WXFMAV. Based on your suggestion I executed "`sudo apt-get install libxerces-c-dev`" on my Ubuntu 16.04 and it fixed the problem.
