### ISSUE TITLE
Creating a world without monster

### ISSUE THREAD

**Issue by wujiyoung** [Microsoft/malmo#245]
Hi, I had some trouble with malmo. There were some monsters in my world, and they killed my agent , which as a result suspend my learning job. Can I create a world without any monster?

**Comment by DaveyBiggers** [comment]
In your mission XML, make sure you set `AllowSpawning` to false - eg:
```
<ServerSection>
    <ServerInitialConditions>
        <AllowSpawning>false</AllowSpawning>
    </ServerInitialConditions>
</ServerSection>
```

Note that behaviour has changed slightly in the latest version - prior to version 0.16.0, this would only disable spawning _while a mission was running_ - ie if you leave the world lying around for a while in between running experiments, things may well spawn. In 0.16.0 spawning should be disabled by default, all the time, and will only be enabled if `AllowSpawning` is explicitly set to true.

In 0.16.0 you can also specify _what_ you'd like to spawn - eg to allow friendly mobs, but disallow monsters, you could do the following:

```
<ServerSection>
    <ServerInitialConditions>
        <AllowSpawning>true</AllowSpawning>
        <AllowedMobs>Pig Sheep Cow Chicken Ozelot Rabbit Villager</AllowedMobs>
    </ServerInitialConditions>
</ServerSection>
```

Final caveat - this doesn't override the behaviour of mob_spawners - if you explicitly add a mob_spawner (eg using DrawingDecorator DrawBlock) then it will spawn, regardless of the `AllowSpawning` settings. 

Of course, normal Minecraft spawning conditions still apply - eg monsters need dark conditions to spawn, pigs need grass, etc.etc. So you could also protect your agent by keeping it bright - eg set the time to midday and disallow the day/night cycle (see `AllowPassageOfTime`).

**Comment by wujiyoung** [comment]
Thank you. I did use DrawingDecorator DrawBlock, I don't know what are mob_spawners, but I guess there were them in my world. So, can I remove the mob_spawners?

**Comment by DaveyBiggers** [comment]
You'd know if you'd used a mob_spawner - see `mob_fun.py` in the samples for an example - so I assume that wasn't the cause of your problem. Can I ask which version of Malmo you were using when you had the problem? As I say, in 0.16.0 mobs should only spawn if you've specifically turned spawning on, so an unexpected mob attack would be a bug. In 0.15.0 it is more likely to happen, depending on how you are using Malmo.

**Comment by wujiyoung** [comment]
I updated my project to 0.16.0, and it seemed no mob attack again.
I got another question, I added function agent_host.close() in my code, but there came out an 

> AttributeError: 'AgentHost' object has no attribute 'close'

I found `void close();` in AgentHost.h, how did it came about?

**Comment by DaveyBiggers** [comment]
Glad to hear your agent is now safe from mob attacks.

AgentHost::close() is a private method, called by the AgentHost destructor. It's not exposed as part of the API, and you shouldn't need to call it. If you have any more questions about this, perhaps you could open a new issue for them?
Cheers!
