### ISSUE TITLE
Mission.h can not be found in Ubuntu 14.04

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#246]
cmake --build .
returns error:
 fatal error: Mission.h: no such file or directory
 #include <Mission.h>
inclued from MissionSpec.h
is that my problem the same as what is disscussed in MacOS?
I have tried to forced install xsd as:
wget http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb
sudo dpkg -i --force-all xsd_4.0.0-1_amd64.deb
sudo apt-get install -f
but the problem still occurs.
should I add command as what has been don in MacOS as below:
wget https://raw.githubusercontent.com/bitfehler/xs3p/master/xs3p.xsl -P $TRAVIS_BUILD_DIR/Schemas
+export MALMO_XSD_PATH=$TRAVIS_BUILD_DIR/Schemas
 cd $TRAVIS_BUILD_DIR
 mkdir build
 cd build
 cmake -DCMAKE_BUILD_TYPE=Release ..
 make
-ctest -VV
+ctest -E Integration -VV
My system is Ubuntu 14.04

**Comment by DaveyBiggers** [comment]
Hi @WXFMAV, just to check, have you been following the linux build instructions here: https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md ?

If you look in your build/Malmo/src folder, do you see Misison.h etc in there?

And what do you see if you type `/usr/bin/xsd version` into a terminal?

**Comment by WXFMAV** [comment]
it was because my MALMO_XSD_PATH is illegal, now it works well. thanks.

**Comment by DaveyBiggers** [comment]
Glad it's working now, thanks for letting us know.
