### ISSUE TITLE
Discrete Command "Use" leaves the inventory as is

### ISSUE THREAD

**Issue by geekstor** [Microsoft/malmo#247]
The Continuous Command "Use" depletes the used object from the inventory gradually. "Use" works in discrete mode now as well :smile:. However, using the Discrete "Use" command does not change the inventory. Suggestion: Reducing the number of the used object from the Inventory by 1 on each "Use" command for the Discrete version.

**Comment by DaveyBiggers** [comment]
Pending merge of #287:
"use" should now deplete the inventory, and "attack" should now add the block drops to the inventory if a block is destroyed.
Have also implemented normal Minecraft logic to prevent blocks being placed in a square that is currently occupied by an entity. (Stops the agent suffocating themselves by building a block around their own head...)
