### ISSUE TITLE
Cpp_Example throws error with specified world XML

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#249]
I build malmo from source, and all the demos work well.
and I tried "sample_mission_loader.py", to load several example worlds such as:

mission_file_no_ext = '../Sample_missions/classroom/basic'
mission_file_no_ext = '../Sample_missions/classroom/obstacles'
mission_file_no_ext = '../Sample_missions/classroom/simpleRoomMaze'  

All they works well.
however, probem occurs in **Cpp_Example**, when I try to load a world based on this demo.
what I change in the code is 

   **MissionSpec my_mission("../Sample_missions/classroom/vertical.xml",true);
   //MissionSpec my_mission;**

the run_mission demo does work well when I use "MissionSpec my_mission", but shows errors when I use "MissionSpec my_mission("../Sample_missions/classroom/vertical.xml",true);" 
so I can not load my specified world . errors are showed as

**terminate called after throwing an instance of 'xsd::cxx::tree::parsing<char>'
  what():  instance document parsing failed**

I do need to develop my project with C plus plus instead of Python, is there anyway to make this Cpp_Example work with customed world well ?thanks.

**Comment by DaveyBiggers** [comment]
The MissionSpec constructor takes a raw XML string, rather than a filename.
What you want to do is read the `Sample_missions/classroom/vertical.xml` file in first, and then pass it to MissionSpec.

(This is just what sample_missions_loader.py is doing here:
```
mission_file = mission_file_no_ext + ".xml" 
with open(mission_file, 'r') as f: 
    print "Loading mission from %s" % mission_file 
    mission_xml = f.read() 
    my_mission = MalmoPython.MissionSpec(mission_xml, True) 

```
What you need is the C++ equivalent of this.)

**Comment by WXFMAV** [comment]
Indeed it works. I pasted my solutions as below:
......
**ifstream in("vertical.xml");
string str( (istreambuf_iterator<char>(in)),(istreambuf_iterator<char>()));
MissionSpec my_mission(str,true);
my_mission.timeLimitInSeconds(10);**
......
thanks so much.

**Comment by DaveyBiggers** [comment]
Great, thanks for posting your solution, glad you are up and running now.
