### ISSUE TITLE
 Your Access Transformers be broke!

### ISSUE THREAD

**Issue by jpritchett** [Microsoft/malmo#260]
Hi I get this error when I try to run 0.16.0 osx , 64 bit

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> Your Access Transformers be broke!
any clues to get past this please?

**Comment by DaveyBiggers** [comment]
Hi @jpritchett, sorry you are having problems. This crops up from time to time and there are a number of different causes. We'd need more details to diagnose it, but you might find some answers by looking at the issues other people having this problem have created: #42, #50, #154, #164, #203.
Hope that helps!

**Comment by jpritchett** [comment]
Thanks I'll have a poke around these .

**Comment by DaveyBiggers** [comment]
I'm assuming this is no longer a problem - please reopen and provide further details if it is. Cheers.

**Comment by prabindh** [comment]
In Windows 10, just needed to close and relaunch the command prompt to resolve this issue. Happened several times till finally it was successful.
