### ISSUE TITLE
DDOS attack caused by ClientPool behaviour

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#263]
Example scenario:
- A client pool of 30 clients.
- 2 researchers each running 15 experiments simultaneously (all on the same pool)
- each experiment is short (30 secs, say)
- code that keeps retrying startMission until it succeeds.
- client pool order the same for each experiment

With 30 clients, and 30 experiments, chances are all clients are going to be busy all the time. If the start times of the experiments are evenly distributed, then a new mission will be starting every second. AgentHost's default behaviour is to send the MissionInit message to each client in the pool in order until it finds a client that is free. With all AgentHosts using the same pool in the same order, then the client at the top of the list will receive at least one MissionInit every second, whether it's busy or not.

Unfortunately, in order to know whether or not the mission can be accepted, the mod currently decodes the MissionInit message, parsing and deserialising the XML. This is an expensive operation, and having to do this every second effectively cripples the client.

A less naive approach to ClientPool usage will mitigate the problem, but we should look at making the mod less vulnerable to the DDOS in the first place. We shouldn't need to completely parse/deserialise the XML, for instance.

**Comment by timhutton** [comment]
Might be related to the slowdown/memory issue, perhaps? #288

**Comment by DaveyBiggers** [comment]
We should be able to significantly improve this now, as a result of the changes introduced in #429.

**Comment by DaveyBiggers** [comment]
Using a fairly extreme test script, bombarding Malmo with complex mission XML messages from a bunch of different processes simultaneously, I can reproduce the ddos. Here the XML decoding accounts for around 20% of Minecraft's client activity, according to Minecraft's inbuilt profiler.
![ddos_attack](https://cloud.githubusercontent.com/assets/13402052/25945978/f2b24920-3640-11e7-8ab8-295e92b6129c.png)
The actual cost is higher than this, since the decode happens twice - once in the client thread (picked up by the profiler), but also in a background thread (which is not profiled).

**Comment by DaveyBiggers** [comment]
And here's the results after slightly tweaking the AgentHost::startMission code so that the single-agent case uses the same code path as the multi-agent case - eg the client gets reserved in a separate step prior to being sent the Mission XML. This reservation step doesn't require sending/decoding the XML, and ensures that busy clients are filtered from the pool before the sending/decoding step happens.
The decoding step is now insignificant, according to the profiler.
![ddos_attack_foiled](https://cloud.githubusercontent.com/assets/13402052/25946162/e466519e-3641-11e7-9bb8-3772054623d5.png)
Although it's a very small change to the code, it's quite a significant change to the startup process, so I won't check this in until it's been thoroughly tested.
