### ISSUE TITLE
Unmapped exceptions resulting in SEHException in C#

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#267]
To reproduce:
Move schemas folder so that MALMO_XSD_PATH is wrong.
Open the C# sample run_mission project.
Attempt to use the xml construction for MissionSpec, eg:
```
MissionSpec mission = new MissionSpec();
string xml = mission.getAsXML(false);
MissionSpec mission2 = new MissionSpec(xml, true);

```
Malmo will throw an exception somewhere, but the user will only see a generally unhelpful SEHException.

**Comment by timhutton** [comment]
Fixed by a5fe2a9
