### ISSUE TITLE
can we load world model (xml file) from internet?

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#269]
we do really want to train our model in a very complex environment,such in a giant city.
we know that there is  a variety of world models online  while are built by minecraft fans.
do our malmo support to download and assemble these models now?
or we have to write the xml files by our self?

**Comment by DaveyBiggers** [comment]
Check out the FileWorldGenerator - http://microsoft.github.io/malmo/0.16.0/Schemas/MissionHandlers.html#element_FileWorldGenerator - it allows you to specify a Minecraft saved world for your mission to run in.

**Comment by WXFMAV** [comment]
Sorry that, I followed the instructions in [http://microsoft.github.io/malmo/0.16.0/Schemas/MissionHandlers.html#element_FileWorldGenerator](url) - but faild to run the specified Minecraft saved world.what I have done is:
(1)launch Minecraft
(2)create a new world. (now there is a new world with complex environment)
(3)press ESC  and save the world.
(4) jump to "PRE_DIR/Minecraft/run/saves/2016-08-10"  the directory which saves the world.
(5) open an demo xml file(I use the default_flat_1.xml) and change the section<FlatWorldGenerator generatorString="3;7,220*1,5*3,2;3;,biome_1"/> into <FileWorldGenerator src="PRE_DIR/Minecraft/run/saves/2016-08-10"/>
(6) run python demo to load the xml file.
but the demo stunk at
**DEBUG: Sending MissionInit to 127.0.0.1 : 10000
DEBUG: Looking for client, received reply from 127.0.0.1: MALMOOK
Waiting for the mission to start..................................................................................................
................................................................................................................................................**
is there anything I did wrong?
thanks so much.

**Comment by katja-hofmann** [comment]
Hi @WXFMAV, it looks like the python agent cannot find a free Minecraft
client. Could you confirm that you have started the client using the
launchClient script appropriate for your platform, as described here:
https://github.com/Microsoft/malmo/blob/master/README.md#launching-minecraft-with-our-mod

Katja

**Comment by WXFMAV** [comment]
Yeah, I changed the port of Minecraft and now ,there shows error as
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
DEBUG: Looking for client, received reply from 127.0.0.1: MALMOOK
**Waiting for the mission to start .Error: Mission ended abnormally: Server world-creation handler failed to create a world: Unable to copy /home/hualinhe/MalmoPlatform/build/install/Minecraft/run/saves/2016-8-11 11_30_40 - is the hard drive full?
........................................................**
my hard drive is not full, for I can run it manually by open the saved world from minecraft window.
is there anything else wrong?
I use the command **python tutorial_2.py** to launch malmo, and I change xml string into :
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
            <Mission xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            
              <About>
                <Summary>Hello world!</Summary>
              </About>
              
              <ServerSection>
                <ServerHandlers>
                  <FileWorldGenerator src="/home/hualinhe/MalmoPlatform/build/install/Minecraft/run/saves/2016-8-11 11_30_40"/>
                  <ServerQuitFromTimeUp timeLimitMs="30000"/>
                  <ServerQuitWhenAnyAgentFinishes/>
                </ServerHandlers>
              </ServerSection>
              
              <AgentSection mode="Survival">
                <Name>MalmoTutorialBot</Name>
                <AgentStart/>
                <AgentHandlers>
                  <ObservationFromFullStats/>
                  <ContinuousMovementCommands turnSpeedDegs="180"/>
                </AgentHandlers>
              </AgentSection>
            </Mission>

**Comment by WXFMAV** [comment]
What's more, after the error occurs, I jump to  **/home/hualinhe/MalmoPlatform/build/install/Minecraft/run/saves/** but can not found the world directory I have saved.  it seems that the saved world is deleted by the malmo platform.

**Comment by katja-hofmann** [comment]
Hi @WXFMAV,

Your mission xml file looks correct. I see that you are running this from
the build path. Could it be that you recompiled Malmo after saving the
world file there? This would have regenerated the whole folder. I recommend
saving the file in a location outside the build folder. Once the mission
xml points to an existing file the world should be loaded correctly.

Kind regards,
Katja

**Comment by WXFMAV** [comment]
Yes, it works!
I copied the world file outside of the build directory and then restart every program,
I do not rebuild the malmo platform every time, it seemed strange why I have to copy it outside of the directory, but now it works fine.
thank you so much.
