### ISSUE TITLE
How can I access the position of "Quit blocks" in ClassroomDecorator?

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#272]
in the world specified by "sample_missions/classrooms/basic.xml",there would always be a "quit blocks" which is yellow in the mission, agent would quit automatically when it reaches that block.
my project want to get the position of this block when my C++ program is running, however, it seems that the position of the block is randomly appeared in the classroom and I haven't found an xml item that can specify the position of this block.
**is there anyway to get the position of the "quit block"
or can we set the position of the "quit block" mannually?**
thanks.

**Comment by timhutton** [comment]
Hi @WXFMAV. The position of the block is generated on the Mod side. Currently the only way to retrieve it is to request an ObservationFromGrid of sufficient size and look for the block type.

Can you give more details about what you're trying to achieve? Hopefully then we can work out the best way to provide the data you need.

**Comment by WXFMAV** [comment]
Yes, I am now work with ObservationFromGrid, thanks!
