### ISSUE TITLE
Cache.properties.lock errors on Gradle builds when running Multiple Malmo instances from same folder 

### ISSUE THREAD

**Issue by geekstor** [Microsoft/malmo#276]
Gradle builds [fail] (http://stackoverflow.com/questions/30724682/gradle-failed-to-refresh) [occasionally] (https://issues.gradle.org/browse/GRADLE-1801) [with] (https://issues.gradle.org/browse/GRADLE-2795) [cache-related] (http://stackoverflow.com/questions/24634363/gradle-intellij-idea-13-bug) [errors](https://discuss.gradle.org/t/unable-to-generate-tar-with-gradle-cache-properties-locked/12639) when multiple builds are performed from the same directory (even when the builds are in a non-overlapping sequence, not necessarily in parallel.) 

One solution is to remove 
```ROOT_MALMO_DIR/.gradle/GRADLE_VERSION(2.7)/taskArtifacts/cache.properties.lock``` or even ```ROOT_MALMO_DIR/.gradle/GRADLE_VERSION(2.7)/taskArtifacts/*```. However, this is not really safe (and has caused problems in the past.)

Another workaround is to set ```--project-cache-dir``` to some other directory like ```~/cache```. Suggestion: ```launchClient.sh``` (and similarly ```lauchClient.bat```) can be changed so that the last three lines are as follows: 

```bash 
./gradlew setupDecompWorkspace --project-cache-dir $CACHE_DIR
./gradlew build --project-cache-dir $CACHE_DIR
./gradlew runClient --project-cache-dir $CACHE_DIR
```

where ```$CACHE_DIR``` is taken from a command line argument, ```--cache-dir```, which if not set defaults to something like ```~/cache```.

**Comment by timhutton** [comment]
I'm struggling to reproduce this on a VM. Using Ubuntu 16.04 in VirtualBox on a Windows 10 host, launching 4 Minecraft instances, after quite a few times (~10 so far) they all just start up fine.

Wondering if is an issue with our GPU cluster, specifically the syncing of the home folder.

**Comment by DaveyBiggers** [comment]
We think the best solution is the same as for #320 - i.e set GRADLE_HOME to a different folder for each copy.
