### ISSUE TITLE
Team rewards (or other co-operative reward schemas) for multi-agent missions

### ISSUE THREAD

**Issue by jorallo** [Microsoft/malmo#279]
For multi-agent missions with no teams (competitive), we can have that the first agent completing the goal gets the reward. However, there is no direct way of having several agents in a team sharing their rewards (e.g., once the mission is completed the reward is given to all of them).

A team reward handler (through the definition of team) would be an option but a more flexible option might be the definition of an (asymmetric) "sharing reward" handler, where the mission specifies the % of reward of agent A that is given to (shared with) agent B and vice versa. Teams would be special cases.

**Comment by DaveyBiggers** [comment]
This was closed in #396, confusingly.
