### ISSUE TITLE
disallowing continuous movement

### ISSUE THREAD

**Issue by qlai** [Microsoft/malmo#283]
is there a way to disallow continuous movement when initializing with default mission? It seems that (in general too) there are commands to allow things, but not to disallow....

**Comment by DaveyBiggers** [comment]
There's `removeAllCommandHandlers();` in the API - it will nuke all the handlers and give you a clean slate, so you could use it right after constructing the default missionSpec to get rid of the continuous command handler.

Also, `allowContinuousMovementCommand` etc actually has the effect of _disallowing_ all _other_ commands - if an allow list exists, then only the commands that are on it will be allowed.

(Personally, I find it's usually safer and easier to do these things with the XML - that way you have complete control, and don't need to worry about the interpretive choices the API has to make for you. But we've tried to make the API work for the common use cases.)
