### ISSUE TITLE
can not launch multiagent mission--MultiMaze.py error

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#284]
I tried the Python_Examples MultiMaze in Ubuntu, but failed to get into multi agent mission.
my command is as below.
`python MultiMaze.py`
in another terminals, I run
`python MultiMaze.py --role 1`
the first one keeps outputing 
**Waiting for the mission to start............................................................**
the second one just outputs that
**Will run as role 1
Mission 0 --- starting at 0, 200, 0
DEBUG: Sending MissionInit to 127.0.0.1 : 10001
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
DEBUG: Looking for server, received reply from 127.0.0.1: MALMOS127.0.0.1:41812
DEBUG: Sending MissionInit to 127.0.0.1 : 10001
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
DEBUG: Looking for client, received reply from 127.0.0.1: MALMOBUSY**
I want to test multi agent mission in my project, should I set something like the client pool so that to launch multi agents mission?

**Comment by timhutton** [comment]
@WXFMAV Multi-agent missions require you to launch two instances of the Minecraft client - did you do that?

By default they will take ports 10000 and 10001, so MultiMaze.py should then work.

**Comment by WXFMAV** [comment]
@timhutton I have tried to launch two intance of the Minecraft client, but now the second command
<python MultiMaze.py --role 1>
always return **Mission ended abnormally:Unable to connect to Minecraft server in multi-agent mission.** 
and the seconde Minecraft window show something like:
**Failt to log in(Try restart your game** 
I wonder if it was because I launch both of the two client in my local computer?
show I run the two client in two different computer？
thanks.

**Comment by DaveyBiggers** [comment]
You can run them both on the local computer, that should be fine. It sounds like the second agent couldn't authenticate - at the moment, you need an authenticated Minecraft login for each agent you want running in a multi-agent mission. In other words, to run two agents in a mission together you will need to have purchased two Minecraft accounts. Once you've done that, within the Minecraft client you can use the `malmo mod options->logins -> add user` to enter your usernames and passwords, and Malmo will use that to log the agents in. (You might need to restart the Minecraft clients for it to take effect.) (Note that the login details are written *in plain text* into a file in your Malmo folder, so don't use the same password you use for all your internet banking... also, make sure you only have one client running when you enter the details, or the other client might stomp on the config file and you'll have to enter them all again...)

**Comment by WXFMAV** [comment]
@DaveyBiggers  It seems that I haven't found any **logins** in **options**. do you mean the **options** button in the Minecraft Main window?
![options](https://cloud.githubusercontent.com/assets/9674091/17891127/8ec0415c-696c-11e6-9ace-4ea29ab28aad.png)

**Comment by DaveyBiggers** [comment]
@WXFMAV from the main menu screen, click on the "Mods" button, then choose "Microsoft Malmo Platform" from the list on the left, and select "Config".

Alternatively, from the in-game menu, select "Mod Options...".

**Comment by WXFMAV** [comment]
OK! thanks.

**Comment by shaw-wong** [comment]
![screen shot 2018-04-27 at 18 26 22](https://user-images.githubusercontent.com/36874058/39352860-5a0b7c0a-4a49-11e8-88e2-6150e9914e3e.png)
Hi, I run into the same problem. But I could not find the "Microsoft Malmo Platform" in the "Mods" button. The picture shows all I have. Any idea? Thanks
