### ISSUE TITLE
Mod slows down with repeated missions.

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#288]
Running 1200 missions of ~30s with maximum overclocking causes noticeable speed drops. Seen on different machines. 

Might be related to the mysterious phenomenon of all memory being taken but sum of processes' memory use is far less. 

Could be the software rendering? (If only affects VMs.)

Could be the GDI handles issue on resizing the window?

**Comment by DaveyBiggers** [comment]
If this is the same problem I'm seeing, I suspect there is some sort of virtual memory churn going on. After leaving a VM running Minecraft for a while, I see no significant memory leakage _within_ the VM (according to `top`, at least), but outside the VM Windows is reporting around 80% memory usage -  almost none of which is listed as being used by any of the processes in Task Manager... According to RamMap most of it us being used by the System PTE. If my sketchy understanding is correct, it seems that more memory is going into maintaining the map from virtual memory to physical memory than is actually being _used_ by anything... The VM seems to be the culprit: VirtualBox.exe is producing around 2000 page faults per second, and the hard drive is being constantly thrashed at around 96% usage, presumably as a result.

So I'm not sure memory is actually _leaking_, as such... but it seems to be getting fragmented to the point where tracking the memory is, er, taking all the memory.

**Comment by DaveyBiggers** [comment]
Here's a plot of the memory use I've been tracking (as reported by `top`) for MazeRunner.py, running continually in an Ubuntu 15.10 VM. Not overclocked.

![memuse_linux](https://cloud.githubusercontent.com/assets/13402052/17964572/d6c3adc2-6ab1-11e6-923c-6b5a4edfcc87.png)

**Comment by DaveyBiggers** [comment]
However, performance did degrade noticeably. Here are typical plots of the yaw observations, and the (x,z) positions for each frame. These are for near the start of the run:
![mission_7](https://cloud.githubusercontent.com/assets/13402052/17965847/9c7326de-6ab6-11e6-99e6-aadf30a9c339.png)
![mission_7_path](https://cloud.githubusercontent.com/assets/13402052/17965849/9f7b6ddc-6ab6-11e6-96be-e681b847141b.png)

And these are later in the run:
![mission_1408](https://cloud.githubusercontent.com/assets/13402052/17965915/e01f3dc8-6ab6-11e6-9cbc-9f01c7e9b717.png)
![mission_1408_path](https://cloud.githubusercontent.com/assets/13402052/17965953/0ef8b3fe-6ab7-11e6-9f45-3f2c5ee29d1f.png)

**Comment by DaveyBiggers** [comment]
This turns out not to be a gradual decay in performance, but a sudden drop, which seems to indicate that this is not, after all, related to a suspected memory leak. The drop-off took place after around 180 missions. It corresponds to the sudden drop in frame rate, seen here:

![rates](https://cloud.githubusercontent.com/assets/13402052/17968351/449d7924-6ac4-11e6-9c01-392ab5b32496.png)

The player's yaw is updated both in the client tick (which stayed constant at 20hz), and in the render tick. A drop in render speed will therefore result in "jerkier" turning, as the yaw is updated by larger amounts, less often. The oscillations in the yaw observation are presumably an unfortunate artefact of this.

What caused the drop in frame rate is a mystery though. Will do some more testing. Perhaps it is related to the drop in memory usage?

**Comment by DaveyBiggers** [comment]
Update: have left this running, and there has been a further drop in frame rate:
![linux_rates](https://cloud.githubusercontent.com/assets/13402052/17970794/ef247b12-6acf-11e6-842d-97b3fe60b36b.png)

...with a corresponding drop in performance:

![mission_2907](https://cloud.githubusercontent.com/assets/13402052/17970766/d7276498-6acf-11e6-986a-7eabe3e06ce2.png)
![mission_2907_path](https://cloud.githubusercontent.com/assets/13402052/17970775/da1ee162-6acf-11e6-9587-2414e5c692a2.png)

**Comment by DaveyBiggers** [comment]
Rebooted the VM and Windows, and re-ran this experiment overnight, with nothing much else running. The result is remarkably similar - the frame rate drops at around 180 missions:

![rates_clean](https://cloud.githubusercontent.com/assets/13402052/18001416/d3d324f2-6b7a-11e6-80f8-00cd2bff07f5.png)

**Comment by DaveyBiggers** [comment]
Same behaviour exhibited on Ubuntu 14.04:

![rates_ubuntu1404](https://cloud.githubusercontent.com/assets/13402052/18010557/eaa5911e-6ba8-11e6-89c5-bd4690dcba5f.png)

Interesting that the observation rate stabilises when the frame rate drops - this seems to happen in all three of these plots. Indicates some competition between the threads?

**Comment by katja-hofmann** [comment]
Could the observation stabilizing be a red hering? I suspect that once the
frame rate drops there's no more major changes in the agent's position /
yaw / etc. So there might be some savings on updates making it easier to
pump out a steady stream of never changing observations.

**Comment by DaveyBiggers** [comment]
Simpler test, just sitting in a never-ending mission, not recording, sending no commands, just counting the observations and frames that arrive each second:

![run_0](https://cloud.githubusercontent.com/assets/13402052/18124469/4e46a7b6-6f6a-11e6-9d0f-03c1e0b54b40.png)

The same drop in frame rate occurs...
New hypothesis: SNOW.
In this graph, I manually started Minecraft snowing - the dip in frame rate starts from that point. The frame rate never recovers, even after the snow ends.

![run_snowii](https://cloud.githubusercontent.com/assets/13402052/18124521/81502c4a-6f6a-11e6-990a-9f044a7248c3.png)

**Comment by DaveyBiggers** [comment]
And here's the same test, but with weather turned off.
The dips in frame rate are nowhere near as severe, and seem to be related to when the computer went to sleep (as my beautiful annotations demonstrate.)

![annotated_plot](https://cloud.githubusercontent.com/assets/13402052/18124635/f06f23c4-6f6a-11e6-9bf5-7e248b60264c.png)

**Comment by DaveyBiggers** [comment]
Unsurprisingly, snow has no effect if you are deep underground - this is the same test, but 200 blocks lower in the y-axis, and therefore a long way underground.
The frame rate is much higher overall. The fluctuations might be linked with the day/night cycle? But there is no dramatic slowdown, despite adding snow at various points.

![plot_deep_underground](https://cloud.githubusercontent.com/assets/13402052/18127640/95581a18-6f79-11e6-8a5b-545c61bcdb50.png)

The frame-rate drop has been reported by several people here, but most of our research has been carried out in sealed rooms, where snow never falls. Which would seem to rule the snow hypothesis out, but...

**Comment by DaveyBiggers** [comment]
...here is the same experiment, but this time positioned only just below the surface. The snow starts around 900 seconds in. (The valley before that is where the VM went to sleep and awoke again, and the starting peak is due to server lag - there was nothing to render at that point, so rendering was very quick.)

![plot_32](https://cloud.githubusercontent.com/assets/13402052/18127922/3278779c-6f7b-11e6-8432-39188ab43675.png)

**Comment by DaveyBiggers** [comment]
Am closing this, since there is an easy workaround now that #264 is done.
But I suspect that there are other factors at work which can cause other slowdowns. I suggest we open new issues for them as and when they come up.
