### ISSUE TITLE
Add API to control mob spawning

### ISSUE THREAD

**Issue by edran** [Microsoft/malmo#289]
Right now (as far as I understand) the only way to spawn monsters is to either:

* Use the command `/summon $MOB_ID $PARAMS*`
* Use `DrawBlock` to create a spawner and have the game continuously spawn monsters.

However this makes it hard to create scenarios where interaction with mobs is required (e.g. to obtain food), especially when trying to create identical conditions between experiments. 

A hacky solution is to [at the start of the mission] teleport the agent to a given position, run the command, and teleport back, but this is ugly and I feel like there should be a better way to deal with this.

**Comment by DaveyBiggers** [comment]
Closed by #324
