### ISSUE TITLE
Can Malmo Platform be used under non X window server?

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#291]
In order to accelerate the trainning process, we want to run the Malmo platform in a Server computer,
which has no X window client.
I have tried in ubuntu terminal(Ctrl+Alt+F1).
but the client cannot be launched.
We want to know if we can run Malmo in a server without any X window?
thanks

**Comment by DaveyBiggers** [comment]
Hi, we've had some success running Minecraft headless on a Linux cluster using a virtual display. You need an x-server, and Minecraft will need open-gl installed. I can try to dig out the steps we used here, though I suspect it varies quite a bit from cluster to cluster.

**Comment by okdshin** [comment]
@DaveyBiggers 
I want to know how to run Minecraft on remote machines without screens. I have tried but failed.
Please describe the steps or any hints.

**Comment by WXFMAV** [comment]
@DaveyBiggers It seemed that there are **no gui** Minecraft versions On the internet. I wonder if the minecraft included in Malmo platform can be set to run in **no gui** mode?

**Comment by DaveyBiggers** [comment]
@WXFMAV I believe you are thinking of the `nogui` flag for running a dedicated Minecraft _server_. This is no good to us, as we require a running _client_ - there is no `nogui` flag for the client (it wouldn't make sense to anyone other than researchers, since a game that you can't see is unlikely to be a big seller...)

However, as stated above, it is possible to run the client using a virtual display. If you give us some details of your environment we might be able to provide some pointers.

**Comment by katja-hofmann** [comment]
Hi @WXFMAV and @okdshin,

if you work on Linux, these steps may help:

 - Install `xinit` (a tool for manually running an X display server)
 - Start xinit (e.g., in a separate shell, or detach the process: `nohup xinit & disown`)
 - Export the display variable and start the Minecraft client: `DISPLAY=:0.0 launchClient.sh`

Let us know if these help. If you are working on other platforms some changes may be required (we tested these on Ubuntu only).

**Comment by WXFMAV** [comment]
@DaveyBiggers  My server is CentOS instead of Ubuntu, my system version is:
`CentOS Linux release 7.2.1511 (Core) `
`3.10.0-327.el7.x86_64`
command `runlevel` returns `N 3` indicating that  there is no x-server.
And I wonder if a linux system running in` level 3` can be installed with `xinit`?

**Comment by okdshin** [comment]
@katja-hofmann Thanks! I can run Minecraft on ubuntu server without any display by following your steps.
@DaveyBiggers Just for your information, on my ubuntu server, runlevel indicates N 2 now and I had to install gdm.

**Comment by katja-hofmann** [comment]
Hi @okdshin - thanks for confirming that this solution works for you.

@WXFMAV - `runlevel 3` should be fine. Were you able to install `xinit` and run it? If not what error message do you get?

**Comment by diazf** [comment]
here's what i've done,

0. make sure /etc/X11/Xwrapper.config is set to "allowed_users=anybody"

then within a separate screen window,

1. nohup xinit -- :<FREE_DISPLAY_NUMBER> &
2. DISPLAY=:<FREE_DISPLAY_NUMBER>.0 ./launchClient.sh

**Comment by jakezhaojb** [comment]
@katja-hofmann 
Following your instruction, I got an error saying 
```
Exception in thread "main" java.io.IOException: Input/output error
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:91)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1096)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1154)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:51)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by MicroSTM** [comment]
@katja-hofmann I tried you solutions but still could not launch client. When I tried to start xinit, I got error message: 

> Fatal server error:
> (EE) no screens found(EE)
