### ISSUE TITLE
Do more regular garbage collection in the Mod

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#312]

**Comment by DaveyBiggers** [comment]
![gcplot](https://cloud.githubusercontent.com/assets/13402052/18719836/ed6057d6-8020-11e6-91aa-184c61653212.png)

**Comment by DaveyBiggers** [comment]
Experimenting with calling the garbage collector each time the Mod enters the dormant state (ie between missions). The memory usage stays pretty constant so far, compared to previous runs.

**Comment by DaveyBiggers** [comment]
After running for 27 hours, things still look good.
(Can't remember all the details of the different environments plotted here - most of this data was collected a while ago - but the general pattern is always the same: rapid gobbling of memory, up to some maximum amount, then a serious spurt of activity from the GC, then a slow steady climb. By contrast, Series 7 shows remarkably steady memory use, with no real sign of creep.)

![gcplot2](https://cloud.githubusercontent.com/assets/13402052/18748904/5d5e30de-80cc-11e6-83f8-8799604b6540.png)
