### ISSUE TITLE
Generated XML Fails Validation : attribute 'destroyAfterUse' is not declared for element 'FlatWorldGenerator' 

### ISSUE THREAD

**Issue by rodneyp290** [Microsoft/malmo#319]
I just pulled the latest https://github.com/Microsoft/malmo/commit/229cd9ea3b66ab0a1e4ec0d4a855f5f5b8e023cd from the master branch, rebuilt everything, and tried to run the tutorials, and I recieve the following error for each tutorial_#.py file.
```
Error starting mission: Internal error: the XML we generate does not validate: instance document parsing failed
:1:562 error: attribute 'destroyAfterUse' is not declared for element 'FlatWorldGenerator'
```
Looking at the git commit messages and the Github Network Graph, it looks like the issue would have been introduce to the master branch with the merge of the https://github.com/Microsoft/malmo/pull/304 pull request

**Comment by rodneyp290** [comment]
Unsure whether to post this or not, because it is clearly a validation bug & someone who knows the code will probably find this a trivial problem to fix; but the below is my ad-hoc attempt to find the bug with little knowledge of code base, in case it is useful

**Current Situation of investigation:**
- Problem is somewhere in between the definition of FlatWorldGenerator in Schemas/MissionHandlers.xsd and MissionInitSpec.cpp, line 64?

**Summed up investigation so find:**
- looked at Malmo/src/AgentHost:
  - `AgentHost::startMission()` - line 86
    - Looked at `AgentHost::initializeOurServers()` - line 124 ... got lost
    - Searched for `validate` & found `AgentHost::generateMissionInit()` - line 160, which had a try catch block that throw an Exception with a matchin error message
        - follow initialisation of `test_output` line 167 to `MissionInitSpec` Constructor line 64 of MissionInitSpec.cpp
        - This is where my *winging it* approach ran into a brick wall as I don't know much about the use of .xsd files to generate code, and the function seemed to use code generated by use MissionInit.xsd?
- However, I can kinda read XML Schema and I grepped the Schemas Directory for FlatWorldGenerator
  - Mission.xsd & MissionHandlers.xsd were the resulting files, with the definition in the later and it does have the destroyAfterUse flag... so I'm guessing problem is somewhere between this file, and MissionInitSpec.cpp line 64

**Comment by DaveyBiggers** [comment]
Hi Rodney, sorry you are having this problem. I wonder if it's related to something @TGlas has experienced - #201 - basically, something appears to be out of step somewhere with the XSD files.
Can I ask - when you say you rebuilt everything, how exactly did you do that?
Can you remind me what operating system you are using?
And do you have any old copies of the XSDs lying around? (Check especially that your MALMO_XSD_PATH, if you have one, is pointed to the right version of the files.)

Also, thanks for your follow-up post - it's always useful to get more information!

**Comment by rodneyp290** [comment]
... Okay, turns out it was my MALMO_XSD_PATH was pointing to the clone of my fork (which I wasn't up to date) instead of the direct clone which I was testing. * facepalm *
Thanks for the quick solution. All better when I point correct folder. :smile:

**Comment by DaveyBiggers** [comment]
Great, glad things are sorted now!
