### ISSUE TITLE
Build fails in Window 10

### ISSUE THREAD

**Issue by smartcook** [Microsoft/malmo#320]
1.Download the latest pre-built version：Malmo-0.17.0-Windows-64bit.zip
2.Install 7-Zip: 7z1602-x64
3.Install FFMPEG: ffmpeg-latest-win64-static
4.Install CodeSynthesis: xsd-4.0.msi
5.Install Python: python-2.7.12.amd64.msi
6.Install the Java SE Development Kit (JDK): jdk-8u101-windows-x64.exe
7.Install the Microsoft Visual Studio 2013 redistributable: vcredist_x64.exe
8.Set MALMO_XSD_PATH： MALMO_XSD_PATH=D:\Malmo-0.17.0-Windows-64bit\Schemas

D:\Malmo-0.17.0-Windows-64bit\Minecraft
launchClient

 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar FAILED

**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':splitServerJar'.
> Could not expand ZIP 'C:\Users\zsc\.gradle\caches\minecraft\net\minecraft\minecraft_server\1.8\minecraft_server-1.8.jar'.**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 22.443 secs
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':splitServerJar'.
> Could not expand ZIP 'C:\Users\zsc\.gradle\caches\minecraft\net\minecraft\minecraft_server\1.8\minecraft_server-1.8.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.69 secs
****************************
 Powered By MCP:
 http://modcoderpack.com/
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************
Version string 'unspecified' does not match SemVer specification
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':splitServerJar'.
> Could not expand ZIP 'C:\Users\zsc\.gradle\caches\minecraft\net\minecraft\minecraft_server\1.8\minecraft_server-1.8.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 42.496 secs

**Comment by katja-hofmann** [comment]
Hi @smartcook,

Sorry you're having trouble getting the project to build.

This looks like a permissions problem. Could you set the gradle home
directory to a location where you have write access, as described here:
http://stackoverflow.com/questions/28838699/how-to-set-gradle-cache-location

Please let us know whether this helps, or if you continue to see exceptions.

Best,
Katja

**Comment by smartcook** [comment]
Yes, It resolve the problem. Thanks very much.
Config the GRADLE_HOME and GRADLE_USER_HOME
