### ISSUE TITLE
Suggestion: Discrete strafing actions

### ISSUE THREAD

**Issue by salaniz** [Microsoft/malmo#321]
There is currently no direct way of moving sideways using the discrete actions. The action set `[movenorth, moveeast, movesouth, movewest]` seems unnatural from the agent's point of view.

My current implementation looks at the current yaw of the agent and then uses the corresponding action from the above set that gives me `move left` or `move right`.
I used the information provided in the [Minecraft Wiki](http://minecraft.gamepedia.com/Coordinates) to associate yaw with north/south/east/west.

I think it would be a nice addition to have a `strafe left/right` natively in the discrete action set.

Edit:
This information about orientation and yaw is needed:
**Yaw - > Direction it points to:**
0 -> South
90 -> West
180 -> North
270 -> East

**Comment by edran** [comment]
Let's remember to include this into #301.

**Comment by DaveyBiggers** [comment]
Fixed in #390 
"strafe 1" -> sidestep to the right.
"strafe -1" ->sidestep to the left.
