### ISSUE TITLE
ImportError:  DLL load failed.

### ISSUE THREAD

**Issue by Eulerianial** [Microsoft/malmo#328]
I am seeing an import error for MalmoPython.
It says specified module note found. But in the Python_Example directory, I do see the MalmoPython lib.
Am I missing something?

**Comment by Bloodknight** [comment]
https://github.com/Microsoft/malmo/wiki/Troubleshooting

**Comment by DaveyBiggers** [comment]
Am assuming this is fixed so am closing this issue. If there are still problems, feel free to reopen, but first it would be worth searching for other cases of this - several other people have reported the same issue.

**Comment by fujimototaiga** [comment]
I have the same problem. I searched for other cases, but they didn't help.
I'm using Windows10, Python2.7 64bit, and installed Malmo-0.17.0-Windows-64bit.
Inserting current path mentionded in #166 also didn't work.
> import os, sys
> sys.path.insert(0, os.getcwd()) 
> 
> import MalmoPython 
> ...

Please help!




C:\Users\fujim\Documents\malmo\Malmo-0.17.0-Windows-64bit\Python_Examples>python run_mission.py
Traceback (most recent call last):
  File "run_mission.py", line 22, in <module>
    import MalmoPython
ImportError: DLL load failed: The specified module could not be found

C:\Users\fujim\Documents\malmo\Malmo-0.17.0-Windows-64bit\Python_Examples>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
