### ISSUE TITLE
Python tutorials use default port 10000 with no apparent way to change to MC running on port 10001

### ISSUE THREAD

**Issue by Bloodknight** [Microsoft/malmo#329]
G:\Malmo\Python_Examples>python tutorial_1.py
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.

**Comment by rodneyp290** [comment]
Based on the MultiMaze.py example, you need to create a ClientPool, add the client entry and use the extended startMission method signature.
... _testing theory_ ... yep it works! :tada: 
Add the following Client Pool Code (adapted from lines 124-128 of MultiMaze.py) before the startMission try catch block :
```python
# Create a client pool here and add an entry for a Minecraft Client at 127.0.0.1:10001
client_pool = MalmoPython.ClientPool()
client_pool.add( MalmoPython.ClientInfo( "127.0.0.1", 10001 ) )
```
and then change the startMission call to:
```python
agent_host.startMission( my_mission, client_pool ,my_mission_record, 0, "" )
```
Attached is an example of tutorial 1 with the necessary changes.
[tutorial_1.py.txt](https://github.com/Microsoft/malmo/files/466001/tutorial_1.py.txt)

**Comment by Bloodknight** [comment]
Works a treat, ty :)

**Comment by DaveyBiggers** [comment]
Yes, the scope of the tutorial was intentionally fairly limited, so the client pool didn't make the cut. We rely on the samples to illustrate some of the more advanced concepts.
At some point perhaps we should either expand the original tutorial, or add a second one to cover things like the client pool.

**Comment by maxisbest** [comment]
hi rodneyp290: 
i tried the tutorial_1.py changed by you, and it worked greatly. but when I tried to use your method on tutorial_2.py, it didn't work. Why? could you please have a try?
