### ISSUE TITLE
VS2015 building

### ISSUE THREAD

**Issue by Bloodknight** [Microsoft/malmo#330]
All appeared well apart from a few warnings (i figure most projects have a few), ctest debug provided some test failures for which i have not an idea how to solve shown here [http://pastebin.com/YhPGAcjQ] with timing in case its relevent; which it appears to be for at least one

**Comment by DaveyBiggers** [comment]
The timeout from two_diggers is to be expected - it relies on having two sets of valid Minecraft login credentials. (At some point we'll make this more obvious.)

The other failures are more concerning, but without any more details it's impossible to say what is causing them to fail.

You can try re-running the individual tests with more verbose output. What do you see if you do this, for example:
```
ctest -C Debug -R mob_fun -VV
```
?
(that's two V's, not one W...)

There's no reason why Malmo shouldn't work with VS2015 by the way - the build instructions are currently for 2013, but they should work just as well with 2015.

**Comment by Bloodknight** [comment]
@DaveyBiggers ok, thank you for the extra testing details, these have helped massively.

Side thought:  I'm wondering if some of these examples should/could be added to the documentation in section 11 of the building for windows page, also the VV vs W thing, that was 5 minutes of pre morning coffee rage right there as i'd started testing just before i got the alert for your comment.

Many of my problems appear to stem from the lack of base flexibility, in part solved by @rodneyp290 in #329 so they should be considered trivial, however 10000 is apparently a popular port used by several applications, in my instance uTorrent (which doesn't seem to have a way to change).

two-diggers fails because it needs two client, when i launch two clients it crashes the first one, and then refuses to connect to the second, i am assuming there is something i have yet to learn about multi client/server interactions so i'll leave this one for now.

I do seem to have a slightly more difficult problem with tests 44 and 45, opening a new issue for them

**Comment by DaveyBiggers** [comment]
Am closing this as I believe it's no longer relevant.
