### ISSUE TITLE
C++ Example Building on Windows

### ISSUE THREAD

**Issue by ghost** [Microsoft/malmo#331]
Hi, 
I need help compiling the CPP example code on Windows. The description in the tutorial with (just run cmake . and cmake --build .) does not work. 
So far I've installed and changed various things:
# Install cmake
# Install VS2013 Express, add bin directory to PATH
# Download and extract boost_1_60_0, run bootstrap.bat and bjam.exe to compile libraries
# Change CMakeLists.txt:

```
 # remove zlib in find_package
 # add --> set( BOOST_ROOT "C:/boost_1_60_0" )
 # and --> set( BOOST_LIBRARYDIR "C:/boost_1_60_0/lib" )
```
# Uncomment the following from FindXsd.cmake:

```
 #if( ( ${SYSTEM_NAME} MATCHES "^Linux-Ubuntu-14.04.*$" ) OR ( ${SYSTEM_NAME} MATCHES "^Linux-Debian-7\\..*$" ) OR ( ${SYSTEM_NAME} STREQUAL "Mac-64bit" ) )
#  set( EXTRA_XSD_EXECUTABLE_NAMES "xsd" )
#endif()
```

After that the cmake . command succeeds, but the cmake --build . command still fails with a lot of errors like the one below:
error LNK2019: unresolved external symbol "public: void __thiscall malmo::ArgumentParser::parseArgs(int,char const \* *)" (?parseArgs@ArgumentParser@malmo@@QAEXHPAPBD@Z) referenced in function _main [D:\run_mission.vcxproj]

For me this indicates that the malmo.lib library is not found, however it is correctly added to the loader. 
Please advise on how to proceed so that the compilation works. 
I think other users would also appreciate updating the Getting Started page on how to correctly setup the development environment for C++.

BR

See the whole build output below:
1>------ Rebuild All started: Project: Noelle, Configuration: Debug Win32 ------
1>  -- Boost version: 1.60.0
1>  -- Found the following Boost libraries:
1>  --   chrono
1>  --   date_time
1>  --   filesystem
1>  --   iostreams
1>  --   program_options
1>  --   regex
1>  --   system
1>  --   thread
1>  --   atomic
1>  -- Configuring done
1>  -- Generating done
1>  -- Build files have been written to: D:/
1>  Microsoft (R) Build Engine version 12.0.40629.0
1>  [Microsoft .NET Framework, version 4.0.30319.42000]
1>  Copyright (C) Microsoft Corporation. All rights reserved.
1>  
1>  Build started 11/09/2016 17:15:45.
1>  Project "D:\ALL_BUILD.vcxproj" on node 1 (default targets).
1>  Project "D:\ALL_BUILD.vcxproj" (1) is building "D:\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
1>  InitializeBuildStatus:
1>    Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
1>  CustomBuild:
1>    All outputs are up-to-date.
1>  FinalizeBuildStatus:
1>    Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
1>    Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
1>  Done Building Project "D:\ZERO_CHECK.vcxproj" (default targets).
1>  Project "D:\ALL_BUILD.vcxproj" (1) is building "D:\run_mission.vcxproj" (3) on node 1 (default targets).
1>  InitializeBuildStatus:
1>    Touching "run_mission.dir\Debug\run_mission.tlog\unsuccessfulbuild".
1>  CustomBuild:
1>    All outputs are up-to-date.
1>  ClCompile:
1>    All outputs are up-to-date.
1>  Link:
1>    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"D:\Debug\run_mission.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib lib\Malmo.lib "C:\boost_1_60_0\stage\lib\libboost_chrono-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_date_time-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_filesystem-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_iostreams-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_program_options-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_regex-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_system-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_thread-vc120-mt-gd-1_60.lib" "C:\boost_1_60_0\stage\lib\libboost_atomic-vc120-mt-gd-1_60.lib" "C:\Program Files (x86)\CodeSynthesis XSD 4.0\lib\vc-12.0\xerces-c_3D.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Debug/run_mission.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Debug/run_mission.lib" /MACHINE:X86 /SAFESEH  /machine:X86 run_mission.dir\Debug\run_mission.obj
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::ArgumentParser::parseArgs(int,char const \* *)" (?parseArgs@ArgumentParser@malmo@@QAEXHPAPBD@Z) referenced in function _main [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall malmo::ArgumentParser::getUsage(void)const " (?getUsage@ArgumentParser@malmo@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: bool __thiscall malmo::ArgumentParser::receivedArgument(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?receivedArgument@ArgumentParser@malmo@@QBE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::MissionSpec::MissionSpec(void)" (??0MissionSpec@malmo@@QAE@XZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionSpec::timeLimitInSeconds(float)" (?timeLimitInSeconds@MissionSpec@malmo@@QAEXM@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionSpec::requestVideo(int,int)" (?requestVideo@MissionSpec@malmo@@QAEXHH@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionSpec::rewardForReachingPosition(float,float,float,float,float)" (?rewardForReachingPosition@MissionSpec@malmo@@QAEXMMMMM@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::MissionRecordSpec::MissionRecordSpec(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0MissionRecordSpec@malmo@@QAE@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordMP4(int,__int64)" (?recordMP4@MissionRecordSpec@malmo@@QAEXH_J@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordObservations(void)" (?recordObservations@MissionRecordSpec@malmo@@QAEXXZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordRewards(void)" (?recordRewards@MissionRecordSpec@malmo@@QAEXXZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordCommands(void)" (?recordCommands@MissionRecordSpec@malmo@@QAEXXZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: double __thiscall malmo::TimestampedReward::getValue(void)const " (?getValue@TimestampedReward@malmo@@QBENXZ) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::WorldState::WorldState(void)" (??0WorldState@malmo@@QAE@XZ) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::AgentHost::AgentHost(void)" (??0AgentHost@malmo@@QAE@XZ) referenced in function _main [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::AgentHost::~AgentHost(void)" (??1AgentHost@malmo@@QAE@XZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::AgentHost::startMission(class malmo::MissionSpec const &,struct malmo::MissionRecordSpec const &)" (?startMission@AgentHost@malmo@@QAEXABVMissionSpec@2@ABUMissionRecordSpec@2@@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: struct malmo::WorldState __thiscall malmo::AgentHost::getWorldState(void)" (?getWorldState@AgentHost@malmo@@QAE?AUWorldState@2@XZ) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::AgentHost::sendCommand(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?sendCommand@AgentHost@malmo@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>D:\Debug\run_mission.exe : fatal error LNK1120: 19 unresolved externals [D:\run_mission.vcxproj]
1>  Done Building Project "D:\run_mission.vcxproj" (default targets) -- FAILED.
1>  Done Building Project "D:\ALL_BUILD.vcxproj" (default targets) -- FAILED.
1>  
1>  Build FAILED.
1>  
1>  "D:\ALL_BUILD.vcxproj" (default target) (1) ->
1>  "D:\run_mission.vcxproj" (default target) (3) ->
1>  (Link target) -> 
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::ArgumentParser::parseArgs(int,char const \* *)" (?parseArgs@ArgumentParser@malmo@@QAEXHPAPBD@Z) referenced in function _main [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall malmo::ArgumentParser::getUsage(void)const " (?getUsage@ArgumentParser@malmo@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: bool __thiscall malmo::ArgumentParser::receivedArgument(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?receivedArgument@ArgumentParser@malmo@@QBE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::MissionSpec::MissionSpec(void)" (??0MissionSpec@malmo@@QAE@XZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionSpec::timeLimitInSeconds(float)" (?timeLimitInSeconds@MissionSpec@malmo@@QAEXM@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionSpec::requestVideo(int,int)" (?requestVideo@MissionSpec@malmo@@QAEXHH@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionSpec::rewardForReachingPosition(float,float,float,float,float)" (?rewardForReachingPosition@MissionSpec@malmo@@QAEXMMMMM@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::MissionRecordSpec::MissionRecordSpec(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0MissionRecordSpec@malmo@@QAE@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordMP4(int,__int64)" (?recordMP4@MissionRecordSpec@malmo@@QAEXH_J@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordObservations(void)" (?recordObservations@MissionRecordSpec@malmo@@QAEXXZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordRewards(void)" (?recordRewards@MissionRecordSpec@malmo@@QAEXXZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::MissionRecordSpec::recordCommands(void)" (?recordCommands@MissionRecordSpec@malmo@@QAEXXZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: double __thiscall malmo::TimestampedReward::getValue(void)const " (?getValue@TimestampedReward@malmo@@QBENXZ) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::WorldState::WorldState(void)" (??0WorldState@malmo@@QAE@XZ) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::AgentHost::AgentHost(void)" (??0AgentHost@malmo@@QAE@XZ) referenced in function _main [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: __thiscall malmo::AgentHost::~AgentHost(void)" (??1AgentHost@malmo@@QAE@XZ) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::AgentHost::startMission(class malmo::MissionSpec const &,struct malmo::MissionRecordSpec const &)" (?startMission@AgentHost@malmo@@QAEXABVMissionSpec@2@ABUMissionRecordSpec@2@@Z) referenced in function __catch$_main$0 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: struct malmo::WorldState __thiscall malmo::AgentHost::getWorldState(void)" (?getWorldState@AgentHost@malmo@@QAE?AUWorldState@2@XZ) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>run_mission.obj : error LNK2019: unresolved external symbol "public: void __thiscall malmo::AgentHost::sendCommand(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?sendCommand@AgentHost@malmo@@QAEXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$_main$2 [D:\run_mission.vcxproj]
1>D:\Debug\run_mission.exe : fatal error LNK1120: 19 unresolved externals [D:\run_mission.vcxproj]
1>  
1>      0 Warning(s)
1>      20 Error(s)
1>  
1>  Time Elapsed 00:00:00.38
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command "cmake --build ." exited with code 1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Bloodknight** [comment]
I found yesterday after multiple problems that the best approach was to follow the build it yourself approach here [https://github.com/Microsoft/malmo/blob/master/doc/build_windows.md](https://github.com/Microsoft/malmo/blob/master/doc/build_windows.md) rather than the dowwnload version.

Also i note that you are compiling 32 bit, was left with the impression that this whole system was 64 bit only, which would explain the fact that you are getting linker errors, it would be looking for a 32 bit lib vs  a 64 bit lib. I'm sure there are other ways to interope 32 with 64 but i'm not entirely sure of the top of my head how

**Comment by DaveyBiggers** [comment]
@AerysT - how did you get started? Did you install a pre-built Malmo from the releases page - https://github.com/Microsoft/malmo/releases - and follow the installation instructions?

**Comment by AerysT** [comment]
@DaveyBiggers Yes, I installed the Malmo-0.17.0-Windows-64bit.zip release and followed the installation guide appropiately. Everything works fine except the C++ compilation

**Comment by Bloodknight** [comment]
i can confirm my initial suspicion that this is because x86 is not supported, you must compile using x64

**Comment by AerysT** [comment]
Thanks Bloodknight, I'll try that!

**Comment by AerysT** [comment]
So, it seems I'm stuck with one last problem:

Now the x64 build tools in C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64 are used
Now when I compile I get the error:
D:\run_mission.cpp : fatal error C1902: Program database manager mismatch; please che
ck your installation [D:\run_mission.vcxproj]
As I found out this is due to a mspdb120.dll x86/x64 mismatch
This mspdb120.dll is only found in C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\ folder, not inside x86_amd64. 
When I remove the library completely, the compiler complains that it is missing. 

Can you please advice on how to proceed (or give me a download link to the x64 mspdb120.dll? I already searched for it on the web and re-installed VS twice without success)
Thanks

**Comment by DaveyBiggers** [comment]
Hi @AerysT, are you using a Visual Studio 2013 x64 command prompt? It should set up all the necessary environment variables for VS to build in 64 bit.
There are some details here: https://msdn.microsoft.com/en-us/library/x4d2c09s(v=vs.120).aspx

**Comment by AndKram** [comment]
cmake -G "Visual Studio 15 Win64" 
Malmo 0.35 should not now need any re-distributables from VS 2013.
