### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by Bloodknight** [Microsoft/malmo#339]
Test project G:/Malmo/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 44
    Start 44: PythonIntegrationTests_human_action_help

44: Test command: C:\Python27\python.exe "G:/Malmo/Malmo/samples/Python_examples/human_action.py" "--help"
44: Environment variables:
44:  PYTHONPATH=G:/Malmo/build/Malmo/src/PythonWrapper/Debug
44:  LD_LIBRARY_PATH=G:/Malmo/build/Malmo/src/PythonWrapper/Debug
44: Test timeout computed to be: 1500
44: Traceback (most recent call last):
44:   File "G:/Malmo/Malmo/samples/Python_examples/human_action.py", line 28, in <module>
44:     from PIL import Image
44: ImportError: No module named PIL
1/2 Test #44: PythonIntegrationTests_human_action_help ...***Failed    0.13 sec
test 45
    Start 45: PythonIntegrationTests_human_action

45: Test command: C:\Python27\python.exe "G:/Malmo/Malmo/samples/Python_examples/human_action.py" "--test"
45: Environment variables:
45:  PYTHONPATH=G:/Malmo/build/Malmo/src/PythonWrapper/Debug
45:  LD_LIBRARY_PATH=G:/Malmo/build/Malmo/src/PythonWrapper/Debug
45: Test timeout computed to be: 1500
45: Traceback (most recent call last):
45:   File "G:/Malmo/Malmo/samples/Python_examples/human_action.py", line 28, in <module>
45:     from PIL import Image
45: ImportError: No module named PIL
2/2 Test #45: PythonIntegrationTests_human_action ........***Failed    0.12 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.35 sec

The following tests FAILED:
         44 - PythonIntegrationTests_human_action_help (Failed)
         45 - PythonIntegrationTests_human_action (Failed)
Errors while running CTest

This seems to refer to  the Python Image Library, appears to be completely unsupported according to found resources.

neither the installer or pip will install PIL

**Comment by Bloodknight** [comment]
Using alternative library 'pillow' seems to work

**Comment by DaveyBiggers** [comment]
See also #150.
We should be mentioning this as a dependency in our installation instructions. Will fix the documentation.

**Comment by Bloodknight** [comment]
When running the human action test (45) when first taking control the cursor spins wildly, only returning to agent control and back again seems to allow the user to actually control the character and complete the test, since i'm new here i don't know what is supposed to happen, but that seems a little odd. Wondering if the difference between the two libs, original PIL and pillow causes this reaction. 

There seems to be conflict between 2 separate applications that want control of keyboard and mouse, perhaps some kind of delay is required between the two apps

**Comment by DaveyBiggers** [comment]
Am closing this - the original issue has been fixed and I've never been able to reproduce the second issue with the human action test.
