### ISSUE TITLE
cmake cpp_example error (includes additional warning)

### ISSUE THREAD

**Issue by Bloodknight** [Microsoft/malmo#343]
CMake Warning at C:/Program Files/CMake/share/cmake-3.6/Modules/FindBoost.cmake:1459 (message):
  No header defined for zlib; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

CMake Error at cmake/FindXsd.cmake:31 (if):
  if given arguments:

```
"(" "MATCHES" "^Linux-Ubuntu-14.04.*\$" ")" "OR" "(" "MATCHES" "^Linux-Debian-7\\..*\$" ")" "OR" "(" "STREQUAL" "Mac-64bit" ")"
```

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)

What i literally do not understand is that there is an executable in the folder, so malmo could not have used this cmakelists.txt to build it since it fails, both command prompt and gui... there is definitely something shenaniganey going on

**Comment by DaveyBiggers** [comment]
Ah, good spot.

FindXsd.cmake refers to ${SYSTEM_NAME}, which is initialised in the Malmo root CMakeLists.txt file. So when Malmo builds the sample, SYSTEM_NAME exists; when the user builds it from within the sample folder, it doesn't.

**Comment by Bloodknight** [comment]
Added PR which i think just got labelled #344 

I of course have not tested on linux (no spare computer), on MAC OS (no spare £,000s). I did rather pilfer the code directly from the main malmo build files, so it should work flawlessly.
