### ISSUE TITLE
Suggestion: The method to finish mission anytime

### ISSUE THREAD

**Issue by okdshin** [Microsoft/malmo#348]
Currently we have to register some conditions to finish a mission. The kinds of conditions are reaching a time limit, reaching command quota, reaching any positions and touching any kinds of blocks.
It's very limited. If we can finish a mission anytime and so we can make more flexible conditions to do so, we can construct more complex and interesting missions (e.g. agents have to go some positions in a specific order).
Now I register condition of jump command quota and when I want to finish the mission, I have the agent jump.

**Comment by salaniz** [comment]
Have a look at #294 that added a quit command for the agent. Just include `MissionQuitCommands` to your XML and then you should be able to use the command `"quit"`. I haven't tried it myself yet, though.

**Comment by okdshin** [comment]
Oh! I overlooked #294. That is what I want exactly.
Thank you @salaniz!
