### ISSUE TITLE
Add 3D movement commands to discrete movement

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#352]
As #219 alludes to, the "jump" command isn't particularly useful at the moment.
We need commands for moving up/forward, up/back, etc.
(The difficulty will be coming back down again - in order to have a chance at keeping state/action pairs relevant, we need the agent to descend immediately, not at the speed of Minecraft's own gravity.)

See also #321.

**Comment by Bloodknight** [comment]
I seem to recall the original conversation only being about jump, but you need to give full single movement steps to all points of the 3x3 cube so that the step reward is consistent
