### ISSUE TITLE
AbsoluteMovementCommands can cause problems with chunk loading

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#353]
Similar issues to #195 can occur if an agent is teleported to a chunk that hasn't yet been loaded.
This seems to be an issue in vanilla Minecraft too - eg using the "tp" slash command can produce the same behaviour.

In addition, the game can get into a state where the player is stuck in an empty chunk (nothing but blue and empty sky), and the chunks never get loaded. Not sure if this ever happens in vanilla Minecraft.

**Comment by DaveyBiggers** [comment]
Am upping this to a P1, since teleporting a large distance (say, 1000 blocks away) can break chunk-loading entirely, leaving the player stuck in an empty chunk, with no fix other than to quit the game and reload.

**Comment by DaveyBiggers** [comment]
![image](https://cloud.githubusercontent.com/assets/13402052/18638272/6adec530-7e87-11e6-8556-0c4df847785e.png)

Been staring at this for a while now. Have turned to Twin Peaks for inspiration. Seldom has a song title fitted a bug so perfectly:

https://www.youtube.com/watch?v=jdb9BTYIXkM

**Comment by Bloodknight** [comment]
I have witnessed this issue in vanilla minecraft before, usually on initial load, but did also happen once when i died.

**Comment by DaveyBiggers** [comment]
I've also seen similar things in vanilla minecraft, but never as reliably reproducible as this.
I think I've found the issue though - we were calling some server-side code from a netty server thread, rather than from the actual server thread. This was then loading chunks, and, I guess, ownership of the chunks was ending up on the wrong thread, causing mayhem and misery and the urge to listen to Julee Cruise albums. I will check in a fix once it's been thoroughly tested.

**Comment by DaveyBiggers** [comment]
Closed by PR #363
