### ISSUE TITLE
Partial world state objects

### ISSUE THREAD

**Issue by DilipA** [Microsoft/malmo#368]
I'm experiencing an issue where a world state object contains an updated position observation but is missing video frames. As a result of this, the first partial world state object is thrown away upon checking `if world_state.number_of_video_frames_since_last_state < 1`. After that, a second partial world state is provided that has the video frames but contains no updated position information causing my world state checker to deadlock completely while waiting for a position update that has already been sent once and thrown away due to missing information.

Is there any alternative way for doing discrete world state validation? I know a month or so back there was talk of adding extra metadata to the world state object to make this process simpler.

Debug printout:

*** Task 1 says ***
	Updated agent position to (5.5,4.5,0.0) after action movesouth 1  (successfully executes action here)
*********************

*** Task 1 says ***
	Retrieved world state after peeking 0 times...
*********************

*** Task 1 says ***
	Collected frame with agent at position [5.5, 46.0, 4.5, 0.0] (confirms collection of video frames)
*********************

*** Task 1 says ***
	Received rewards and updated replay memory...
*********************

*** Task 1 says ***
	Executed action: movenorth 1* (selects next action for execution)
*********************

*** Task 1 says ***
	Valid state checker: Retrieved world state with missing frames (presumably this world state had updated position information)
*********************

*** Task 1 says ***
	Valid state checker: Current grid observation: (at this point, we've peeked for a new world state and have passed the video frame check that was failed above)
[u'air', u'air', u'diamond_block', u'air', u'air', u'diamond_block', u'air', u'air', u'diamond_block']
*********************

*** Task 1 says ***
	Agent has not yet left last known position (...but we have no new position information to update with...)
	Last known: (5.5,4.5,0.0)
	Observed: (5.5,4.5,0.0)
	Last action taken: movenorth 1
*********************

*** Task 1 says ***
	Valid state checker: Current grid observation: 
[u'air', u'air', u'diamond_block', u'air', u'air', u'diamond_block', u'air', u'air', u'diamond_block']
*********************

*** Task 1 says ***
	Agent has not yet left last known position (...and this continues endlessly...)
	Last known: (5.5,4.5,0.0)
	Observed: (5.5,4.5,0.0)
	Last action taken: movenorth 1
*********************

**Comment by DaveyBiggers** [comment]
Hi Dilip, if you're using `peekWorldState` then nothing should be getting "thrown away" - if the video frames haven't yet arrived, you can just keep peeking until they do. When everything has arrived, calling `getWorldState` will give you the whole lot, and clear the world state ready for the next iteration.

**Comment by DaveyBiggers** [comment]
Just re-read more closely. Are you saying that the frames _never_ arrive for a particular world state? That's possible, if the render speed is too slow, but the frames should always arrive if you wait long enough. What render speeds are you getting? If it's suspiciously low, check your overclocking - remember we saw cases where the overclocked client thread was strangling the render thread.

In general, it's hard to say where the state change will be seen first - in the frame position or the observations. You can't assume one or the other. When your valid state checker says this: "Retrieved world state with missing frames", what do you then do with that world state? How did you decide that the frames were "missing", and not just "on their way"?

I'm afraid we haven't yet added any metadata to make this easier - I think you're referring to #301, which is quite a big job, but should considerably simplify these things. (At least, it will move the complexity from your code into ours...) In the meantime, robust_frames.py in the python samples gives some sort of example of state validation, though I'm not sure it will teach you anything you don't already know... Good luck!

**Comment by DilipA** [comment]
Hi Dave! So I am using `peekWorldState` to collect all world states passed as input to my valid state checker. The issue is _not_ that frames never arrive but simply that position observations and frames come in different (peeked) world state objects and my checker currently expects that all information be present for a state to be considered valid (is this kind of expectation wrong?). 

After checking `world_state.number_of_video_frames_since_last_state < 1` to determine that the video frames are in fact missing from the current peeked world state, the checker simply returns false and the while loop that continually peeks for the next world state continues. The output I pasted above would suggest that when the next world state was peeked and contained video frames, the position information was no longer available for extraction _from that same peeked world state_ and so the state checker returns false waiting for a world state object to come through with both video frames and position information. 

When I get back into the lab, I'll add a print statement to simply dump out the current world state observations to stdout so we can see this more easily (since right now I'm only guessing that the position information was missing the second time around based on the code I have written).

**Comment by DaveyBiggers** [comment]
Ah - what is your observation policy? If it is set to `LATEST_OBSERVATION_ONLY` then each new observation will replace the last one. If it's set to `KEEP_ALL_OBSERVATIONS` then the world state will just accumulate observations until the next call to `getWorldState()`, and the situation you've described should be impossible.

**Comment by DilipA** [comment]
Currently it is set to `LATEST_OBSERVATION_ONLY` but if `KEEP_ALL_OBSERVATIONS` only accumulates until a call to `getWorldState()` then that sounds like the solution and my mistake was using the wrong observation policy.

I'll give it a go and report back.

**Comment by DilipA** [comment]
Alright so after more debugging, I found the problem had to do with how path blocking was getting checked within the world state checker. Effectively, the position maintained by my code was not aligned with the agent's true position in the world resulting in observations that were inconsistent with the position and action taken.

This problem appears to be resolved. Thanks Dave!
