### ISSUE TITLE
Travis builds all failing on OSX

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#369]
Looks like something got updated in OSX and now all python tests SEGFAULT.

**Comment by DaveyBiggers** [comment]
Was the old issue about the non-system Python seg-faulting on OSX (see #45 and #46). Somehow the Travis VM had started to use /usr/local/bin/python instead /usr/bin/python - fixed by supplying PYTHON_EXECUTABLE to CMake in the travis CI script - though would be good to get to the bottom of #45 and #46 eventually!

**Comment by lobachevzky** [comment]
How exactly do you supply `PYTHON_EXECUTABLE` to `cmake`? #475
