### ISSUE TITLE
AgentHost.startMission throws cryptic error when called with invalid 'role'

### ISSUE THREAD

**Issue by katja-hofmann** [Microsoft/malmo#374]
Running on Windows, with python 2.7, Malmo-0.17

When calling `my_agent_host.startMission(my_mission, my_clients, my_mission_record, 1, my_exp_id)` and role 1 does not exist in the mission, the agent host segfaults (on windows: `Access violation reading location 0xFFFFFFFFFFFFFFFF.`). Should provide a more informative error message.

**Comment by DaveyBiggers** [comment]
Platform will now throw a runtime exception with a helpful error message.
