### ISSUE TITLE
Long launching time issue

### ISSUE THREAD

**Issue by inprog** [Microsoft/malmo#381]
I've installed malmo 0.17.0 64bit version on windows 10 successfully with components listed below.
- vs2013.5
- boost 1.60
- cmake 3.7.0
- jdk-8u101-windows-64
- python-2.7.12.amd64
- zlib 128

The question is, every time I start LaunchClient.bat to active minecraft, the execution stucked at prints below,

> > Configuring > 0/1 projects > root project

If lucky, it could go through for a few minutes. If not, I have to break it by Ctrl-C after maybe 30 minutes' waiting and try again.

I traced the batch file and find out that the stucking command is,

> "C:\Program Files\Java\jdk1.8.0_101/bin/java.exe"    " -Dorg.gradle.appname=gradlew" -classpath "D:\software\malmo\Malmo-0.17.0-Windows-64bit\Minecraft\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain setupDecompWorkspace

I'm not a Java player, does it mean that some resources are not localized into my computer? Can I download them somewhere and install them in my harddrive so as not to remote access them every time?

Or it is because I'm not installed it properly?

I've been through with waiting and retrying. Could anybody kindly help me out! 
Thanks alot!

Below is part of the output messages when I'm lucky. 

> Error occurred parsing version!
> ###### 
> 
> ```
>      ForgeGradle 2.0-SNAPSHOT-30739b0
> ```
> 
>   https://github.com/MinecraftForge/ForgeGradle
> ###### 
> 
> ```
>            Powered by MCP 9.10
>          http://modcoderpack.com
>      by: Searge, ProfMobius, Fesh0r,
>      R4wk, ZeuX, IngisKahn, bspkrs
> ```
> ###### 
> 
> Version string 'unspecified' does not match SemVer specification
> You should try SemVer : http://semver.org/
> :deobfCompileDummyTask
> :deobfProvidedDummyTask
> :getVersionJson
> :extractUserdev UP-TO-DATE
> :extractDependencyATs SKIPPED
> :extractMcpData SKIPPED
> :extractMcpMappings SKIPPED
> :genSrgs SKIPPED
> :downloadClient SKIPPED
> :downloadServer SKIPPED
> :splitServerJar SKIPPED
> :mergeJars SKIPPED
> :deobfMcSRG SKIPPED
> :getFernFlower SKIPPED
> :decompileMc SKIPPED
> :fixMcSources SKIPPED
> :applySourcePatches
> :remapMcSources SKIPPED
> :recompileMc SKIPPED
> :extractNatives SKIPPED
> :getAssetIndex UP-TO-DATE
> :getAssets
> Current status: 57/734   7%
> Current status: 132/734   17%
> Current status: 194/734   26%
> Current status: 294/734   40%
> Current status: 357/734   48%
> Current status: 418/734   56%
> Current status: 488/734   66%
> Current status: 523/734   71%
> Current status: 547/734   74%
> Current status: 618/734   84%
> Current status: 696/734   94%
> Current status: 718/734   97%
> :makeStart
> :setupDecompWorkspace
> BUILD SUCCESSFUL
> Total time: 1 mins 52.173 secs
> ......

**Comment by DaveyBiggers** [comment]
Is this still a problem?
I suspect this is some sort of internet connectivity issue - setupDecompWorkspace will download a bunch of stuff, but it shouldn't need to do it more than once.
If it's still a problem, instead of running launchClient.bat, you could run Minecraft directly by typing `gradlew runClient` - though you will lose the ability to pass commandline parameters that way.

Alternatively, if setupDecompWorkspace has run correctly at least once, you could just comment that line out of the bat file.

**Comment by DaveyBiggers** [comment]
Am assuming this is no longer an issue - feel free to reopen if it is.
