### ISSUE TITLE
Yaw in <DrawEntity> not working

### ISSUE THREAD

**Issue by jiajunwu** [Microsoft/malmo#393]
Hi,

Setting yaw and pitch in <DrawEntity> does not lead to any changes in the rendered scene. 

Another possibly related observation is, if I put two entities (say two ''Pig'') close enough, then there seems to be some collision going on and after that the pigs move to the direction specified by ''yaw''.

**Comment by DaveyBiggers** [comment]
I've reproduced this. My piggies are definitely pointing the wrong way.

**Comment by DaveyBiggers** [comment]
Fixed in #508.
