### ISSUE TITLE
Minecraft configuration

### ISSUE THREAD

**Issue by tambetm** [Microsoft/malmo#399]
I would like to change the max FPS option in Minecraft configuration, but when I run Minecraft through Malmo, ~/.minecraft directory is not created (and I'm assuming not used?). Where keeps Minecraft it's configuration when run through Malmo and how could I change it? Thanks!

**Comment by DaveyBiggers** [comment]
It's in your malmo folder - eg inside Malmo/Minecraft/run. There should be an options.txt file in there which contains the configuration.

**Comment by tambetm** [comment]
Thanks, that worked!
