### ISSUE TITLE
tutorial_6.py not working

### ISSUE THREAD

**Issue by avisingh599** [Microsoft/malmo#403]
Hi,

I tried to run `tutorial_6.py`, but I got the following error:

```
Repeat 1 of 150
Error starting mission: Internal error: the XML we generate does not validate: instance document parsing failed
:1:1728 error: attribute 'autoFall' is not declared for element 'DiscreteMovementCommands'
:1:1728 error: attribute 'autoJump' is not declared for element 'DiscreteMovementCommands'
```

I have not changed anything from the xml and python file present in the current version of the repo.

**Comment by DaveyBiggers** [comment]
Check your versions - if you type `python tutorial_6.py --help` you should see something like this:
```
Malmo version: 0.19.0

Allowed options:
  -h [ --help ]         show description of allowed options
  --test                run this as an integration test
```

autoFall and autoJump were added in 0.19.0 - if you see "Malmo version: 0.18.0" then you need to build version 19.
Also check MALMO_XSD_PATH points to the correct version of the schemas (the XSD files have version numbers at the top ).

Hope that helps!

**Comment by avisingh599** [comment]
This is the response:
```
Malmo version: 0.19.0

Allowed options:
  -h [ --help ]         show description of allowed options
  --test                run this as an integration test


```

**Comment by avisingh599** [comment]
Also, I have built from source (a version that I pulled a few minutes ago).  `MALMO_XSD_PATH` is set correctly as well.

**Comment by DaveyBiggers** [comment]
Odd. We've had similar issues in the past (#201, #319) which usually turn out to be a mismatch somewhere between builds. Has this previously been working? Try doing a git pull and rebuilding again. For what it's worth, I've just tried this (updating and rebuilding) on an old copy of 0.18.0, and it updated and ran correctly, so master _should_ be fine...

Afraid I can't look into this anymore now as I'm about to go on holiday, but hopefully someone else will be able to shed some light if rebuilding doesn't do the trick.

(You may need to try _aggressive_ rebuilding if just doing `make install` doesn't cut it...)

**Comment by avisingh599** [comment]
Working now! I forgot to source the bashrc file after I rebuilt, thanks a
lot for your help!
