### ISSUE TITLE
Entering the Mission using a seperate minecraft client

### ISSUE THREAD

**Issue by MadcowD** [Microsoft/malmo#408]
Is it possible to enter an ongoing mission using a seperate minecraft client, for observationi?

**Comment by DaveyBiggers** [comment]
Yes, and we do this fairly frequently - but at the moment you will need two valid Minecraft logins (this is something we are actively trying to improve).

Here's the simplest way to get what you are after:
1. Make sure you have entered your login details in the Minecraft Mod UI - from within Minecraft, find the Mods menu, select Malmo, go to Logins, and enter your credentials.
2. Fire up two Minecrafts. (NB: if you are using LaunchClient.sh/bat, you might want to make a separate copy of the entire Minecraft folder, and run each copy from its own folder - this prevents gradle from fighting over the files.)
3. Start your mission
4. With the mission running, hit escape to bring up the Minecraft game menu, and select "Open to LAN". (You can choose how to open the world - in spectator mode, creative mode etc. Spectator mode will let your observer fly through walls etc; creative mode will let him interact with the AI agent.)
5. In the other Minecraft instance, select Multiplayer and choose the LAN World that you created in step 4.

This approach should also work across different machines (provided they are on the same LAN). You just need to make sure the two Minecraft instances have valid (different) login credentials.

The other way of doing this is by using a multi-agent mission - you can specify in your mission XML that you want two agents in the mission, and Malmo will take care of opening to LAN and joining the server for you. Take a look at MultiMaze.py and two_diggers.py for examples of this. (MultiMaze requires two python processes, one for each agent'; two_diggers does it all in one process.) In your case, your second agent wouldn't need to do anything - you'd just manually take control of it. (Hit Return in Minecraft to toggle between AI control and human control). Doing it this way also gives you the option of positioning your observer correctly (using the first approach, Minecraft will just spawn you at the default spawn point, which might be miles from the action), and allows you to record the observer's frames too.

Let us know if you have any problems getting this to work.

**Comment by MadcowD** [comment]
Thank you much!
