### ISSUE TITLE
Libboost library not loaded 

### ISSUE THREAD

**Issue by Brigadirk** [Microsoft/malmo#415]
Hey all,

I get the following error-message:

  File "tutorial_1.py", line 22, in <module>
    import MalmoPython
ImportError: dlopen(/Users/Dirk/Downloads/Malmo/Python_Examples/MalmoPython.so, 2): Library not loaded: /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
  Referenced from: /Users/Dirk/Downloads/Malmo/Python_Examples/MalmoPython.so
  Reason: image not found

when I try to run tutorial_1.py

I have boost-1.62.0 & MalmoPython.so is present in the Python_examples folder. 

Anyone have any clues what is going on here?

**Comment by DaveyBiggers** [comment]
Sorry you are having trouble. Obvious question first - does `/usr/local/opt/boost-python/lib/libboost_python-mt.dylib` exist on your system?

Otherwise, we need some more information - what's your OS? how did you install boost, and what version of python are you using? What do you see in `/usr/local/opt/boost-python/INSTALL_RECEIPT.json` ?

**Comment by Brigadirk** [comment]
It seemed that I had installed boost, but not boost-python. I found it out by following your checks.

Thanks for your help.

**Comment by DaveyBiggers** [comment]
Great, thanks for letting us know.

**Comment by jozhang97** [comment]
Hi 
I'm also having this problem, but the .dylib file exists for me. 
My /usr/local/opt/boost-python/INSTALL_RECEIPT.json contains the following: 
{"homebrew_version":"1.1.5-46-g6648ff1","used_options":[],"unused_options":["--universal","--c++11","--without-python","--with-python3"],"built_as_bottle":true,"poured_from_bottle":true,"installed_as_dependency":false,"installed_on_request":true,"changed_files":["INSTALL_RECEIPT.json","share/doc/boost-python/building.qbk"],"time":1485646778,"source_modified_time":1482412310,"HEAD":null,"stdlib":"libcxx","compiler":"clang","runtime_dependencies":null,"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost-python.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"1.63.0","devel":null,"head":"HEAD","version_scheme":0}}}
