### ISSUE TITLE
How to run multi-agent demo two diggers?

### ISSUE THREAD

**Issue by emailweixu** [Microsoft/malmo#417]
Sorry for the naive question. I am very new to Malmo and Minecraft. I am trying to run the demo with the following steps:
1. at Malmo\Minecraft:
launchClient --port=10000
launchClient --port=10001

2. at Python_Examples:
python two_diggers.py

I did nothing else besides the above commands. The demo fails. The output is:

DEBUG: Sending MissionInit to 127.0.0.1 : 10000                                                          
DEBUG: Looking for client, received reply from 127.0.0.1: MALMOOK                                        
DEBUG: Sending MissionInit to 127.0.0.1 : 10000                                                          
DEBUG: Looking for server, received reply from 127.0.0.1: MALMOERRORMinecraftServerConnection missing!   
DEBUG: Sending MissionInit to 127.0.0.1 : 1000
DEBUG: Looking for server, received reply from 127.0.0.1: MALMONOMISSION
Traceback (most recent call last):
  File "two_diggers.py", line 108, in <module>                                                                   
     agent_host2.startMission( my_mission, client_pool, MalmoPython.MissionRecordSpec(), 1, '' )
RuntimeError: Failed to find the server for this mission - you must start the agent that has role 0 first

**Comment by DaveyBiggers** [comment]
At the moment, multi-agent missions require one valid set of Minecraft login credentials *per* agent. (We're actively trying to improve this, but at least one login will always be required.) Logins need to be purchased from the Minecraft website.

In order for Malmo to log in for you, it needs to have access to your Minecraft usernames/passwords - they can be entered via the Minecraft gui - go to the Minecraft menu, find the Mods menu, select Malmo, and hit the logins button. You can add new logins there. You can also specify the port to map that login to - if you map them to ports 10000 and 10001, then It Should Just Work...

Let us know if you have any problems.

**Comment by emailweixu** [comment]
Why does not single agent mission need login, while the multi agent mission need?

**Comment by DaveyBiggers** [comment]
Good question... At the moment, the way we are opening a world and sharing it online requires the use of Minecraft's authentication, whereas running locally in a standalone world doesn't. But we're working on changing the way we do multi-agent missions, to avoid this need for authentication. Watch this space!

**Comment by DaveyBiggers** [comment]
Substantially reworked this in #429. No longer need authentication, so all you should need to get this to work is to run two Minecraft clients, as you tried initially. Let us know if it doesn't work!
