### ISSUE TITLE
Feature request: provide 32bpp depth values

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#419]
See discussion at #394.
Ideally we'd do this in a way that doesn't break the existing RGBD video provider, so as not to break code that relies on the current implementation. It should be possible to provide a depth-only video producer as an alternative option; some work will need to be done on allowing multiple video frame channels.

**Comment by mihnet** [comment]
(Quick and dirty solution) Is it possible to add to [TimestampedVideoFrame](http://microsoft.github.io/malmo/0.30.0/Documentation/structmalmo_1_1_timestamped_video_frame.html) two more params: distance to zero depth points (in 'blocks') and distance range (or distance to 255-depth (max) points)? Than it'll be easy for user to get ~"real" distance to every point in frames with depth. Well, with 255 gradations only, but this wouldn't break current implementations though. Even for 25 blocks range 255 gradations will give 0.1 block accuracy - enough for approximate map around agent.

**Comment by DaveyBiggers** [comment]
Closed in 0.31.0 - can now get a 32bpp float depth map, scaled according to "real" distances. (So a value of 3.5 means that the pixel is 3.5 blocks away from the player's eyes.)

**Comment by akshay-sharma1995** [comment]
Hey @DaveyBiggers, can you please explain how to get this float depth map from the depth map producer?
I tried using PIL library's Image.frombytes function to read the video frame (with want_depth='true') like this:
`img = Image.frombytes('RGBA', (640,480), bytes(frame.pixels))                                                                                                                                      
`
Though I know RGBA is for the alpha channel, but I can't figure out any way to get a depth image array from frame.pixels.
Doing this gives me depth channel with all integer valued depth values. Can you tell me the whether it is the correct way to get the depth channel, or is there a different way to do it?
