### ISSUE TITLE
Meaning of generatorString in FlatWorldGenerator

### ISSUE THREAD

**Issue by emailweixu** [Microsoft/malmo#430]
Hi, what is the meaning of generatorString. I cannot find any documentation about it.

**Comment by DaveyBiggers** [comment]
It's the format Minecraft uses in its in-game superflat generator - I can never remember the syntax, but there should be plenty of details about it online, and there are a few handy webapps that exist to help generate the strings.

Our XML documentation [here](http://microsoft.github.io/malmo/0.17.0/Schemas/MissionHandlers.html#element_FlatWorldGenerator
) contains a link to one, or there's another one [here](http://chunkbase.com/apps/superflat-generator#3;7,2*3,2;1;village).
