### ISSUE TITLE
build failed while running launchClient.sh

### ISSUE THREAD

**Issue by SeungyounShin** [Microsoft/malmo#433]
I use Ubuntu and I just downloaded the minecraft 
And then just typed "launchClient.sh" in terminal 
I got build failed error and below is the part of error log

`FAILURE: Build failed with an exception.

* Where:
Build file '/home/ssy1001/minecraft/malmo-master/Minecraft/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'Minecraft'.
> version.properties file is missing - this is created automatically by CMake. If you are building from source, make sure you have built the full source tree, not just the Minecraft folder.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.532 secs
`

**Comment by DaveyBiggers** [comment]
Like it says, if you are building Malmo from source then you need to build all of it, not just Minecraft. Build instructions are [here](https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md).
If you don't want to build, then you need to install one of the pre-built releases found [here](https://github.com/Microsoft/malmo/releases).
