### ISSUE TITLE
Launch fails after failed download

### ISSUE THREAD

**Issue by jmenashe** [Microsoft/malmo#435]
I have tried running launchClient.sh on a couple different versions of Ubuntu. In each case the launch fails when attempting to download http://export.mcpbot.bspk.rs/versions.json. Is there a mirror for this file? Could the launch be modified so that it doesn't rely on a single Russian website in order to function? Perhaps some fallback could be provided on GitHub to mitigate issues like this in the future.

**Comment by jmenashe** [comment]
I fixed this for myself by setting up a local web server with a previously cached copy of versions.json, and redirecting my hosts file to the local mirror. Obviously this is a bandaid and not a replacement for an actual fix.

**Comment by tambetm** [comment]
I hit the same issue today. Luckily the file was back before I was able to take any course of action. But I wonder if there is a way to run Malmo without refreshing everything? Would be using `./gradlew setupDevWorkspace` or `./gradlew setupCIWorkspace` make any difference?

**Comment by DaveyBiggers** [comment]
You're not alone in this - looks like there have been some problems with bspkrs' website lately. Forge uses mcpbot.bspk.rs when deobfuscating Minecraft - see here: http://www.minecraftforge.net/forum/index.php?topic=44308.0
That thread implies the ForgeGradle has now been updated to use local versions if the website is down, so hopefully this will no longer affect existing users, though new users are still vulnerable to this issue.

**Comment by DaveyBiggers** [comment]
Am closing this - judging from bspkr's twitter feed (see http://bspk.rs/MC/index.html) there was a Python upgrade which upset things, but all should be back to normal as of the 16th Jan.
