### ISSUE TITLE
Boost symbol not found on MacOS Sierra

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#445]
Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transformprimaryEPKcS4
Boost version installed: 1.63

Hopefully this falls under the work done in #392, and all we need to do is make sure we build our OSX release with STATIC_BOOST=ON.

**Comment by rooa** [comment]
I got the same error when trying to run examples in arbitrary languages.  I also received a warning when trying to install boost with `--with-python` option that said the option doesn't exist.

```
$ brew install boost --with-python
Warning: boost: this formula has no --with-python option so it will be ignored!
...
```
Is there any solutions to this so far? Thanks.

**Comment by ericljiang** [comment]
Building from source worked for me.

https://github.com/Microsoft/malmo/blob/master/doc/build_macosx.md

**Comment by DaveyBiggers** [comment]
I believe this is fixed now - we statically link with boost when we build our release binaries now.
