### ISSUE TITLE
Back to Malmo on fedora 25, with a Python ImportError: libTH.so.

### ISSUE THREAD

**Issue by vthierry** [Microsoft/malmo#450]
Hi Malmo,
    one testimony :) and one help-request

It had been my pleasure to test malmo en redhat/fedoar a few moths ago and then had to switch to other projects, sorry, now back.

To witness :
    - source package compiles entirey well (just to check)
    - binary distribution is sufficient for a normal user like me and
        - C++ example runs well with one patch

    # - Adds to ./MalmoPlatform/Cpp_Examples/CMakeLists.txt
    # 65a66
    #   ${CMAKE_THREAD_LIBS_INIT} # to avoid a link error related to fc fun…nny threads install

     
To ask for help
    - i also need to run Python missions and i fail on

    Traceback (most recent call last):
      File "run_mission.py", line 20, in <module>
        import MalmoPython
    ImportError: libTH.so.0: cannot open shared object file: No such file or directory

(i am a python-dummy :( ) it seems that libTH.so.0 might be related to torch that we do need and that i can not install on my fedora-25 distribution (or may be not) -> any one can help ?

Sincerely.

**Comment by mfuntowicz** [comment]
Hi @vthierry, 

The first thing would be to check if torch library can be found on the system or not : 

`locate libTH`

If nothing appear, Torch is not installed on your system. You'll need to follow the [setup for Torch](http://torch.ch/docs/getting-started.html#_)

Let us know.
Morgan

**Comment by vthierry** [comment]
Hi Morgan,

Thanks for your prompt answer.
- i confirm torch is not installes (e.g. locate libTH return is empty)
- i did try http://torch.ch/docs/getting-started.html but get stucked by:
torch>bash install-deps;
Only Fedora 20-24 are supported for now, aborting.
while :
torch>uname -a
Linux kiti 4.9.3-200.fc25.x86_64 

Now i reinstall Malmo from source https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md and it works the Python_Examples/MalmoPython.so does not ask for torch.

So, fine for me; your feedbak helped me to move in the right direction.

Sincerely

Thierry.

**Comment by mfuntowicz** [comment]
Hi @vthierry,

Glad to hear that I finally worked someway for you.
I'm closing this issue for now, feel free to reopen/create a new one if needed :)

Morgan
