### ISSUE TITLE
ubuntu 15.04, error on display the menu

### ISSUE THREAD

**Issue by redliu312** [Microsoft/malmo#460]
I run the pre-build  released  0.19.0 version malmo on ubuntu 15.04.
The released file I download is "Malmo-0.19.0-Linux-Ubuntu-14.04-64bit_withBoost.zip"

The result is as below:
![minecraft_error](https://cloud.githubusercontent.com/assets/6196351/22520680/482e96a4-e8f0-11e6-985a-4237d76ec348.png)

Any suggestion on how can I find the root cause or how can I solve this?

**Comment by DaveyBiggers** [comment]
Hi @redliu312, sorry you are having problems. Is this still an issue?
A few questions:
Have you installed any other Minecraft mods, texture packs etc?
What version of java are you using?
How much memory do you have?
Are you running on a 64bit machine or 32bit?
What do you see if you type
```
glxinfo | grep version
```
into a terminal?
(If you don't have glxinfo, try typing `sudo apt-get install mesa-utils` first.)

**Comment by DaveyBiggers** [comment]
@redliu312 I'm closing this because we haven't heard anything for a while, but if it's still an issue, please go ahead and re-open.

**Comment by redliu312** [comment]
Hi @DaveyBiggers ,
Apologies for the delay. 
This ubuntu run on a virtualbox as a guest machine.
I made some tests and I confirmed that this issue is caused by the virtualbox 3D acceleration option 
which will cause the openGL fail. I  uncheck this option and the Malmo work greatly.
