### ISSUE TITLE
Missing one space in malmo_lib.psm1

### ISSUE THREAD

**Issue by MinexAutomation** [Microsoft/malmo#468]
Hello! I didn't understand what the "gitter" channel was, but by clicking on "Issues" I see there are 57 of them. I searched for "malmo_lib.psm1" and received no results. So. I hope this is a new issue.

I downloaded 0.20, and followed the "Installing dependencies on Windows (Automated)" instructions. I encountered a PowerShell error:

The string starting:
At E:\Organizations\Microsoft\Malmo\Downloads\Malmo-0.20.0-Windows-64bit\scripts\pslib\malmo_lib.psm1:241 char:74
+         & 'C:\Program Files\7-Zip\7z.exe' x .\temp\mesa.7z -o'.\temp\mesa <<<< ' | Out-Host
is missing the terminator: '.

After adding a space between -o and '.\temp\mesa' on line 241, the script proceeded as expected.

**Comment by katja-hofmann** [comment]
Hi @MinexAutomation 

thank you for reporting this! @37b20bc should fix this. 

Out of curiosity, what version of 7-zip do you have on your setup? And what version of windows is this? Adding a space breaks the script on the machines I've tested (moving the single quotes worked) - so I'm curious when this changed.

**Comment by MinexAutomation** [comment]
Hello Katja,

Thanks for the fix!

I have 7-zip 9.20.

I am running Windows 7 Professional.
