### ISSUE TITLE
Link to manual install is broken in install_windows.md

### ISSUE THREAD

**Issue by okkhoy** [Microsoft/malmo#474]
Links to: https://github.com/Microsoft/malmo/blob/build_ps_fixes/doc/install_windows_manual.md
where as the correct link is: https://github.com/Microsoft/malmo/blob/master/doc/install_windows_manual.md

**Comment by DaveyBiggers** [comment]
Also the link from the manual instructions back to the automated instructions was broken.
Fixed them both - thanks for reporting this.
