### ISSUE TITLE
Fail to build the source on mac

### ISSUE THREAD

**Issue by ChristineTzeng** [Microsoft/malmo#482]
I followed the tutorial(https://github.com/Microsoft/malmo/blob/master/doc/build_macosx.md) to setup  the environment on my mac. However, I got below error message:
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   iostreams
--   program_options
--   python
--   regex
--   system
--   thread
--   atomic
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CSharp (missing: CSHARP_TYPE CSHARP_VERSION CSHARP_COMPILER)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCSharp.cmake:67 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:121 (find_package)

-- Configuring incomplete, errors occurred!

Is there something missing? In that tutorial there's no requirement to install C#

**Comment by carl24k** [comment]
Hi Christine.  Would you please explain how you got around this error?  I am seeing the same.  Thank you!
