### ISSUE TITLE
Build script: missing dependency on Debian 8?

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#483]
Cmake fails to find zlib when running the build script on a fresh Azure Debian 8 VM.

`sudo apt-get install zlib1g-dev` is required to get hold of /usr/include/zlib.h...
but later fails with ` undefined reference to boost::iostreams::zlib_error::check(int)` etc.

**Comment by DaveyBiggers** [comment]
Also on Ubuntu 14 - need
`sudo apt-get install libbz2-dev` in order to compile boost iostreams.

**Comment by DaveyBiggers** [comment]
The build/install docs are gradually rusting as the various open-source tools/dependencies we use get updated... Will use this issue to keep track of the changes required / make notes.

For example, the build powershell script downloads an old version of cmake (3.7.2) which isn't compatible with versions of boost greater than 1.63 (the powershell script downloads and builds boost 1.63.0 by default, so that should work fine, but if you are mixing and matching, you run the risk of wasting hours trying to work out why cmake won't find the boost libraries...)

Our CMakeLists.txt only has `SET Boost_ADDITIONAL_VERSIONS` commands up to 1.63.

The instructions all assume building vith VS2013 - need to know that, if building with VS2017, the cmake generator argument is `-G "Visual Studio 15 2017 Win64"` but the boost b2.exe toolset argument is `toolset=msvc-14.1` - the toolset and vs version numbers are not the same thing - see https://stackoverflow.com/a/42738533 for helpful details.

**Comment by AndKram** [comment]
Updated in recent releases.
