### ISSUE TITLE
Python tutorial files dont open

### ISSUE THREAD

**Issue by EnricoDelPiero** [Microsoft/malmo#501]
Hi, when im trying to open the tutorial files, it gives me error messages such as: 

C:\Users\Sir Henry\Downloads\Installationsdateien\Malmo-0.21.0-Windows-64bit\Python_Examples>tutorial_1.py
  File "C:\Users\Sir Henry\Downloads\Installationsdateien\Malmo-0.21.0-Windows-64bit\Python_Examples\tutorial_1.py", line 35
    print 'ERROR:',e
                 ^
SyntaxError: Missing parentheses in call to 'print'

I havent changed anything in the script, does anybody know how to solve this?
Thank you

**Comment by DaveyBiggers** [comment]
Sounds like you are using Python 3. Malmo is built against 2.7, and the samples are all written in 2.7.

There is an open task about adding Python 3 support, but for now the simplest course of action is to switch to using Python 2.

**Comment by EnricoDelPiero** [comment]
Thanks, you are correct sir!
