### ISSUE TITLE
Agent can't run script in LAN

### ISSUE THREAD

**Issue by SeanViswanathan** [Microsoft/malmo#504]
Client 1: Creates a world instance by running script at the main menu.

I End script after world is created and open it up to LAN.

Client 2: Joins Lan

How can I make client 2 run the same script as client 1 so that they can both be running the script in the same world?

**Comment by SeanViswanathan** [comment]
I want to have multiple agents working in the same world running the same exact script I wrote... basically they are placing blocks on a set of predefined rules. I can't figure out how to properly hook all the agents up to one world and they all run the script.

**Comment by DaveyBiggers** [comment]
What you want is a "multi agent mission". Take a look in the python samples folder - there are several examples here which should give you the general idea.
In short, you want to define an `<AgentSection>` for each agent, create a separate `agentHost` for each agent, and call `startMission` on each one (passing them all the same mission XML but different "role" numbers. Eg with two agents, you'd have "role 0" and "role 1".)
Malmo ensures that whichever agent has role 0 will create the integrated server and open it to the LAN automatically, and then wait for the other agents to join before starting the mission.

The agentHosts don't have to be running in the same process, or even on the same machine - but for convenience most of the samples have them running in the same process. MultiMaze.py is an example of using one python process per agent (there's currently an unrelated issue with MultiMaze - #420 - which means it won't run at present, though the code should still give you an idea of how to go about it.)
multi_agent_test.py is an example of creating and controlling multiple agents from the same thread - one mission loop controls all the agentHosts.
turn_based_test.py was written to demonstrate the turn scheduler, which you are probably not interested in, but also demonstrates how to create multi agent missions where each agent has its own thread.

Am closing this issue but feel free to open a new one if you run into any problems.
