### ISSUE TITLE
Objects labels

### ISSUE THREAD

**Issue by Nicolas99-9** [Microsoft/malmo#506]
Does the API provide a way to automatically label the objects in a frame? (or at least identify the position of the objects in the screen space)

**Comment by okkhoy** [comment]
@Nicolas99-9 I think you can use `ObservationFromRay` to identify the position of object wrt the player.
`ObservationFromRay` returns a JSON string within observation JSON similar to the following:
```
u'LineOfSight': {u'hitType': u'block',
                      u'inRange': True,
                      u'type': u'stone',
                      u'variant': u'stone',
                      u'x': 8.0,
                      u'y': 45.59931137525265,
                      u'z': 1.5},
```

**Comment by Nicolas99-9** [comment]
@okkhoy Does it return all the visible objects ? Is there a documentation ? I haven't found information on http://microsoft.github.io/malmo/0.21.0/Documentation/index.html

**Comment by okkhoy** [comment]
nope not all objects. returns what ever is in the "line of sight" of the player. 
observation from ray has some basic documentation here: http://microsoft.github.io/malmo/0.21.0/Schemas/MissionHandlers.html#element_ObservationFromRay

**Comment by DaveyBiggers** [comment]
We don't currently provide object labeling, though it's something we've had planned for a while - feel free to add a thumbs-up to #66 - the more people ask for it, the more likely it is that we'll make the time to do it.
