### ISSUE TITLE
Multi-Agent Missions Confusion

### ISSUE THREAD

**Issue by SeanViswanathan** [Microsoft/malmo#509]
Link to original post:
https://github.com/Microsoft/malmo/issues/504

I'm still confused on whether follow the steps outlined will allow my agents to run by the main-loop I've defined - indepdent of each other. Does following MultiMaze allow all agents (lets say I use 5) to be running the general script ? (in twodiggers, each agent1 and agent2 need specific commands given to them. I want to avoid that). 

Additionally, is there any reading resources on multi agents that I can find, or for Malmo in general? The tutorial.py isn't in depth for me, and the XML schema documentation is the only other thing I can find. 

Thanks!

**Comment by DaveyBiggers** [comment]
The python samples are your best reading resource. Take a look at multi_agent_test.py - it basically does what you are describing: there is one main loop (starts around line 314) which contains all the logic for controlling the agents, and it's applied to each agentHost in turn:
```
for i in xrange(NUM_AGENTS):
            ah = agent_hosts[i]
```
So yes, you can use the same code for each agent, you just need to run it on each agent. You can do this in the way multi_agent_test.py does it, looping through each agent in turn, or you can create a separate thread for each agent, or you can run the entire script separately once for each agent... it's entirely up to you how you do it, and all these methods are demonstrated in the samples. Does that help at all?

**Comment by DaveyBiggers** [comment]
Am closing this issue now - feel free to ask around on the gitter page for more help (https://gitter.im/Microsoft/malmo), or open another issue here if you have any more specific questions.
