### ISSUE TITLE
Problems with multiagent missions

### ISSUE THREAD

**Issue by luarsu** [Microsoft/malmo#514]
Hi everyone,

This might be a very dumb question but I've been trying to start some of the multiagent examples from the python examples (two_diggers, multiagent test) and I've had several problems. The only multiagent example I could try it's the MultiMaze, in which first I run the  agent 0 and then I run the other agents.

However, with two_diggers I start two different clients and when I tried to test it I have some errors like:
- It says that there are not enough clients available, even if I have two different clients opened in different ports
-It says that I must initialize the agent 0 first and then it stops, but there is no option to initialize agent 0 first

I just initialize the two diggers as any other example:
python two_diggers.py

I tried several times and once the two diggers started running in both clients, but after the first 10 seconds it gave me an error and stopped, telling me that the connection was lost.
I'm doing an important university project using Malmo and I'd like to to use several agents for it, but I can't start until I figure it out how the examples work, so any help would be appreciated. Maybe I'm initializing the examples wrong, or maybe it's an error from Malmo, but I dont really know.

Thanks in advance!

**Comment by DaveyBiggers** [comment]
A few things to try:
In your Minecraft clients, find the Malmo mod options screen (from the title menu click on "Mods" then select "Microsoft Malmo Mod" in the list on the left hand side, and click "Config". Or, from within a game, his escape and select "Mod Options...").
Then change the value of "debugDisplayLevel" until it says "Show all diagnostics".
The most useful thing this will do is show you the Mod's state at the top-left of the screen.
Before trying to start the mission, you want it to show:
SERVER: DORMANT
CLIENT: DORMANT
(Don't worry if there is no server - as long as everything is listed as being dormant).

Sometimes, with multi-agent missions, the Mod state machines get a little stuck - we're slowly ironing out these issues, but occasionally, if something goes wrong, it doesn't always back it back to the dormant state. Unless the mod is in the dormant state, it won't accept new missions - this will result in the "not enough clients available" message.

The "you must start agent 0 first" message means that the second agent is trying to connect to a Minecraft server that isn't up and running yet. It's the responsibility of agent 0 to start this server, hence "you must start agent 0 first".
On slower machines, it can take a while for the server to get up and running. In two_diggers.py, there's no particularly sophisticated attempt to deal with this case; it simply starts agent 0, waits ten seconds, and then starts agent 1. (Other samples do error checking and try a bit harder!)
Try increasing the value in the `time.sleep(10)` lines and see if this makes the sample more reliable for you.

As for stopping after the first 10 seconds, I suspect this was the same problem - two_diggers runs two sets of missions, and the first mission is 10 seconds long.

Let us know if this helps.

**Comment by DaveyBiggers** [comment]
@luarsu am closing this now, assuming you are up and running - please feel free to reopen if you need any further clarification on this issue. Cheers.

**Comment by luarsu** [comment]
Yeah, the problem is solved, thank you ver much :3
