### ISSUE TITLE
Why is not working Discrete/AbsoluteMovementCommands but it does ContinuousMovementCommands

### ISSUE THREAD

**Issue by DGMonkeyKing** [Microsoft/malmo#515]
I don't know what i am doing wrong:
This works:
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Mission xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <About>
        <Summary>Hello world!</Summary>
    </About>

    <ServerSection>
        <ServerInitialConditions>
            <Time>
                <StartTime>1000</StartTime>
                <AllowPassageOfTime>false</AllowPassageOfTime>
            </Time>
            <Weather>clear</Weather>
        </ServerInitialConditions>

        <ServerHandlers>
            <FlatWorldGenerator generatorString="3;7,220*1,5*3,2;3;,biome_1" />
            <DrawingDecorator>
                <DrawCuboid x1="0" y1="227" z1="0" x2="''' + str(xTop) + '''"
                    y2="227" z2="''' + str(zTop) + '''" type="air" />   
                <DrawCuboid x1="0" y1="227" z1="0" x2="''' + str(xTop) + '''"
                    y2="227" z2="''' + str(zTop) + '''" type="obsidian" />
                <DrawCuboid x1="0" y1="227" z1="0" x2="0" y2="237"
                    z2="''' + str(zTop) + '''" type="glass" />
                <DrawCuboid x1="0" y1="227" z1="0" x2="''' + str(xTop) + '''"
                    y2="237" z2="0" type="glass" />
                <DrawCuboid x1="''' + str(xTop) + '''" y1="227" z1="''' + str(zTop) + '''"
                    x2="''' + str(xTop) + '''" y2="237" z2="0" type="glass" />
                <DrawCuboid x1="''' + str(xTop) + '''" y1="227" z1="''' + str(zTop) + '''"
                    x2="0" y2="237" z2="''' + str(zTop) + '''" type="glass" />
                <DrawCuboid x1="23" y1="226" z1="22" x2="26" y2="236" z2="26"
                    type="lapis_block" />
                <DrawCuboid x1="23" y1="227" z1="22" x2="26" y2="227" z2="26"
                    type="red_flower" variant="blue_orchid" /> 
                ''' + drawItems() + '''
            </DrawingDecorator>
            <ServerQuitWhenAnyAgentFinishes />
        </ServerHandlers>
    </ServerSection>

    <AgentSection mode="Survival">
        <Name>MalmoTutorialBot</Name>
        <AgentStart>
            <Placement x="22" y="228.0" z="23" pitch="30" yaw="0" />
            <Inventory>
                <InventoryItem slot="8" type="diamond_pickaxe" />
            </Inventory>
        </AgentStart>
        <AgentHandlers>
            <ContinuousMovementCommands/>
            <ObservationFromFullStats />
            <ObservationFromGrid>
                <Grid name="floor3x3">
                    <min x="-1" y="-1" z="-1" />
                    <max x="1" y="-1" z="1" />
                </Grid>
            </ObservationFromGrid>
            <InventoryCommands />
            <AgentQuitFromTouchingBlockType>
                <Block type="diamond_block" />
            </AgentQuitFromTouchingBlockType>
        </AgentHandlers>
    </AgentSection>
</Mission>

This does not:
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Mission xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <About>
        <Summary>Hello world!</Summary>
    </About>

    <ServerSection>
        <ServerInitialConditions>
            <Time>
                <StartTime>1000</StartTime>
                <AllowPassageOfTime>false</AllowPassageOfTime>
            </Time>
            <Weather>clear</Weather>
        </ServerInitialConditions>

        <ServerHandlers>
            <FlatWorldGenerator generatorString="3;7,220*1,5*3,2;3;,biome_1" />
            <DrawingDecorator>
                <DrawCuboid x1="0" y1="227" z1="0" x2="''' + str(xTop) + '''"
                    y2="227" z2="''' + str(zTop) + '''" type="air" />   
                <DrawCuboid x1="0" y1="227" z1="0" x2="''' + str(xTop) + '''"
                    y2="227" z2="''' + str(zTop) + '''" type="obsidian" />
                <DrawCuboid x1="0" y1="227" z1="0" x2="0" y2="237"
                    z2="''' + str(zTop) + '''" type="glass" />
                <DrawCuboid x1="0" y1="227" z1="0" x2="''' + str(xTop) + '''"
                    y2="237" z2="0" type="glass" />
                <DrawCuboid x1="''' + str(xTop) + '''" y1="227" z1="''' + str(zTop) + '''"
                    x2="''' + str(xTop) + '''" y2="237" z2="0" type="glass" />
                <DrawCuboid x1="''' + str(xTop) + '''" y1="227" z1="''' + str(zTop) + '''"
                    x2="0" y2="237" z2="''' + str(zTop) + '''" type="glass" />
                <DrawCuboid x1="23" y1="226" z1="22" x2="26" y2="236" z2="26"
                    type="lapis_block" />
                <DrawCuboid x1="23" y1="227" z1="22" x2="26" y2="227" z2="26"
                    type="red_flower" variant="blue_orchid" /> 
                ''' + drawItems() + '''
            </DrawingDecorator>
            <ServerQuitWhenAnyAgentFinishes />
        </ServerHandlers>
    </ServerSection>

    <AgentSection mode="Survival">
        <Name>MalmoTutorialBot</Name>
        <AgentStart>
            <Placement x="22" y="228.0" z="23" pitch="30" yaw="0" />
            <Inventory>
                <InventoryItem slot="8" type="diamond_pickaxe" />
            </Inventory>
        </AgentStart>
        <AgentHandlers>
            <DiscreteMovementCommands/>     <-----This changes
            <ObservationFromFullStats />
            <ObservationFromGrid>
                <Grid name="floor3x3">
                    <min x="-1" y="-1" z="-1" />
                    <max x="1" y="-1" z="1" />
                </Grid>
            </ObservationFromGrid>
            <InventoryCommands />
            <AgentQuitFromTouchingBlockType>
                <Block type="diamond_block" />
            </AgentQuitFromTouchingBlockType>
        </AgentHandlers>
    </AgentSection>
</Mission>

Mayhap it is need to put something before that? Some kind of configuration?

PD: The commands that works on Continuous are "move" and "strafe". On Discrete no thing works.

**Comment by DaveyBiggers** [comment]
What exactly have you tried?
Discrete and continuous commands work differently.
Eg, in continuous mode, "move 1" means "start moving forward at max velocity".
In discrete mode, "move 1" means "move one block forward and stop".

**Comment by DGMonkeyKing** [comment]
Discrete Movement does nothing actually, regardless the command. Thats the problem.
When i execute sendCommand("move 1"), un Continuous mode it does what you said, but the same command in discrete does no thing. That's why i ve started to think that I am missing something I can't figure out. Thanks.

**Comment by DaveyBiggers** [comment]
Ouch! Thank you for reporting this - I think this is a regression we introduced recently.
The root cause of the problem is that the agent needs to be in the _centre_ of the block - eg change your placement to:
```        <Placement x="22.5" y="228.0" z="23.5" pitch="30" yaw="0" />```

The code which moves the agent tries to keep it in the centre of the block, but it assumes that the agent _started_ in the centre; recent code changes don't deal well with cases where this is not true!

**Comment by DGMonkeyKing** [comment]
Ok, that was the problem, now is working perfectly. A lot of thanks! :thumbsup::thumbsup::thumbsup:
