### ISSUE TITLE
StartMission problem performance

### ISSUE THREAD

**Issue by Nicolas99-9** [Microsoft/malmo#517]
I have a problem with startMission, I'm using the eating_1.xml mission. 
Each time I reset the environment, I'm calling the  startMission function. My inventory is cleared but the items (the food) are not erased so after a few iteration the map is fulled by thousands of fruits. I could use forceWorldReset() but it's very slow. 

I tried to draw "air" before drawing the items : 

`<DrawCuboid x1="-52" y1="227" z1="-50" x2="50" y2="227" z2="50" type="air" />
                    <DrawCuboid x1="-50" y1="226" z1="-50" x2="50" y2="226" z2="50" type="carpet"  colour="RED" face="UP"/>`

**Comment by DaveyBiggers** [comment]
Try changing y1 to "226" - for some reason (I guess because of the carpet), the items won't get cleared unless you fill from 226 to 227.
