### ISSUE TITLE
agent.getWorldState().observations fails sometimes. Any potentials causes?

### ISSUE THREAD

**Issue by afkim11** [Microsoft/malmo#524]
Hello, 
I'm experiencing some issues with the command agent.getWorldState().observations. Sometimes, I can't assure in what conditions, it doesn't return the information about the agent and it causes a beautiful index out of range when I try to access with agent.getWorldState().observations[-1] to parse it. Currently, I have 2 agents and let's say 1of 4 times I try to get the observations it doesn't return the observations and causes a disaster in my execution(For example, the agent doesn't go where I wanted to send him). Is there any potential reason why this is happening? I have a hypothesis that it happens when I try to get the observations while the agent is moving(when I say 'moving' I mean executing discrete commands like movenorth,movewest, etc...) Could this be the cause of the issue?

Thank you very much and congratulations for this project, it's awesome.

**Comment by mfuntowicz** [comment]
Hi @afkim11,

On the AgentHost, you have a property that helps you deal with this situation:

```python
latest_ws = agent_host.peekWorldState()
        if latest_ws.number_of_observations_since_last_state > 0:
            world_obs = json.loads(latest_ws.observations[-1].text)
```

Hope it helps :), 
Morgan

**Comment by afkim11** [comment]
First, thank you for replying! Could you explain me what is the main difference between getWorldState or PeekWorldState? Is there any difference?.
The one thing I have different from your code is checking **number_of_observations_since_last_state**. If there are no new observations since the last state and I try to get the observations will it cause the error I'm getting?.
The thing is that I just use the observations to get the coordinates of the agent and to get his name, is there an alternative to obtain this information?.
Thanks for everything.

**Comment by mfuntowicz** [comment]
You're welcome, 

peekWorldState doesn't consume the internal buffer (data remains available inside the socket) where getWorldState will consume the internal buffer (data flushed from the socket).

Basically, you use peekWorldState() to check everything you need is present (like number_of_observations_since_last_state > 0) and when you the criteria are present you can safely call getWorldState() to flush everything inside the pipe (reseting number_of_observations_since_last_state).

**Comment by afkim11** [comment]
Hi there again!
I have changed all my getWorldState() for peekWorldState() and everything is working as I want it to. 
Thank you very much for this, you've saved me! 👍 :D
