### ISSUE TITLE
Detect enemies on the map

### ISSUE THREAD

**Issue by davidastur94** [Microsoft/malmo#525]
i try to detect enemies using:

<ObservationFromGrid>
<Grid name="floor3x3">
<min x="-1" y="-1" z="-1"/>
<max x="1" y="-1" z="1"/>
</Grid>
</ObservationFromGrid>

but it seems only work with materials like "stained_glass" or "stained_hardened_clay", is there any way to detect a zombie or a creeper?

**Comment by davidastur94** [comment]
the code i mentioned:
ObservationFromGrid
Grid name="floor3x3x2"
min x="-1" y="-1" z="-1"
max x="1" y="1" z="1"
Grid
ObservationFromGrid

**Comment by DaveyBiggers** [comment]
Yes, `ObservationFromGrid` only tells you the blocks around you.
You want `ObservationFromNearbyEntities`. See, for example, mob_fun.py in the python samples. Let us know if you have any problems.
