### ISSUE TITLE
Feature request: get health of entities 

### ISSUE THREAD

**Issue by asontha** [Microsoft/malmo#531]
Is it possible to get the health of entities other than yourself when using ObservationFromNearbyEntities? We want to know when we've applied damage to nearby entities so that we could create something that hunts.

**Comment by DaveyBiggers** [comment]
It's not currently possible, but I've turned this into a feature request. Hopefully we'll manage to add this soon.

**Comment by StStevens** [comment]
It should be possible now!

https://github.com/Microsoft/malmo/pull/536
