### ISSUE TITLE
Question: Can agents turn/incline certain angles?

### ISSUE THREAD

**Issue by Yarichi** [Microsoft/malmo#532]
Hi! I was wondering if its possible for an agent in Malmo to turn 90 degres to left or righ, or even incline the head to look to the cube on the floor and things like that.

Thanks in advance!.

**Comment by DaveyBiggers** [comment]
Yes, take a look at the discrete movement commands. In addition to "move" and "strafe" there is also "turn" and "look". `discrete_3d_test.py` contains an example of the turn commands in action.
