### ISSUE TITLE
Java AgentHost.sendCommands method strange behavior

### ISSUE THREAD

**Issue by wandergibaut** [Microsoft/malmo#534]
Hi guys!
I'm using Malmo as Environment on my Master's research on Cognitive Architectures and I am coding in Java with the Netbeans IDE. As the the example program works perfectly, I've started just copying the code to make posterior changes.
In my program (as probably everyones) I get the Observations, do some processing and them send commands back to Malmo. And there is the problem: although the link works fine for things like "getObservations()", when I use the method "sendCommand(String)" it simples do nothing. Not even an error message is fired, nothing! 
I'm desperately trying to figure it out and may use some help :D
thanks! 

edit:
the commands.txt file generate indicates only one "move 1" command (that the agent didn't follow).

**Comment by DaveyBiggers** [comment]
Without seeing your code it's difficult to know what the problem might be. What command handlers are you using? What exactly are you seeing?

**Comment by wandergibaut** [comment]
the problematic code is bellow (It looks like a Frankstein's monster by now). 
Essentially I broke the original code in parts:
- createAndSetupAgent method
- Mission1 class (creates the missionSpecs, uses a xml as starting point)
- the "main" part
Some classes and methods are irrelevant and can be  comment (and in fact it was comment for debbuging). I noticed that despite being able to get the Observations, the original program was unable to send commands to Minecraft. So I looking for the point exactly where the problem arrises.

`public Environment(String argv[]){
       //this.mind = new AgentMind();
       //this.argv = argv;
       createAndSetupAgent(argv);
       createAndSetMOsAndCodelets(agent_host);
       world_state = agent_host.getWorldState();
       
    }

    public WorldState getWorldState(){
        return world_state;
    }
    
    public void startMission(Mission1 mission){
       //createAndSetupAgent(argv);
       //createAndSetMOsAndCodelets(agent_host);
       //world_state = agent_host.getWorldState();
        try{
            agent_host.startMission(mission.getMission(), mission.getMissionRecord());
            //agent_host.sendCommand("move 1");
        }
        catch(Exception e){
            System.out.println("Error starting mission: " + e.getMessage());
            System.exit(1);
        }
        
        WorldState world_state;// = env.getWorldState();
        
        System.out.print("Waiting for the mission to start");
        
        do{
            System.out.print(".");
            try{
                Thread.sleep(100);
            }
            catch(Exception eX){
                System.out.println("User interrupted while waiting for mission to start.");
                return;
            }
            world_state = agent_host.getWorldState();
            for(int i = 0;i < world_state.getErrors().size(); i++){
                System.out.println("Error: " + world_state.getErrors().get(i).getText());
            }
        }while(!world_state.getIsMissionRunning());
        System.out.println("");
        
        //Main loop
        do{
            System.out.println("system is running");
            agent_host.sendCommand( "move 1" );
            agent_host.sendCommand("turn " + 1);
            agent_host.sendCommand("attack 1");
            //mind.start();
            
           //
            try{
                Thread.sleep(500);
            }
            catch(InterruptedException ex){
                System.out.println("User interrupted while mission was running.");
                return;
            }
            world_state = agent_host.getWorldState();
            System.out.print("video, observation, rewards received: ");
            System.out.print(world_state.getNumberOfVideoFramesSinceLastState() + ", ");
            System.out.print(world_state.getNumberOfObservationsSinceLastState());
            System.out.println(world_state.getNumberOfRewardsSinceLastState());
            
            for(int i = 0;i < world_state.getRewards().size(); i++){
                TimestampedReward reward = world_state.getRewards().get(i);
                System.out.println("Summed reward: " + reward.getValue());
            }
            for(int i = 0;i < world_state.getErrors().size(); i++){
                TimestampedString error = world_state.getErrors().get(i);
                System.out.println("Error: " + error.getText());
            }
        }while(world_state.getIsMissionRunning());
    }
    
    public void createAndSetupAgent(String[] argv){
        //inicializa o agent_host
        agent_host = new AgentHost();
        try{
            StringVector args = new StringVector();
            args.add("MalmoAppWand");
            for(String arg : argv)
                args.add(arg);
            agent_host.parse(args);
            System.out.println("checando se tah tudo ok");
        }
        catch(Exception e){
            System.out.println("ERROR: " + e.getMessage());
            System.out.println(agent_host.getUsage());
            System.exit(1);
        }
        if(agent_host.receivedArgument("help")){
            System.out.println(agent_host.getUsage());
            System.exit(0);
        }
    }`

**Comment by wandergibaut** [comment]
'XML:
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Mission xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <About>
    <Summary>WS3DApp Malmo version 0.5.</Summary>
  </About>

  <ServerSection>
    <ServerInitialConditions>
        <Time>
		<StartTime>1</StartTime>
		<AllowPassageOfTime>false</AllowPassageOfTime>
	</Time>	
	<Weather>rain</Weather>
    </ServerInitialConditions>
    <ServerHandlers>
      <FlatWorldGenerator generatorString="3;7,220*1,5*3,2;3;,biome_1"/>
      <ServerQuitFromTimeUp timeLimitMs="20000"/>
      <ServerQuitWhenAnyAgentFinishes/>
    </ServerHandlers>
  </ServerSection>

  <AgentSection mode="Survival">
    <Name>Arthur Abdel Simpson</Name>
    <AgentStart>
      <Placement x="0" y="227" z="0" pitch="15" yaw="90"/>
    </AgentStart>
    <AgentHandlers>
	<ObservationFromFullStats/>
	<ObservationFromRay/>
	<ObservationFromGrid>
		<Grid name ="floor3x3">
			<min x="-1" y="-1" z="-1"/>
			<max x="1" y="-1" z="1"/>
		</Grid>
	</ObservationFromGrid>
      <RewardForCollectingItem>
        <Item reward="1" type="apple"/>
        <Item reward="50" type="emerald"/>
      </RewardForCollectingItem>
      <RewardForSendingCommand reward="-1" />
    </AgentHandlers>
  </AgentSection>
  
</Mission>`

**Comment by wandergibaut** [comment]
XML:
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Mission xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <About>
    <Summary>WS3DApp Malmo version 0.5.</Summary>
  </About>

  <ServerSection>
    <ServerInitialConditions>
        <Time>
		<StartTime>1</StartTime>
		<AllowPassageOfTime>false</AllowPassageOfTime>
	</Time>	
	<Weather>rain</Weather>
    </ServerInitialConditions>
    <ServerHandlers>
      <FlatWorldGenerator generatorString="3;7,220*1,5*3,2;3;,biome_1"/>
      <ServerQuitFromTimeUp timeLimitMs="20000"/>
      <ServerQuitWhenAnyAgentFinishes/>
    </ServerHandlers>
  </ServerSection>

  <AgentSection mode="Survival">
    <Name>Arthur Abdel Simpson</Name>
    <AgentStart>
      <Placement x="0" y="227" z="0" pitch="15" yaw="90"/>
    </AgentStart>
    <AgentHandlers>
	<ObservationFromFullStats/>
	<ObservationFromRay/>
	<ObservationFromGrid>
		<Grid name ="floor3x3">
			<min x="-1" y="-1" z="-1"/>
			<max x="1" y="-1" z="1"/>
		</Grid>
	</ObservationFromGrid>
      <RewardForCollectingItem>
        <Item reward="1" type="apple"/>
        <Item reward="50" type="emerald"/>
      </RewardForCollectingItem>
      <RewardForSendingCommand reward="-1" />
    </AgentHandlers>
  </AgentSection>
  
</Mission>

**Comment by wandergibaut** [comment]
about the XML:

ServerHandlers
      <FlatWorldGenerator generatorString="3;7,220*1,5*3,2;3;,biome_1"/>

AgentHandlers
	<ObservationFromFullStats/>
	<ObservationFromRay/>
	<ObservationFromGrid>
		<Grid name ="floor3x3">
			<min x="-1" y="-1" z="-1"/>
			<max x="1" y="-1" z="1"/>
		</Grid>
	</ObservationFromGrid>
      <RewardForCollectingItem>
        <Item reward="1" type="apple"/>
        <Item reward="50" type="emerald"/>
      </RewardForCollectingItem>
      <RewardForSendingCommand reward="-1" />
    </AgentHandlers>

**Comment by wandergibaut** [comment]
Forget it, I just figured it out!

i forgot the 'DiscreteMovementCommands' Handler on the XML file. :X
I Assumed that there were a default construction and unless I specified something, this default would be used.

again, thanks for the answer!
:smile:
