### ISSUE TITLE
Launch Minecraft Server Without GUI

### ISSUE THREAD

**Issue by afkim11** [Microsoft/malmo#535]
Hi,
I want to launch a multi-agent program(>3 agents) and I have a Hardware limitation when I try to open more than 3 Minecraft instances (My RAM, 16GB, is not good enough for 4 Minecraft) so I thought that I could open more minecraft instances if I open N-1 instances without GUI(without graphics, just as a server in the terminal) and 1 instance as a "Observer Agent" in the sky watching everything. 
The question is, is it possible to launch minecraft without GUI? is there any way to do something like "launchMinecraft.bat --nogui" ?
Thank you very much.

**Comment by tambetm** [comment]
I've had previously success with xvfb. For example:
```
xvfb-run -a -e /dev/stdout -s '-screen 0 1400x900x24' ./launchClient.sh
```
But I doubt you win that much. You could try to lower resolution instead.

**Comment by afkim11** [comment]
Thank you very much for your answer and sorry for answering you now, 5 days later. 

I think that might work on Linux but I need to run Minecraft and my agents program on Windows, so I would need a way to run minecraft without GUI. Anyway thank you a lot :)

Would there be any way(modifying any gradle tool or any other way) to run on Windows Minecraft without GUI?

**Comment by DaveyBiggers** [comment]
There's no way that we know of to do this on Windows, and, as @tambetm points out, I'm not sure it would save you much memory anyway. If you have access to more than one machine, you could run some of your Minecraft instances there? As long as you put the correct IP address in your ClientPool, Minecraft doesn't have to be run locally.
