### ISSUE TITLE
EC parameter error when run ./launchClient.sh

### ISSUE THREAD

**Issue by gliese581gg** [Microsoft/malmo#538]
I got 'EC parameter error' when I run the ./launchClient.sh

I'm using ubuntu 14.04 and I installed all dependencies as described in section 1 of 

'https://github.com/Microsoft/malmo/blob/master/doc/install_linux.md'.

The problem was solved after I installed openjdk-8-jdk instead of openjdk-7-jdk as follows

sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
sudo update-alternatives --config java
sudo update-alternatives --config javac

(from https://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts)

I'm posting this because someone might get same error:)

**Comment by DaveyBiggers** [comment]
Thanks for this @gliese581gg!
I've re-opened this as a reminder to myself to fix up our integrated build process, which is suffering the same problem.
