### ISSUE TITLE
Pre-built release 0.22.0 for Ubuntu 14.04 

### ISSUE THREAD

**Issue by jiajunwu** [Microsoft/malmo#546]
Current release 0.22.0 is only for Ubuntu 16.04. Would we have a pre-built version for 14.04 as well? Thanks!

**Comment by DaveyBiggers** [comment]
It should go up today, along with the other builds (OSX, Debian etc).
I'll close this issue when it's up.

**Comment by DaveyBiggers** [comment]
Brief update: #547 has disrupted our plans to build the Ubuntu 16.04 binaries... Will hopefully have a workaround soon.

**Comment by DaveyBiggers** [comment]
Ended up skipping this and moving to 0.30.0 - Ubuntu builds are up.
