### ISSUE TITLE
python skripts won't run (ImportError: DLL load failed: The specified module could not be found.)

### ISSUE THREAD

**Issue by EnricoDelPiero** [Microsoft/malmo#548]
I know this issue came up earlier, but all the recommended steps didn't help.
- The correct python version 2.7.11 in 64 bit is installed
- codesynthesis 4.0 is installed and added to path 

But still i see the error message
D:\Malmo\Builds\Malmo-0.22.0-Windows-64bit\Malmo-0.22.0-Windows-64bit\Python_Examples>python tutorial_1.py
Traceback (most recent call last):
  File "tutorial_1.py", line 22, in <module>
    import MalmoPython
ImportError: DLL load failed: The specified module could not be found.

Any ideas why this might still be an issue?
Best, 
Henry

**Comment by DaveyBiggers** [comment]
Have you installed the Microsoft VS2013 redistributable? eg step 6 here:
https://github.com/Microsoft/malmo/blob/master/doc/install_windows_manual.md

If that doesn't work, try running the C++ or C# samples - they sometimes give more helpful error messages than Python, and will usually tell you _what_ is missing, rather than just complaining that _something_ is missing...

**Comment by EnricoDelPiero** [comment]
I have deinstalled and reinstalled all the dependencies (several times now) and added their locations to the path variable. 

When I’m trying to launch a java agent I get: A JNI error has occurred, please check your installation and try again. 

Cpp is telling me: MSVCR120.dll is missing.

Csharp:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Research.Malmo.MalmoNETNativePINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'MalmoNETNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_MalmoNETNative(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.SWIGExceptionHelper..ctor()
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Research.Malmo.MalmoNETNativePINVOKE.new_AgentHost()
   at Program.Main()

Thank you for your help!

**Comment by EnricoDelPiero** [comment]
One more thing. the link in step 6 of the list doesnt work, so i downloaded it from another website...

**Comment by DaveyBiggers** [comment]
Hmm, that broken link is annoying.
If MSVCR120.dll is missing then your attempt to install the VS2013 redist must have failed.
Try here?
https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

**Comment by EnricoDelPiero** [comment]
Thank you very much sir, the initial error message disappeared... But now I see this:

C:\Users\Heinrich Peters\Desktop\Malmo\Builds\Malmo-0.22.0-Windows-64bit\Malmo-0.22.0-Windows-64bit\Python_Examples>python tutorial_1.py
Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.

C:\Users\Heinrich Peters\Desktop\Malmo\Builds\Malmo-0.22.0-Windows-64bit\Malmo-0.22.0-Windows-64bit\Python_Examples>python run_mission.py
Error starting mission: FFMPEG not available

do you have an idea whats still wrong?

**Comment by DaveyBiggers** [comment]
Really glad that worked!
Am closing this issue since the original problem is now solved, but feel free to open additional issues for new problems. (But as for the FFMPEG issue, my guess is that you've not installed FFMPEG. Please see the installation instructions. And the other error indicates that you don't have a Malmo Minecraft client running. The tutorial [here ](https://github.com/Microsoft/malmo/blob/master/Malmo/samples/Python_examples/Tutorial.pdf) might be helpful, if you haven't already seen it.)
