### ISSUE TITLE
Interface Arrangement of Blocks

### ISSUE THREAD

**Issue by EnricoDelPiero** [Microsoft/malmo#552]
Hello, 
is there a way to get specific information about the arrangement of blocks in the world?
I would like to check if certain blocks are in specific coordinates of the coordinate system after the agent did some work. 

for example: 
- Did the agent place a specific block type in xyz?
- Did the agent destroy a specific block in xyz? 

Is there any way i could get that type of information out of malmo? 
Best
Henry

**Comment by DaveyBiggers** [comment]
Hi Henry, take a look at the tutorial - https://github.com/Microsoft/malmo/blob/master/Malmo/samples/Python_examples/Tutorial.pdf - section 9 talks about the ObservationFromGrid, which is what you are after.
Some of the python samples also contain examples of its use - eg drawing_test.py.
