### ISSUE TITLE
Prompting Text in Minecraft Environment

### ISSUE THREAD

**Issue by EnricoDelPiero** [Microsoft/malmo#555]
Hi there! 
I'm working on Malmo tasks that can be solved by human players but also by AI. 
To make the environment more human-friendly i would like to prompt instructions and feedback on screen while the game is running. The text should appear in the game environment and should be adjustable in size and position. 

I couldnt find a feature that enables me to do this. If it already exists i would be very thankful for hints. 
If not please regard this as a feature request. 

Best, 
Henry

**Comment by EnricoDelPiero** [comment]
I improvised a solution using chat commands, however i am still looking for a more elegant way to provide feedback and instructions to the player...
Any ideas?

**Comment by katja-hofmann** [comment]
Hi @EnricoDelPiero,

the chat commands are a good Minecraft-based solution. For cases where we need more control over the human player interaction, we use a custom GUI. Here's an example: https://github.com/Microsoft/malmo/blob/master/Malmo/samples/Python_examples/human_action.py. Another example is the one we used for the Malmo Collaborative AI challenge: https://github.com/Microsoft/malmo-challenge/tree/master/ai_challenge/pig_chase

Best,
Katja
