### ISSUE TITLE
CMakeLists.txt still has major version 0.22

### ISSUE THREAD

**Issue by katja-hofmann** [Microsoft/malmo#574]

**Comment by DaveyBiggers** [comment]
Not by my reckoning - https://github.com/Microsoft/malmo/blob/master/CMakeLists.txt#L27
In theory it shouldn't even be possible to run the integration tests if this was true.

Ah, but the online documentation is probably still on version 0.22 - I'll update it now and close this issue when it's done.

**Comment by DaveyBiggers** [comment]
Have updated the online docs (was still on 0.21)
