### ISSUE TITLE
Fail to erase items

### ISSUE THREAD

**Issue by MicroSTM** [Microsoft/malmo#580]
I tried to add one item (e.g., diamond) at a random position for each episode. To "soft-reset" the world, I drew air blocks first every time. However, there are always leftover items after each episode. And #517 does not work for me. Is there a way to ease these items without "force-reset"?

The drawing decorator is like this:
> <DrawingDecorator>
          <DrawCuboid type="air" x1="-2" x2="2" y1="45" y2="226" z1="0" z2="4"/>
          <DrawCuboid type="sandstone" x1="-2" x2="2" y1="45" y2="45" z1="0" z2="4"/>
          <DrawItem type="diamond" x="0" y="46" z="4"/>
   </DrawingDecorator>

**Comment by DaveyBiggers** [comment]
Ah, looks like a classic out-by-one error... the code which draws the blocks is inclusive - eg z1="0" z2="4" will place five blocks, at z=[0,1,2,3,4]. But the code which clears out the old items is effectively exclusive - it clears up to the _start_ of the 4th block, not the _end_ of the 4th block (which is the start of the fifth). I think this has always been wrong.

I'm testing a fix, but in the meantime, you should be able to work around it by expanding the volume of air you are drawing.

**Comment by MicroSTM** [comment]
Thanks. That works.
