### ISSUE TITLE
Multi agent project

### ISSUE THREAD

**Issue by colmsjo** [Microsoft/malmo#586]
Hi,

I'm new here so point me in the right direction if this isn't the place to ask this question.

I'm working on a project where we want to observe multiple agents in a virtual world. The agents will cooperate and/or compete with each other for food etc. Is it possible to have an observer, not being an agent, that views the world and the agents within?

**Comment by DaveyBiggers** [comment]
There are a few ways of doing this. You could create an observer agent - multi_agent_test.py uses this approach - basically a "spare" Malmo agent that you don't send commands to, but which can provide a viewpoint on the world. (If you hit the enter key you can toggle AI/human control, and control the agent as a normal Minecraft player would.)
A variation of this approach is to run an extra Minecraft client, and log in manually - just find the game on the LAN and join it.

The second approach is to use the agent observations - see, for example, mob_fun.py (single agent) or tsp_race.py (multi agent) - they draw a representation of the world state using TKinter and the agent's observations.

I hope this gives you some pointers, do come back to us if you have any questions.

**Comment by DaveyBiggers** [comment]
Am closing this issue, assuming it's no longer blocking you. If you have any other questions do get in touch.
