### ISSUE TITLE
Getting Block Entity Data

### ISSUE THREAD

**Issue by toschug** [Microsoft/malmo#588]
Is it possible to enhance `ObservationFromRayImplementation.buildMouseOverData` to retrieve addtional block entity data?

For example signs have four lines of text (Text1, Text2, Text3, Text4) as extra data.
The agent could then "read" the sign (by using `ObservationFromRay` and then `prop_Text1` etc.) next to a door, to see whether it is his house for example.

Current output I have is:
`{"LineOfSight":{"hitType":"block","x":220.63356369148156,"y":86.60169553502067,"z":1552.125,"type":"wall_sign","prop_facing":"south","inRange":true,"distance":1.6947537660598755}}`

From what I can see (with my limited resources) it should be doable to implement, On the other hand this would certainly involve some work to get the extra data of ALL available "special" blocks.

I try it with some other block to assume it is "the sign with his name".
So this is more like a feature request than an urgent problem.

Does s.o. see a better wordaround here for the moment?
Or do I miss sth completly, as it is already possbile what I request?

Thanks!

**Comment by DaveyBiggers** [comment]
Good suggestion. I've added a flag to ObservationFromRay (false by default) to return the NBTTagCompound for tile entities - this will allow you to get the text from signs, amongst other things. There's an example of how to use it in decision_tree_test.py.
