### ISSUE TITLE
Observation for items for planning

### ISSUE THREAD

**Issue by ChristineTzeng** [Microsoft/malmo#602]
I've drawn many items on map discretely and now I want to detect/observe them without full state observation.
At the beginning I tried with ObservationFromGrid but it ended up with never catching item information- I'm so confused since my agents and my items are generated at the same plane and I did try with y from -1 to 1.
After that, I tried with ObservationFromNearbyEntities which did capture the nearby entity information. Anyway, is there other way or better way than ObservationFromNearbyEntities to achieve this?

**Comment by DaveyBiggers** [comment]
ObservationFromNearbyEntities is what you want - free-floating items are entities, as far as Minecraft is concerned. ObservationFromGrid only returns block types.

Note that ObservationFromNearbyEntities has a range limit - can't remember offhand what it is, but Minecraft unloads entities once they are a certain threshold away from the player, at which point they disappear from the observation. Items are also short-lived - Minecraft, as part of the default game mechanics, destroys them after something like five minutes.

If either of these limitations become an issue for you, please open a feature request about it - hopefully we can do something about it.
