### ISSUE TITLE
Python scripts ImportError on MalmoPython

### ISSUE THREAD

**Issue by amccraw** [Microsoft/malmo#606]
I've installed the latest (0.31.0) pre-built version of Malmo for Windows and followed all of the instructions, but cannot get the python examples to run.  Every time I try I get the error:

Traceback (most recent call last):
  File "run_mission.py", line 22, in <module>
    import MalmoPython
ImportError: DLL load failed: The specified module could not be found.

I found [issue 548](https://github.com/Microsoft/malmo/issues/548) and tried running the C++ examples, but those worked fine so it didn't help narrow down what DLL might be missing.  Is there any other way to try and narrow down what the issue is?

UPDATE - I waded through Dependency Walker, and it's looking for Python36.dll even though I'm running Python 2.7 with future installed

**Comment by okkhoy** [comment]
@amccraw how did you resolve this issue? can you please provide some details

**Comment by okkhoy** [comment]
@amccraw thanks! i will create another bug report then!
