### ISSUE TITLE
Block-player collision not working

### ISSUE THREAD

**Issue by pablogps** [Microsoft/malmo#611]
Blocks can be placed in positions that collide with the player. At least in some cases this results in pushing the player away from the new block.

**Comment by DaveyBiggers** [comment]
Looks like this got broken in Malmo 0.30.0 when we moved to Minecraft 11.
Seems like there was some major refactoring to Mojang's Block/BlockState code, in the process of which `Block.getCollisionBoundingBox` was changed such that it now returns an `AxisAlignedBB` which is _relative to the position of the block_ - ie (0,0,0,1,1,1) - whereas it previously returned the absolute co-ords of the bounding box. Helpfully the method still takes a `BlockPos` - it just ignores it.

So all we need to do is offset the AABB by the BlockPos ourselves. It's a one line fix. Would have been _nice_ if the method name had changed to reflect the completely different behaviour though...

**Comment by pablogps** [comment]
Glad to see it won't be much trouble!
