### ISSUE TITLE
can't run run_mission.py in macOS - issue in libxerces

### ISSUE THREAD

**Issue by lucasosouza** [Microsoft/malmo#618]
Hi guys!

I'm having a hard time configuring ProjectMalmo to run in macOS Sierra. When I tried to run run_mission.py, it fails when importing MalmoPython library. 

```
ImportError: dlopen(/Users/lucasosouza/Documents/Softwares/MalmoPlatform/Python_Examples/MalmoPython.so, 2): Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib
  Referenced from: /Users/lucasosouza/Documents/Softwares/MalmoPlatform/Python_Examples/MalmoPython.so
  Reason: image not found
```
I've checked the folder and indeed libxerces-c-3.1 is not there - it was updated to 3.2, and the brew formula will currently only install the 3.2 version of xerces-c. This is what I have in `otool -L MalmoPython.so`:

```
MalmoPython.so:
	@rpath/MalmoPython.so (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

The issue is homebrew formula installs the latest version, which is 3.2. I couldn't find a formula for 3.1. So I went to xerces-c website, and downloaded the previous version from there. The only compiled version is macOS x-86, which gave an architecture error, so I downloaded source code and compiled it locally.

This got me through the xerces-c issue, but now I ran into a new issue with the curl library referenced by xerces-c:

```
ImportError: dlopen(/Users/lucasosouza/Documents/Softwares/MalmoPlatform/Python_Examples/MalmoPython.so, 2): Library not loaded: libcurl.4.dylib
  Referenced from: /usr/local/opt/xerces-c/lib/libxerces-c-3.1.dylib
  Reason: Incompatible library version: libxerces-c-3.1.dylib requires version 8.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

I've updated my curl with homebrew already. I've changed PATH to read curl from the homebrew installed version. Before running ./configure to compile xerces-c, I've also tried setting the environment variables LDFLAGS and CPPFLAGS to point to my brew version of curl, which is 7.56.1. However, I keep getting the same error, even when I compile setting LDFLAGS and CPPFLAGS or when I compile without setting these.

Any ideas on how to proceed? I am not sure what I'm missing here, and I'm stuck at it in the moment. Thanks a lot

**Comment by lucasosouza** [comment]
Closing my own issue. I got it to work by changing PATH to read curl homebrew version before compiling xerces-3.1. Not sure what difference would this make since setting LDFLAGS and CPPFLAGS should be enough, but it somehow worked.

**Comment by ZhiruiFeng** [comment]
Hi lucasosouza, I met the exact same problem with you. Do you have any suggestion for solving this problem?
