### ISSUE TITLE
Error building on MacOSX: File CSharpWrapper/libMalmoNETNative.so not found

### ISSUE THREAD

**Issue by rocanaan** [Microsoft/malmo#624]
Hello,

I'm following the build instructions on Mac OS given on https://github.com/Microsoft/malmo/blob/master/doc/build_macosx.md and when doing make install I get the following output:

`10-253-0-180:build rodrigocanaan$ make install
[ 31%] Built target Malmo
[ 35%] Built target MalmoNETNative
[ 36%] Built target MalmoNET
[ 39%] Built target MalmoJava
[ 43%] Built target MalmoJavaJar
[ 45%] Built target MalmoPython
[ 47%] Built target CppTests_test_video_writer
[ 49%] Built target CppTests_test_video_server
[ 51%] Built target CppTests_test_parameter_set
[ 53%] Built target CppTests_test_string_server
[ 55%] Built target CppTests_test_persistence
[ 57%] Built target CppTests_test_argument_parser
[ 59%] Built target CppTests_test_client_server
[ 61%] Built target CppTests_test_mission
[ 63%] Built target CppTests_test_agent_host
[ 65%] Built target CppTests_create_tcp_server
Error copying file (if different) from "/Users/rodrigocanaan/MalmoPlatform/build/Malmo/src/CSharpWrapper/libMalmoNETNative.so" to "/Users/rodrigocanaan/MalmoPlatform/build/Malmo/test/CSharpTests/libMalmoNETNative.so".
make[2]: *** [CSharpTests_test_mission] Error 1
make[1]: *** [Malmo/test/CSharpTests/CMakeFiles/CSharpTests_test_mission.dir/all] Error 2
make: *** [all] Error 2
`

Going to ~MalmoPlatform/build/Malmo/src/CSharpWrapper/ I verify that the libMalmoNETNative.so is in fact missing. What could have gone wrong?

Thank you!

**Comment by rocanaan** [comment]
SOLVED

There was a "MalmoNETNative.so" file, which I renamed to "libMalmoNETNative.so"

**Comment by xorb0ss** [comment]
Just adding, this also happened on Arch.
Renaming fixed it.
