### ISSUE TITLE
Fail Trying to launch Minecraft

### ISSUE THREAD

**Issue by Creamiologist** [Microsoft/malmo#627]
I failed trying to lauch Minecraft Environment with the following error messages (it's too long so I just put some error bits):

DEBUG:minecraft_py:[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6

DEBUG:minecraft_py:[ant:javac] Note: Some input files use or override a deprecated API.

DEBUG:minecraft_py:[ant:javac] Note: Recompile with -Xlint:deprecation for details.

DEBUG:minecraft_py:[ant:javac] Note: Some input files use unchecked or unsafe operations.

DEBUG:minecraft_py:[ant:javac] Note: Recompile with -Xlint:unchecked for details.

DEBUG:minecraft_py:[ant:javac] 1 warning

DEBUG:minecraft_py::recompileMc FAILED

DEBUG:minecraft_py:

DEBUG:minecraft_py:FAILURE: Build failed with an exception.

DEBUG:minecraft_py:

DEBUG:minecraft_py:* What went wrong:

DEBUG:minecraft_py:Execution failed for task ':recompileMc'.

DEBUG:minecraft_py:> Problems opening file input stream for file: /home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/tmp/recompileMc/compiled/net/minecraft/network/play/server/S11PacketSpawnExperienceOrb.class

DEBUG:minecraft_py:

DEBUG:minecraft_py:* Try:

DEBUG:minecraft_py:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

DEBUG:minecraft_py:

DEBUG:minecraft_py:BUILD FAILED

DEBUG:minecraft_py:

DEBUG:minecraft_py:Total time: 10 mins 56.875 secs

DEBUG:minecraft_py:****************************

DEBUG:minecraft_py: Powered By MCP:

DEBUG:minecraft_py: http://modcoderpack.com/

DEBUG:minecraft_py: Searge, ProfMobius, Fesh0r,

DEBUG:minecraft_py: R4wk, ZeuX, IngisKahn, bspkrs

DEBUG:minecraft_py: MCP Data version : 9.10

DEBUG:minecraft_py:****************************

DEBUG:minecraft_py:Version string 'unspecified' does not match SemVer specification

DEBUG:minecraft_py:You should try SemVer : http://semver.org/

DEBUG:minecraft_py::deobfCompileDummyTask

DEBUG:minecraft_py::deobfProvidedDummyTask

DEBUG:minecraft_py::compileApiJava UP-TO-DATE

DEBUG:minecraft_py::processApiResources UP-TO-DATE

DEBUG:minecraft_py::apiClasses UP-TO-DATE

DEBUG:minecraft_py::copyModToClient UP-TO-DATE

DEBUG:minecraft_py::copyModToServer UP-TO-DATE

DEBUG:minecraft_py::deleteSchemas

DEBUG:minecraft_py::copySchemas

DEBUG:minecraft_py::jaxb

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-xjc/2.2.4-1/jaxb-xjc-2.2.4-1.pom

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.4-1/jaxb-impl-2.2.4-1.pom

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2.3/jaxb-api-2.2.3.pom

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.pom

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.pom

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-xjc/2.2.4-1/jaxb-xjc-2.2.4-1.jar

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.4-1/jaxb-impl-2.2.4-1.jar

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2.3/jaxb-api-2.2.3.jar

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar

DEBUG:minecraft_py:Download https://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.jar

DEBUG:minecraft_py::sourceMainJava

DEBUG:minecraft_py::compileJava

DEBUG:minecraft_py:Download https://libraries.minecraft.net/com/mojang/authlib/1.5.17/authlib-1.5.17.pom

DEBUG:minecraft_py:Download https://libraries.minecraft.net/com/mojang/authlib/1.5.17/authlib-1.5.17.jar

DEBUG:minecraft_py:error: error reading /home/alexzhou/.gradle/caches/minecraft/net/minecraftforge/forge/1.8-11.14.3.1543/snapshot/20141130/forgeSrc-1.8-11.14.3.1543.jar; error in opening zip file

DEBUG:minecraft_py:warning: [options] bootstrap class path not set in conjunction with -source 1.6

DEBUG:minecraft_py:error: error reading /home/alexzhou/.gradle/caches/minecraft/net/minecraftforge/forge/1.8-11.14.3.1543/snapshot/20141130/forgeSrc-1.8-11.14.3.1543.jar; cannot read zip file

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:24: error: package net.minecraftforge.event.entity.living does not exist

DEBUG:minecraft_py:import net.minecraftforge.event.entity.living.LivingDeathEvent;

DEBUG:minecraft_py:                                             ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:25: error: package net.minecraftforge.event.world does not exist

DEBUG:minecraft_py:import net.minecraftforge.event.world.ChunkEvent;

DEBUG:minecraft_py:                                     ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:26: error: package net.minecraftforge.fml.client.event.ConfigChangedEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.client.event.ConfigChangedEvent.OnConfigChangedEvent;

DEBUG:minecraft_py:                                                             ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:27: error: package net.minecraftforge.fml.common.eventhandler does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

DEBUG:minecraft_py:                                                 ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:28: error: package net.minecraftforge.fml.common.gameevent.PlayerEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent;

DEBUG:minecraft_py:                                                          ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:29: error: package net.minecraftforge.fml.common.gameevent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.TickEvent;

DEBUG:minecraft_py:                                              ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:22: error: package net.minecraftforge.event.entity.living does not exist

DEBUG:minecraft_py:import net.minecraftforge.event.entity.living.LivingDeathEvent;

DEBUG:minecraft_py:                                             ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:23: error: package net.minecraftforge.event.entity.living.LivingSpawnEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.event.entity.living.LivingSpawnEvent.CheckSpawn;

DEBUG:minecraft_py:                                                              ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:24: error: package net.minecraftforge.event.world does not exist

DEBUG:minecraft_py:import net.minecraftforge.event.world.ChunkEvent;

DEBUG:minecraft_py:                                     ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:25: error: package net.minecraftforge.event.world.WorldEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.event.world.WorldEvent.PotentialSpawns;

DEBUG:minecraft_py:                                                ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:26: error: package net.minecraftforge.fml.client.event.ConfigChangedEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.client.event.ConfigChangedEvent.OnConfigChangedEvent;

DEBUG:minecraft_py:                                                             ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:27: error: package net.minecraftforge.fml.common.gameevent.PlayerEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent;

DEBUG:minecraft_py:                                                          ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:28: error: package net.minecraftforge.fml.common.gameevent.TickEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.TickEvent.ClientTickEvent;

DEBUG:minecraft_py:                                                        ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:29: error: package net.minecraftforge.fml.common.gameevent.TickEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.TickEvent.PlayerTickEvent;

DEBUG:minecraft_py:                                                        ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:30: error: package net.minecraftforge.fml.common.gameevent.TickEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.TickEvent.RenderTickEvent;

DEBUG:minecraft_py:                                                        ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:31: error: package net.minecraftforge.fml.common.gameevent.TickEvent does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.gameevent.TickEvent.ServerTickEvent;

DEBUG:minecraft_py:                                                        ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:60: error: package TickEvent does not exist

DEBUG:minecraft_py:    public void onClientTick(TickEvent.ClientTickEvent ev)

DEBUG:minecraft_py:                                      ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:79: error: package TickEvent does not exist

DEBUG:minecraft_py:    public void onServerTick(TickEvent.ServerTickEvent ev)

DEBUG:minecraft_py:                                      ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:91: error: package TickEvent does not exist

DEBUG:minecraft_py:    public void onPlayerTick(TickEvent.PlayerTickEvent ev)

DEBUG:minecraft_py:                                      ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:103: error: package TickEvent does not exist

DEBUG:minecraft_py:    public void onRenderTick(TickEvent.RenderTickEvent ev)

DEBUG:minecraft_py:                                      ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:115: error: package ChunkEvent does not exist

DEBUG:minecraft_py:    public void onChunkLoad(ChunkEvent.Load cev)

DEBUG:minecraft_py:                                      ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:127: error: cannot find symbol

DEBUG:minecraft_py:    public void onPlayerDies(LivingDeathEvent lde)

DEBUG:minecraft_py:                             ^

DEBUG:minecraft_py:  symbol:   class LivingDeathEvent

DEBUG:minecraft_py:  location: class EpisodeEventWrapper

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:139: error: cannot find symbol

DEBUG:minecraft_py:    public void onConfigChanged(OnConfigChangedEvent ev)

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:  symbol:   class OnConfigChangedEvent

DEBUG:minecraft_py:  location: class EpisodeEventWrapper

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java:157: error: cannot find symbol

DEBUG:minecraft_py:    public void onPlayerJoinedServer(PlayerLoggedInEvent ev)

DEBUG:minecraft_py:                                     ^

DEBUG:minecraft_py:  symbol:   class PlayerLoggedInEvent

DEBUG:minecraft_py:  location: class EpisodeEventWrapper

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateMachine.java:24: error: package net.minecraftforge.common does not exist

DEBUG:minecraft_py:import net.minecraftforge.common.MinecraftForge;

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateMachine.java:25: error: package net.minecraftforge.fml.common does not exist

DEBUG:minecraft_py:import net.minecraftforge.fml.common.FMLCommonHandler;

DEBUG:minecraft_py:                                    ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:95: error: cannot find symbol

DEBUG:minecraft_py:    protected void onClientTick(ClientTickEvent ev) throws Exception {}

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:  symbol:   class ClientTickEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:97: error: cannot find symbol

DEBUG:minecraft_py:    protected void onServerTick(ServerTickEvent ev) {}

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:  symbol:   class ServerTickEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:99: error: cannot find symbol

DEBUG:minecraft_py:    protected void onPlayerTick(PlayerTickEvent ev) {}

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:  symbol:   class PlayerTickEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:101: error: cannot find symbol

DEBUG:minecraft_py:    protected void onRenderTick(RenderTickEvent ev) {}

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:  symbol:   class RenderTickEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:103: error: package ChunkEvent does not exist

DEBUG:minecraft_py:    protected void onChunkLoad(ChunkEvent.Load cev) {}

DEBUG:minecraft_py:                                         ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:105: error: cannot find symbol

DEBUG:minecraft_py:    protected void onPlayerDies(LivingDeathEvent event) {}

DEBUG:minecraft_py:                                ^

DEBUG:minecraft_py:  symbol:   class LivingDeathEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:107: error: cannot find symbol

DEBUG:minecraft_py:    protected void onConfigChanged(OnConfigChangedEvent event) {}

DEBUG:minecraft_py:                                   ^

DEBUG:minecraft_py:  symbol:   class OnConfigChangedEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/StateEpisode.java:109: error: cannot find symbol

DEBUG:minecraft_py:    protected void onPlayerJoinedServer(PlayerLoggedInEvent event) {}

DEBUG:minecraft_py:                                        ^

DEBUG:minecraft_py:  symbol:   class PlayerLoggedInEvent

DEBUG:minecraft_py:  location: class StateEpisode

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/MalmoAuthenticationScreen.java:26: error: package net.minecraft.client.gui does not exist

DEBUG:minecraft_py:import net.minecraft.client.gui.GuiButton;

DEBUG:minecraft_py:                               ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/MalmoAuthenticationScreen.java:27: error: package net.minecraft.client.gui does not exist

DEBUG:minecraft_py:import net.minecraft.client.gui.GuiScreen;

DEBUG:minecraft_py:                               ^

DEBUG:minecraft_py:/home/alexzhou/machine-learning/gym/lib/python2.7/site-packages/minecraft_py-0.0.2-py2.7.egg/minecraft_py/Malmo/Minecraft/build/sources/main/java/com/microsoft/Malmo/MalmoAuthenticationScreen.java:28: error: package net.minecraft.client.gui does not exist

DEBUG:minecraft_py:import net.minecraft.client.gui.GuiTextField;

...........

################################
The error goes on but later it's mainly about not being able to import net.minecraftforge.fml.client.config...

I'm not really sure what is going on... I have been trying to make this work for way too much time....

**Comment by DaveyBiggers** [comment]
I take it you are attempting to use Malmo as a gym environment, eg with this: https://github.com/tambetm/gym-minecraft ?

If you install and use Malmo according to our documentation, and run into problems, we will try to help you, but I'm afraid we don't have the resources to provide support for third-party systems. Can you contact them directly with your issue?
