### ISSUE TITLE
0.31.0 Malmo-0.31.0-Windows-64bit_Python3.6.zip release wrong mod version

### ISSUE THREAD

**Issue by laysdra7265** [Microsoft/malmo#628]
Looks like mode is old version.
It attempt to parse Handshake string as xml,and get a "SAXParseException:content is not allowed in prolog"Error
Never success to init a new mission.

**Comment by DaveyBiggers** [comment]
I'm not sure why this would happen, but I don't think it's to do with an old mod version in the zip. You can check the version of the mod by opening the mod options gui within Minecraft - it should say 0.31.0.
You can also check the version of the platform you are using by running any of the python samples with "--help", eg: `python MazeRunner.py --help` should print out `Malmo version 0.31.0 ...`
Finally, you can check the version number in the schemas - MALMO_XSD_PATH should point to a folder with five xsd files in it - all of those should have the version number at the top - eg:

```
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ProjectMalmo.microsoft.com"
           xmlns="http://ProjectMalmo.microsoft.com"
           elementFormDefault="qualified"
           version="0.31">
```

All three of these (the schemas, the mod, the platform) need to have matching version numbers - but if there is a mismatch things just won't run - the mod just won't start up if its version number doesn't match the schemas, for instance. It shouldn't result in a SAXParseException. There must be something else going on here.
Can you post some more information? The Minecraft log would be especially helpful.

**Comment by Phantomb** [comment]
Just weighing in with my experience with the latest release: I managed to install the latest release without any real problems. The only minor issues I had were the ones I mentioned in #271 : https://github.com/Microsoft/malmo/issues/271#issuecomment-341992800

This might somehow be related to the first issue I mentioned there? (the reported XSD version mismatch)

**Comment by laysdra7265** [comment]
That wired,when the problem appearing,I found the code in the "Minecraft\src\main\java\com\microsoft\Malmo\Client" is old version,and i spent whole day to recompile my self the new version mod code.
And now i recheck the zip i download that time,the source code in is the correct version???how??
well I don't know how did it happen,maybe something goes wrong when my first installed,the old code overwrite the file?I might accident overwrite the code for some reason that i didn't notice.

**Comment by laysdra7265** [comment]
Well I need to reinstall again to see if the problem appear again.
(I had some mod program experience.So actually I recompile myself with correct code and get it work

**Comment by laysdra7265** [comment]
OK,nothing bad happen this time,sorry,looks like I careless overwriting the file :(
(I don't known what I did wrong that time,and I even don't known where the old code come from:(
