### ISSUE TITLE
Python examples saving video frames throws PIL.Image error

### ISSUE THREAD

**Issue by Phantomb** [Microsoft/malmo#631]
The python examples that optionally save video frames (if `save_images` is set to `True`) like `robust_frames.py` and `tabular_q_learning` throw an error:

https://pastebin.com/uuAZdWKX

This is because the image data is expected as a byte-like structure instead of a string. (NB: the byte-like structure is not the same as the byte array datatype that the pixels already are).

To fix this error, I changed `str(frame.pixels)` to `bytes(frame.pixels)` after which it runs and correctly saves the images.

Do you want me to make an edit to the affected files and submit a pull request for those?

**Comment by DaveyBiggers** [comment]
Ah yes, good spot - I missed this when updating from Py2 to Py3. Yes, please, if you have time to make a PR that would be great.

**Comment by Phantomb** [comment]
PR submitted & Awaiting checks. Do note that I haven't tested it with python2. I'm not sure if we'd need to check for that to retain the old version of the code in that case? Let's hope it just works 😇
