### ISSUE TITLE
extractUserdev FAILED when runclient.bat

### ISSUE THREAD

**Issue by bobbyte** [Microsoft/malmo#632]
Hi

I've been trying to install and run Malmo.

I followed the installation guide and now have a problem with runclient.bat

`
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extractUserdev'.
> Could not expand ZIP 'D:\My Documents\\.gradle\caches\modules-2\files-2.1\net.minecraftforge\forge\1.11.2-13.20.0.2228\
326dcc73b90cdfa451d145dcf3d6e34797d378a\forge-1.11.2-13.20.0.2228-userdev.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.466 secs`

At first I thought it has problem with permission so I've changed GRADLE_USER_HOME to a writable directory but it still has problem

Please help. Thank you.

**Comment by DaveyBiggers** [comment]
From a bit of digging, it looks like gradle is sometimes upset by spaces in the file path - can you try changing GRADLE_USER_HOME to something without spaces (eg not "My Documents")?

**Comment by bobbyte** [comment]
![image](https://user-images.githubusercontent.com/2357254/33028981-ebb93542-ce49-11e7-8a8a-3550d2408910.png)

Thank you but I've tried and it is the same.
Is it has something to do with name too long?
or can I manually unzip that file >,< Because I can open it with WinRAR but I dont know where to place the contents

Regards.

**Comment by xorb0ss** [comment]
Can you run ./launchClient.bat with --info or --debug and attach the screenshot or paste the log output?

**Comment by bobbyte** [comment]
It say
Error: Invalid option --info
![image](https://user-images.githubusercontent.com/2357254/33186500-f6dabaf6-d081-11e7-9736-df7b7dec70c6.png)

I have tried 
1. uninstall every Java and only use Java from Malmo
2. try Malmo .31
3. try on different computer (win10 and win8)

But it doesn't work I really don't know why haha.

(I can install on macbook so I'm fine for the time being, but I really curious what about this problem)
