### ISSUE TITLE
vs Google3D environment Malmo can be the a new tool for language understanding!

### ISSUE THREAD

**Issue by yliu90** [Microsoft/malmo#636]
recently, google has published their new environment (deepmind 3D ) for language understanding. This news make me wonder if microsoft can assign more people to update project malmo more faster and add more language research features into it ?(which is a hot topic in natural language processing area, according to my experience, I'm a PHD btw) Since I believe the Malmo is far more powerful than google 3D.

just suggest...

**Comment by tesslerc** [comment]
Where did you see that Google/DeepMind published the language understanding domains?
All I found is the general DeepMind Labs which doesn't contain the language modeling parts.

**Comment by yliu90** [comment]
Few months ago, Google Deepmind has released this work to exhibit the idea of language learning via a simulated environment.
Hermann, K. M., Hill, F., Green, S., Wang, F., Faulkner, R., Soyer, H., ... & Wainwright, M. (2017). Grounded language learning in a simulated 3d world. arXiv preprint arXiv:1706.06551.

**Comment by DaveyBiggers** [comment]
Thank you for your suggestion, and for the interesting paper. Obviously, we'd love to have more people working on Malmo, and we're also particularly interested in the area of grounded natural language - one of [my colleagues](https://www.microsoft.com/en-us/research/people/nkushman/) is very active in this area. In the meantime, Malmo is open source, so we'd love to get the community to contribute to its development - and if there are any specific NLP features you'd like to see, you are welcome to add feature requests here as github issues!
