### ISSUE TITLE
Requesting uninstall option in Makefile

### ISSUE THREAD

**Issue by xorb0ss** [Microsoft/malmo#638]
After building from source for Linux, I noticed there is no uninstall option.
Could this be provided or is there already a built-in uninstall method I'm overlooking?

**Comment by DaveyBiggers** [comment]
There's no `make uninstall` provided, but Malmo doesn't put anything anywhere except its own install folder, so there's no special work involved in uninstalling it - either just delete your build folder, or use the build/install_manifest.txt file - this is a list of all the files that got created as part of `make install`.
(You can do something like `xargs rm < install_manifest.txt`)

I hope that's sufficient for your needs, but if there's a compelling reason why we should add a `make uninstall` option, please reopen this issue and let us know, and perhaps we'll revisit this.
Cheers!
