### ISSUE TITLE
Automatic installation script Python version wrong?

### ISSUE THREAD

**Issue by wsdonny** [Microsoft/malmo#649]
It seems like in the newest release `0.31.0`, different zip file support different Python version? Such as `Malmo-0.31.0-Windows-64bit_Python3.6.zip` might only support Python 3?

I installed using the script on a totally new system, it only automatically installed Python 2, which cannot run the Python_Examples (`ImportError: DLL load failed: The specified module could not be found.`). I manually installed Python 3 and everything is fine.

So maybe the Python version in `malmo_install.ps1` should be changed?

**Comment by DaveyBiggers** [comment]
Good point. This has now been fixed - the installation now contains a `malmo.properties` file, which the installation script now checks to determine which version of Python to install.
