### ISSUE TITLE
Mac: Unable to execute run_mission.py

### ISSUE THREAD

**Issue by bogey12** [Microsoft/malmo#654]
If I try to launch a python agent using:
Python_Examples Tony$ /usr/bin/python run_mission.py

I get the following error:
Exception in closing of MissionRecord: Attempt to write to non-existent directory: ./mission_records/979fa2f0-8207-4753-b0fe-b8ce67a843b9

However, while the command is still running (before the error). In the MissionRecord directory, a directory will be created:
<img width="713" alt="error 1" src="https://user-images.githubusercontent.com/34564684/35191341-966d916e-fe2d-11e7-871e-8fa0d6652380.png">

Then the directory is deleted and replaced by a different one:
<img width="725" alt="error 2" src="https://user-images.githubusercontent.com/34564684/35191375-3401a974-fe2e-11e7-8d34-88381cd28c06.png">

Finally, this new directory is deleted and replaced by two empty directories:
<img width="704" alt="error 3" src="https://user-images.githubusercontent.com/34564684/35191386-5964e97e-fe2e-11e7-93e1-c3bdfe0b5d59.png">

**Comment by AndKram** [comment]
Time to try a newer release for MacOS.
