### ISSUE TITLE
erro quando tento abrir o minecraft 

### ISSUE THREAD

**Issue by jo0n** [Microsoft/malmo#657]
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-d13a6c8
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches SKIPPED
:remapMcSources SKIPPED
:recompileMc SKIPPED
:extractNatives SKIPPED
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 28/1196   2%
Current status: 99/1196   8%
Current status: 152/1196   12%
Current status: 210/1196   17%
Current status: 274/1196   22%
Current status: 358/1196   29%
Current status: 459/1196   38%
Current status: 540/1196   45%
Current status: 578/1196   48%
Current status: 665/1196   55%
Current status: 758/1196   63%
Current status: 844/1196   70%
Current status: 927/1196   77%
Current status: 993/1196   83%
Current status: 1080/1196   90%
Current status: 1181/1196   98%
:makeStart
:setupDecompWorkspace

BUILD SUCCESSFUL

Total time: 3 mins 43.719 secs
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-d13a6c8
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient UP-TO-DATE
:copyModToServer UP-TO-DATE
:deleteSchemas
:copySchemas
:jaxb
[ant:xjc] [WARNING] schema_reference.4: Falha ao ler o documento do esquema 'Types.xsd' porque 1) nÒo foi possÝvel encontrar o documento; 2) nÒo foi possÝvel ler o documento; 3) o elemento-raiz do documento nÒo Ú <xsd:schema>.
[ant:xjc]   line 11 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [WARNING] schema_reference.4: Falha ao ler o documento do esquema 'MissionHandlers.xsd' porque 1) nÒo foi possÝvel encontrar o documento; 2) nÒo foi possÝvel ler o documento; 3) o elemento-raiz do documento nÒo Ú <xsd:schema>.
[ant:xjc]   line 12 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'BlockOrItem' para um componente 'type definition'.
[ant:xjc]   line 253 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'BlockOrItem' para um componente 'simpleType definition'.
[ant:xjc]   line 253 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'Variation' para um componente 'type definition'.
[ant:xjc]   line 254 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'Variation' para um componente 'simpleType definition'.
[ant:xjc]   line 254 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'Colour' para um componente 'type definition'.
[ant:xjc]   line 255 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'Colour' para um componente 'simpleType definition'.
[ant:xjc]   line 255 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'PosAndDirection' para um componente 'type definition'.
[ant:xjc]   line 122 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'EntityTypes' para um componente 'type definition'.
[ant:xjc]   line 171 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromRecentCommands' para um componente 'element declaration'.
[ant:xjc]   line 331 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromHotBar' para um componente 'element declaration'.
[ant:xjc]   line 332 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromFullStats' para um componente 'element declaration'.
[ant:xjc]   line 333 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromFullInventory' para um componente 'element declaration'.
[ant:xjc]   line 334 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromSubgoalPositionList' para um componente 'element declaration'.
[ant:xjc]   line 335 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromGrid' para um componente 'element declaration'.
[ant:xjc]   line 336 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromDistance' para um componente 'element declaration'.
[ant:xjc]   line 337 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromDiscreteCell' para um componente 'element declaration'.
[ant:xjc]   line 338 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromChat' para um componente 'element declaration'.
[ant:xjc]   line 339 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromNearbyEntities' para um componente 'element declaration'.
[ant:xjc]   line 340 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromRay' para um componente 'element declaration'.
[ant:xjc]   line 341 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ObservationFromTurnScheduler' para um componente 'element declaration'.
[ant:xjc]   line 342 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'VideoProducer' para um componente 'element declaration'.
[ant:xjc]   line 344 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'DepthProducer' para um componente 'element declaration'.
[ant:xjc]   line 345 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'LuminanceProducer' para um componente 'element declaration'.
[ant:xjc]   line 346 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ColourMapProducer' para um componente 'element declaration'.
[ant:xjc]   line 347 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForTouchingBlockType' para um componente 'element declaration'.
[ant:xjc]   line 349 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForSendingCommand' para um componente 'element declaration'.
[ant:xjc]   line 350 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForSendingMatchingChatMessage' para um componente 'element declaration'.
[ant:xjc]   line 351 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForCollectingItem' para um componente 'element declaration'.
[ant:xjc]   line 352 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForDiscardingItem' para um componente 'element declaration'.
[ant:xjc]   line 353 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForReachingPosition' para um componente 'element declaration'.
[ant:xjc]   line 354 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForMissionEnd' para um componente 'element declaration'.
[ant:xjc]   line 355 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForStructureCopying' para um componente 'element declaration'.
[ant:xjc]   line 356 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForTimeTaken' para um componente 'element declaration'.
[ant:xjc]   line 357 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForCatchingMob' para um componente 'element declaration'.
[ant:xjc]   line 358 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'RewardForDamagingEntity' para um componente 'element declaration'.
[ant:xjc]   line 359 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ContinuousMovementCommands' para um componente 'element declaration'.
[ant:xjc]   line 361 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AbsoluteMovementCommands' para um componente 'element declaration'.
[ant:xjc]   line 362 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'DiscreteMovementCommands' para um componente 'element declaration'.
[ant:xjc]   line 363 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'InventoryCommands' para um componente 'element declaration'.
[ant:xjc]   line 364 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ChatCommands' para um componente 'element declaration'.
[ant:xjc]   line 365 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'SimpleCraftCommands' para um componente 'element declaration'.
[ant:xjc]   line 366 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'MissionQuitCommands' para um componente 'element declaration'.
[ant:xjc]   line 367 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'TurnBasedCommands' para um componente 'element declaration'.
[ant:xjc]   line 368 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AgentQuitFromTimeUp' para um componente 'element declaration'.
[ant:xjc]   line 371 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AgentQuitFromReachingPosition' para um componente 'element declaration'.
[ant:xjc]   line 372 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AgentQuitFromTouchingBlockType' para um componente 'element declaration'.
[ant:xjc]   line 373 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AgentQuitFromCollectingItem' para um componente 'element declaration'.
[ant:xjc]   line 374 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AgentQuitFromReachingCommandQuota' para um componente 'element declaration'.
[ant:xjc]   line 375 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AgentQuitFromCatchingMob' para um componente 'element declaration'.
[ant:xjc]   line 376 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AbsoluteMovementCommands' para um componente 'element declaration'.
[ant:xjc]   line 390 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'DiscreteMovementCommands' para um componente 'element declaration'.
[ant:xjc]   line 391 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'InventoryCommands' para um componente 'element declaration'.
[ant:xjc]   line 392 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ChatCommands' para um componente 'element declaration'.
[ant:xjc]   line 393 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'SimpleCraftCommands' para um componente 'element declaration'.
[ant:xjc]   line 394 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'MissionQuitCommands' para um componente 'element declaration'.
[ant:xjc]   line 395 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'FlatWorldGenerator' para um componente 'element declaration'.
[ant:xjc]   line 424 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'FileWorldGenerator' para um componente 'element declaration'.
[ant:xjc]   line 425 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'DefaultWorldGenerator' para um componente 'element declaration'.
[ant:xjc]   line 426 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'DrawingDecorator' para um componente 'element declaration'.
[ant:xjc]   line 434 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'AnimationDecorator' para um componente 'element declaration'.
[ant:xjc]   line 435 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'MazeDecorator' para um componente 'element declaration'.
[ant:xjc]   line 436 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ClassroomDecorator' para um componente 'element declaration'.
[ant:xjc]   line 437 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'SnakeDecorator' para um componente 'element declaration'.
[ant:xjc]   line 438 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'MovingTargetDecorator' para um componente 'element declaration'.
[ant:xjc]   line 439 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'BuildBattleDecorator' para um componente 'element declaration'.
[ant:xjc]   line 440 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ServerQuitFromTimeUp' para um componente 'element declaration'.
[ant:xjc]   line 448 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: NÒo Ú possÝvel resolver o nome 'ServerQuitWhenAnyAgentFinishes' para um componente 'element declaration'.
[ant:xjc]   line 449 of file:/C:/Users/joÒo/Downloads/Malmo-0.31.0-Windows-64bit_Python3.6/Malmo-0.31.0-Windows-64bit_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
:jaxb FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\joÒo\Downloads\Malmo-0.31.0-Windows-64bit_Python3.6\Malmo-0.31.0-Windows-64bit_Python3.6\Minecraft\build.gradle' line: 164

* What went wrong:
Execution failed for task ':jaxb'.
> unable to parse the schema. Error messages should have been provided

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 16.146 secs

**Comment by DaveyBiggers** [comment]
I suspect the problem might be due to the non-ASCII character in your path - "joÒo" - we've had problems with this in the past. Try installing Malmo somewhere else, and make sure MALMO_XSD_PATH is set correctly. Let us know if that helps!

**Comment by DaveyBiggers** [comment]
I'm closing this since we've not heard from you for a week - but please do re-open and provide more details if this is still a problem.
