### ISSUE TITLE
Output labelled pixel data

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#66]
For object recognition it might be useful at some point to output labelled pixel data - assign a different color to each block and entity type.

Let us know if this is a feature that would be useful to you. We think it can be done with a custom shader for example.

**Comment by DaveyBiggers** [comment]
Done in 0.31.0. Enjoy!

**Comment by biggzlar** [comment]
> Done in 0.31.0. Enjoy!

Where and how? :D
