### ISSUE TITLE
error when trying to open tutorial 1

### ISSUE THREAD

**Issue by jo0n** [Microsoft/malmo#660]
No module named builtins

**Comment by rodneyp290** [comment]
I come across this problem too. 
Release [0.31.0](https://github.com/Microsoft/malmo/releases/tag/0.31.0) mentions the support to Python 3 in the breaking changes, and that you may need to run `pip install future` if you're using python2.
This solved the issue for me, hope it helps.

**Comment by DaveyBiggers** [comment]
Thanks Rodney.
@jo0n I'm assuming that solved your issue - please re-open and provide further information if it didn't.
