### ISSUE TITLE
Potential C# Wrapper library name issue

### ISSUE THREAD

**Issue by rodneyp290** [Microsoft/malmo#661]
When building ( master - Malmo https://github.com/Microsoft/malmo/commit/d3057d3055e773033e6a126f7b28cd5aec282eee ) on my Arch Linux I run into the following problem:
```Scanning dependencies of target CSharpTests_test_argument_parser
[ 68%] Compiling C# exe CSharpTests_test_argument_parser: '/usr/bin/mcs /t:exe /out:CSharpTests_test_argument_parser.exe /platform:x64 /sdk:4 /reference:System.dll;/reference:~/repos/malmo/build/Malmo/src/CSharpWrapper/MalmoNET.dll ~/repos/malmo/Malmo/test/CSharpTests/test_argument_parser.cs'
Error copying file (if different) from "~/repos/malmo/build/Malmo/src/CSharpWrapper/libMalmoNETNative.so" to "~/repos/malmo/build/Malmo/test/CSharpTests/libMalmoNETNative.so".
make[2]: *** [Malmo/test/CSharpTests/CMakeFiles/CSharpTests_test_argument_parser.dir/build.make:67: CSharpTests_test_argument_parser] Error 1
make[1]: *** [CMakeFiles/Makefile2:1812: Malmo/test/CSharpTests/CMakeFiles/CSharpTests_test_argument_parser.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
and when I look in `~/repos/malmo/build/Malmo/test/` I find ` MalmoNETNative.so` instead of `libMalmoNETNative.so`

I found that the find build/Malmo/src/CSharpWrapper/CMakeFiles/MalmoNETNative.dir/link.txt (produced by cmake) contains a single c++ compile line with the output flag `-o MalmoNETNative.so`.
By manually changing the flag to `-o libMalmoNETNative.so` I was able to get it to make install to run successfully. 
However, since the file is create by cmake, I didn't feel like this was an adequate solution.

Starting from scratch, I removed my current build dir and searched for instances of `libMalmoNETNative` and `MalmoNETNative`. Since MalmoNETNative was more prevalent I replaced all occurence of `libMalmoNETNative` with `MalmoNETNative` (see fork: https://github.com/rodneyp290/malmo/commit/7faeb2109a053547dad087ec717a9aeafaacf821), which seems to have fixed the issue...

However, since I am admittedly not actually familiar with the actual code and what I might be breaking, I thought I would raise an issue instead of a pull request.

**Comment by DaveyBiggers** [comment]
Thanks for looking into this Rodney.

It would appear that this was broken by a change to CMake in v3.9.0 - see here: https://github.com/Kitware/CMake/commit/8ed663791bdda4e726f7b3764bc75f8856724d6f
CMake has (incorrectly, I think) dropped the lib prefix for C# libraries.
Unfortunately, your suggested fix would break the compile for people using older versions of CMake, but it's an easy fix to explicitly specify the "lib" prefix in our own /Malmo/src/CSharpWrapper/CMakeLists.txt - I'll be merging this fix into master in the next few days, but if you want it now you can cherry-pick https://github.com/Microsoft/malmo/commit/43b7b360e07300786351f4a7612120bc7fad7b06.

**Comment by rodneyp290** [comment]
Hey @DaveyBiggers, just a quick follow up. I checked out the current build_experiment, and aside from running in to a [mono issue](https://github.com/mono/mono/issues/6752), with a simple `export TERM=xterm` workaround.
The build is mostly fine up until the installing phase when I received this error:
```-- Up-to-date: /home/rodney/repos/malmo/build/install/Minecraft/launchClient.sh
-- Installing: /home/rodney/repos/malmo/build/install/Minecraft/src/main/resources/version.properties
CMake Error at Minecraft/cmake_install.cmake:653 (file):
  file INSTALL cannot find
  "/home/rodney/repos/malmo/Minecraft/build/libs/MalmoMod-0.32.0.jar".
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
``` looking in the `Minecraft/build/libs` there is a `MalmoMod-0.31.0.jar`
By creating a symbolic link I could trick it into building "successfully" , but running the Minecraft `lauchClient.sh` logically fails due to the incorrect version
`java.lang.RuntimeException: This mod has been incorrectly built; check schema version numbers.`

**Comment by rodneyp290** [comment]
So I ran `git clean -xdf` (then added `Schema/xs3p.xsl` back), and now the build works fine, and I have checked the python tutorial run :+1:
