### ISSUE TITLE
error opening launch_minecraft_in_background

### ISSUE THREAD

**Issue by jo0n** [Microsoft/malmo#663]
A problem occurred evaluating root project 'Minecraft'.
> version.properties file is missing - this is created automatically by CMake. If you are building from source, make sure you have built the full source tree, not just the Minecraft folder.+

**Comment by DaveyBiggers** [comment]
The error message tells you everything you need to know.
Try either using a pre-built released version of Malmo (downloadable from the [releases](https://github.com/Microsoft/malmo/releases) page), or, if you are building from source yourself, make sure you've properly built the whole project - the build process generates the version.properties file for you.
I suspect you've gone for the unworkable middle option - downloading a zip of the source and attempting to run it without building it first?

**Comment by DaveyBiggers** [comment]
Am closing this since we haven't heard from you in a while, but if this is still a problem feel free to reopen and give us some more details.
