### ISSUE TITLE
Installation : Anaconda recipes for Malmo

### ISSUE THREAD

**Issue by spMohanty** [Microsoft/malmo#664]
Hi,

I spent some time writing [conda](https://anaconda.org/anaconda) recipes for Malmo, with the goal that installation across all platforms can be deterministically done just by doing : 
```
# Env setup
conda create python=2.7 --name malmo # you are free to replace '2.7' with python '3.5' or python '3.6' 
source activate malmo
conda config --add channels conda-forge

# Install malmo
conda install -c crowdai malmo

# Use Malmo
python -c "import MalmoPython" #for use of the Python API
malmo-server -port 10001 # For launching the minecraft client
```
If you are `osx64` or `linux64`, then the instructions above should work for you if you have [anaconda installed](https://www.anaconda.com/download/).

I currently have the following builds available for Malmo version `0.31.0`: 
- [x] osx64/py27
- [x] osx64/py35
- [x] osx64/py36
- [x] linux64/py27
- [x] linux64/py35
- [x] linux64/py36
- [ ] win64/py27
- [ ] win64/py35
- [ ] win64/py36
- [ ] win32/py27
- [ ] win32/py35
- [ ] win32/py36

The recipes are available at [https://github.com/spMohanty/malmo-conda-recipe](https://github.com/spMohanty/malmo-conda-recipe), and pull requests are very much welcome :smile: Yet to write down the recipe for Windows builds.

If there are any errors when you try this out, please do follow up either on the issue tracker of the actual repository, or on this thread.

cc/  @katja-hofmann

**Comment by AndKram** [comment]
Being reworked for the Marlo competition.

**Comment by AndKram** [comment]
Conda builds available for MarLo competition: https://github.com/crowdAI/marlo-multi-agent-starter-kit/
