### ISSUE TITLE
Error when launching the Mod - Import MalmoPython fails

### ISSUE THREAD

**Issue by JoannaFJ** [Microsoft/malmo#689]
Hi, 

I have installed the release Malmo-0.34.0-Windows-64bit_withBoost_Python3.6 and followed the instructions regarding the installation (and have repeated the steps multiple times). But I am stuck to this error while trying to launch the mod from Python_Examples: 

_Traceback (most recent call last): 
File "tabular_q_learning.py", line 32, in <module>
import MalmoPython
ImportError: DLL load failed: The specified module could not be found._ 

I can find the MalmoPython.lib and MalmoPython.pyd files from the Python_Examples Folder. Additionally the installation (.\malmo_install.ps1) was successfull. I am able to launch the Minecraft with .\launchClient.bat. 

I have checked the paths and they seem to be ok - I have the following set correctly: 
MALMO_XSD_PATH: ...Malmo-0.34.0-Windows-64bit_withBoost_Python3.6\Schemas
Path (contains): C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64
PYTHONPATH: ...Malmo-0.34.0-Windows-64bit_withBoost_Python3.6\Python_Examples

Please could someone help and tell what else should I check? Thanks!

**Comment by AndKram** [comment]
You could try running the "run_mission" C++ example. Often you get more linking errors than from the Python example. The 0.35 release has cut out several dependencies on Windows so it may work for you.

**Comment by AndKram** [comment]
Re-raise if 0.36 fails to install please.
