### ISSUE TITLE
Allow access to ClientInfo in ClientPool to make killClient easier to use

### ISSUE THREAD

**Issue by katja-hofmann** [Microsoft/malmo#691]
The scenario: I have a ClientPool and want to restart the clients in it at regular intervals. At the moment, ClientPool does not expose a list of its clients, so I need to maintain a separate list with pointers to the individual ClientInfo's. Ideally, I'd like to be able to do something like this:

```Python
for client in my_client_pool:
    my_agent_host.killClient(client)
```

**Comment by AndKram** [comment]
Fixed in 0.35
