### ISSUE TITLE
Issue with power shell script .\malmo_install.ps1

### ISSUE THREAD

**Issue by ileonidmas** [Microsoft/malmo#692]
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."

**Comment by swayson** [comment]
+1

**Comment by burgessjack** [comment]
+1

**Comment by ileonidmas** [comment]
I think I solved it. Go to https://ffmpeg.zeranoe.com/builds/win64/static/ and copy the name of the latest zip (lets say its ffmpeg-latest-win64-static.zip)

Now go to the location of your git repo (for example I have C:\Users\username\Desktop\Malmo-0.34.0-Windows-64bit_withBoost_Python3.6\scripts\pslib) and open malmo_lib.psm1 .

Go to line number number 112 and be sure that the link to the file you download is the name you coppied before. For example, this is mine http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip. Moreover, you might want to change the line 116 and 117 as well since it is the location of the folder. You can check what is being unpacked in this folder C:\ffmpeg.

**Comment by AndKram** [comment]
I believe this is already fixed on the master branch (issue #678).
