### ISSUE TITLE
Win10 launchClient build failure

### ISSUE THREAD

**Issue by RockmanZheng** [Microsoft/malmo#693]
* What went wrong:
A problem occurred evaluating root project 'Minecraft'.
> Failed to apply plugin [id 'net.minecraftforge.gradle.forge']
   > Unable to obtain url ([https://launchermeta.mojang.com/mc/game/version_manifest.json]) with etag!

**Comment by RockmanZheng** [comment]
I cannot visit the site launchermeta.mojang.com even on Edge browser. It seems that I cannot access this page.

**Comment by hexiaobing5880** [comment]
@RockmanZheng I solved this problem by referring to this site: https://plugins.gradle.org/plugin/net.minecraftforge.gradle.forge  （Build script snippet for plugins DSL for Gradle 2.1 and later）

**Comment by RockmanZheng** [comment]
@hexiaobing5880 Thanks for your response. I will close this thread once I figure it out with your advice. Thank you again for your clue.

**Comment by RockmanZheng** [comment]
@hexiaobing5880 I copied the code in the website you gave me into build.gradle. Things can be downloaded with this change. But another error occurred.

There are no mappings for MC 1.11.2

In build.gradle, minecraft{...}, version = "1.11.2-13.20.0.2228" and mappings = "snapshot_20161220" seems to be mismatched.

**Comment by RockmanZheng** [comment]
No. But I work around this issue by install Malmo on Ubuntu 16.04 (Linux system). @fixbut

**Comment by AndKram** [comment]
Tracking under #714. Some people are still having problems getting the mappings.
