### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by aierwei** [Microsoft/malmo#703]
* Where:
Build file 'C:\ProgramData\ProjectMalmo\malmo-master\Minecraft\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating root project 'Minecraft'.
> version.properties file is missing - this is created automatically by CMake. If you are building from source, make sure you have built the full source tree, not just the Minecraft folder.

**Comment by AndKram** [comment]
Please try building using cmake in the Minecraft parent directory and the launching Minecraft by changing directory into the Mincraft directory/folder and running ./launchClient.sh or launchClient.bat (on Windows). It's not possible to run gradle directly without some build initialization.

**Comment by ProQianXiao** [comment]
I have the same problem,  I use the command "pip install malmo" to install malmo, and that was fine.
Next I download the "malmo-master.zip" and unzip it, then I cd Minecraft, use the command "launchClient"
,and get the same error.

Could you tell me the detailed methods, thanks very much.
