### ISSUE TITLE
observations in multi-agent mission

### ISSUE THREAD

**Issue by irabkina** [Microsoft/malmo#704]
According to the documentation, several observe commands in the mission spec (e.g. observeGrid, observeFullInventory, etc.) only support single agent missions. Is this true of the latest release, and if so, are there any known workarounds?

Thanks,
Irina

**Comment by irabkina** [comment]
In practice, observations of all kinds seem to work just fine in multi-agent missions. Looks like that particular note in the documentation is out of date.

**Comment by AndKram** [comment]
Marlo has an API for creating a mission spec which is not very fully features compared with creating/editing the mission xml yourself. Not sure what documentation exactly but suspect it just referring to limitations in the api.

**Comment by AndKram** [comment]
You could try the Marlo API https://github.com/crowdAI/marLo or contibute to that if it still does not meet multi-agent needs.
