### ISSUE TITLE
DLL Load Failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by idvhfd** [Microsoft/malmo#705]
Title says it all.
Installed normally using the guidance steps highlighted in the readme and install_windows.md
Operating system: Win 10 Pro x64
Distributable or compiled?: Distributable, used the 0.34.0 windows x64 Python 3.6 version.
All dependencies installed as highlighted: I tried both manually and through the automatic installation. Also tried manually by following the powershell scripts' flow to ensure correctitude. This includes the C++ redistributables, which were installed accordingly.
MALMO_XSD_PATH is set to Schemas folder
Codesynthesis XSD x64 bin folder as well as x86 bin folder both added to PATH correctly
Python 3.6 added to PATH correctly
FFMPEG and XSD work when prompted in CMD or PS

Starting the client up works (albeit with an error that I've seen in another issue)
When booting up any agent, I am greeted by the following error:
![image](https://user-images.githubusercontent.com/31739117/41052393-8e6d7148-69b0-11e8-89b3-79dc4cf2df8e.png)

I've seen numerous issues raised on this topic. I've tried the solutions specified there and few of my own. Yet I feel compelled still to raise this issue again, for I have failed to make it run. Can anyone see what I'm missing?

**Comment by irabkina** [comment]
Make sure you're using 64-bit Python. I had the same error with 32-bit.

**Comment by AndKram** [comment]
You could try to see if you have 32 or 64 bit Python (e.g. python -c "import platform; platform.architecture()")? If it's 32 bit then a complete uninstall followed by a manual install of the 64 bit version would be necessary (as Malmo is 64 bit).

**Comment by idvhfd** [comment]
That is precisely what the issue was, I received a PM regarding this and forgot to come reply and close last week.

Indeed, do pay careful attention to the version of Python installed on your machine, especially if you had previous versions of Python installed before running the Malmo installation script.

Thanks both.
