### ISSUE TITLE
Error on installing ffmpeg 

### ISSUE THREAD

**Issue by Itsatsu** [Microsoft/malmo#707]
hello, I encountered an error during the installation can you help me?
when I run the script as administrator, the installation of ffmpeg this error would appear.
thank.

error:
Installing ffmpeg
Downloading http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z to \Users\Eric\temp\ffmpeg.7z ...
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « Le serveur distant a retourné une erreur : (404) Introuvable. »

**Comment by AndKram** [comment]
Release 0.35.6 updated the script.
