### ISSUE TITLE
Boost-related linking problems with release 0.34

### ISSUE THREAD

**Issue by TGlas** [Microsoft/malmo#709]
I am facing linker errors when trying to link my C++ program with libMalmo.a and boost. I am on Ubuntu 16.04, where I am using Malmö release 0.34. I have boost 1.58 installed through apt-get. Here are the essentials of my linker command (it is actually lengthy):

	g++ -pthread -o [...] -lMalmo [...] -lboost_python -lboost_date_time -lboost_thread -lboost_system -lboost_serialization -lboost_regex -lboost_program_options -lboost_iostreams -lboost_filesystem -lboost_chrono [...]

I get a whole list of linker errors. Here is the first one, the others are similar:

	/home/tobi/ini/projects/malmo/Cpp_Examples/lib/libMalmo.a(AgentHost.cpp.o): In function `malmo::AgentHost::extractVersionNumber(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
	AgentHost.cpp:(.text+0x9383): undefined reference to `boost::re_detail_106500::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'

Any ideas what I am doing wrong, or how to debug this? It would be good to know which version of boost was used to build libMalmo.a in the 0.34 release on Ubuntu 16.04. Can I find this information somewhere?

**Comment by AndKram** [comment]
Malmo 0.35.6 was build with boost 1_66_0 on all platforms instead of relying on "apt-get install boost". You also need boost-python for a specific version of Python if you are also linking with Python. The build_ubuntu1604_python3 docker file in script/docker would show you how to build boost and Malmo for Ubuntu 16.04.

**Comment by TGlas** [comment]
Thanks for the reply, and for hinting at the docker script.

I have now switched from release 0.34 to the current repository snapshot, but things still don't build. I fear that my local setup is somewhat messed up. I'll report back if I get this sorted out somehow.
