### ISSUE TITLE
Malmo Python Import Error

### ISSUE THREAD

**Issue by addis2123** [Microsoft/malmo#715]
ubuntu 18.04 64 bit
I have updated to ubuntu 18.04 from 16.04, and from Malmo 0.31.0. to Malmo 0.35.6. running python 3.6.

File "/media/addis2123/Desktop/Goby/mission.py", line 6, in <module>
         import MalmoPython
ImportError: libxerces-c-3.1.so: cannot open shared object file: No such file or directory

Possibly a dependency issue.

**Comment by okkhoy** [comment]
The manual install instructions on Ubuntu (16.04+) doesn't include libxerces-c-3.1. 
You may want to install that separately.

**Comment by addis2123** [comment]
The answer is that the new version of Malmo does not need it, but the old one did. because I did not do a clean install it was broken. The pip3 package for Ubuntu 18.04 64bit is not working as well though.

For the next person. be sure you delete all old Malmo files and references from your system after making the same switch as me.

**Comment by addis2123** [comment]
After a clean install, it works. turns out that there were some old files left over from my move to 18.04. To fix I removed all references of Malmo from my system and did a fresh install. The library file was not required.
