### ISSUE TITLE
Docs: Installing dependencies for MacOSX: sudo brew cask install java8 does not work

### ISSUE THREAD

**Issue by i3games** [Microsoft/malmo#722]
Installing dependencies for MacOSX on: https://github.com/Microsoft/malmo/blob/master/doc/install_macosx.md

`sudo brew cask install java8` 

cannot work (except if homebrew itself is owned by root). The reason is that homebrew does not allow sudo for security reasons.

I was able to install java8 with:

```
brew tap caskroom/versions
brew cask install java8
```

the second step will invoke sudo and ask for your password.

**Comment by AndKram** [comment]
Removed sudo from instructions thanks.
