### ISSUE TITLE
Docs: Mac homebrew installation fails 

### ISSUE THREAD

**Issue by i3games** [Microsoft/malmo#725]
The homebrew installation [https://github.com/Microsoft/malmo/blob/master/doc/install_macosx.md]() will currently fail because it will install Python 3.7 as well as the boost libraries for 3.7. It seems Python 3.6 is hardcoded into the Malmo installation, thus this currently doesn't work.

**Comment by AndKram** [comment]
I've added the binary release for MacOS / Python 3.7 to https://github.com/Microsoft/malmo/releases. Also added a pip binary wheel (malmo-0.35.6.0-cp37-cp37m-macosx_10_13_x86_64.whl) to https://pypi.org/project/malmo/#files.

**Comment by i3games** [comment]
I can confirm that the agents can now be launched using the binary 3.7 release, after updating the MALMO_XSD_PATH (please consider #726). Thank you for the quick fix.
