### ISSUE TITLE
Docs: python3 instead of pyton

### ISSUE THREAD

**Issue by i3games** [Microsoft/malmo#726]
On [https://github.com/Microsoft/malmo/blob/master/README.md]() in section "Launch an agent":

```
cd Python_Examples
python run_mission.py
```
On Mac OSX, after the installation steps described above, this command should be:

```
cd Python_Examples
python3 run_mission.py
```

as
`python` will refer to the Apple-supplied Python, currently 2.7, which will throw an error
`python3` will refer to the Homebrew-installed Python, currently 3.7

**Comment by AndKram** [comment]
Yes, that helps thanks,
