### ISSUE TITLE
Can someone summary the method which can run malmo headless?

### ISSUE THREAD

**Issue by YupengGao** [Microsoft/malmo#730]
1.Can someone summary the method which can run malmo headless? I know people are using xinit or xvfb-run. but the fact is I failed after I try these.

2. Can anyone confirm that the docker file (https://github.com/Microsoft/malmo-challenge/tree/master/docker) is working properly on your local machine? I run the docker file in my machine with this issue https://github.com/Microsoft/malmo-challenge/issues/48

Thanks

**Comment by AndKram** [comment]
The docker build script scripts/docker/build.sh uses the following:

 xpra start :100
 export DISPLAY=:100

with the docker files (e.g. build_ubuntu1604_python3.dockerfile) perform the install.

By the way, you can also run the vnc image and not connect vnc to it for a quick out of the box headless experience :-)

https://github.com/Microsoft/malmo/blob/package/scripts/python-wheel/README.md

**Comment by spMohanty** [comment]
@YupengGao @AndKram  : If the actual visual window is not something you care about, then you can simply start the `launchClient.sh`with `xvfb-run`. This should work fine : 
```
xvfb-run -s "-screen 0 1400x900x24" launchClient.sh -port 1000
```
