### ISSUE TITLE
a problem about Malmo0.36.0

### ISSUE THREAD

**Issue by Vorigin** [Microsoft/malmo#741]
When I run "launchClient", it always occurs the following information
..\Malmo\Client\ClientStateMachine.java:2121:error:cannot find symbol "ScoreHelper.logMissionEndRewards<reward>".
Please,thank you.

**Comment by AndKram** [comment]
You may have picked up some reverted changes on the 0.36.0 branch. If you downloaded Minecraft using the "malmo.minecraftbootstrap.download()" could you delete the MalmoPlatform directory (assuming you made no changes that need to be kept) and download again?

**Comment by Vorigin** [comment]
@AndKram 
Thanks for your answer.I tried it,but it didn,t works.

**Comment by AndKram** [comment]
Sorry to hear that. As you opened another issue are you still getting the above "cannot find symbol" error or are you now able to launch MInecraft with our mod?

**Comment by ileonidmas** [comment]
I have the same issue

**Comment by Vorigin** [comment]
@AndKram
Thank you. I'm using ver0.35.6 now.

**Comment by AndKram** [comment]
The 0.36.0 Windows binary zip was incorrect so I've re-built and uploaded it to again: 
https://github.com/Microsoft/malmo/releases/download/0.36.0/Malmo-0.36.1-Windows-64bit_withBoost_Python3.6.zip

**Comment by Vorigin** [comment]
@AndKram 
Thank you very much!!
