### ISSUE TITLE
Is timeLimitInSeconds truly seconds?

### ISSUE THREAD

**Issue by TheSauceMan** [Microsoft/malmo#752]
I was struggling getting the CPP_Example working for a while.  It would start and instantly exit because the client requested it to be done.

Just for kicks I changed:
    my_mission.timeLimitInSeconds(10);

to
    my_mission.timeLimitInSeconds(20000);

And suddenly it works -- and runs for 20 seconds.  The field is called "InSeconds", the documentation in the header says it is in seconds, but the behavior is in milliseconds.  What is the expected behavior?

Sauce

**Comment by AndKram** [comment]
Yes it's a bug, the mission XML is in ms but the C method is in seconds.

**Comment by AndKram** [comment]
Pull request #754 if you fancy doing a quick review.

**Comment by TheSauceMan** [comment]
I haven't built from source yet, it'll take a little while.  It looks reasonable to me.

I found the same issue on the python side, but reviewing python_module.cpp it looks like python is just a wrapper to the C++ implementation anyway, right?  So this fix would apply there as well.

Sauce

**Comment by AndKram** [comment]
Don't worry about building / testing unless you are doing that anyway as I'll test. Unfortunately our existing tests don't check how long the actually runs.
