### ISSUE TITLE
Mac - Python Segmentation Fault

### ISSUE THREAD

**Issue by darajorjor** [Microsoft/malmo#760]
OS: MacOS Mojave
Python: Installed from brew, 3.7 according to docs

Whenever I attempt to run any of the example files, I encounter the following problem:
    
    ➜  Python_Examples python3 run_mission.py
    [1]    13628 segmentation fault  python3 run_mission.py

I'm confused about where the problem might be. Any ideas?

the output of `otool -L MalmoPython.so`:

    MalmoPython.so:
	@rpath/MalmoPython.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python (compatibility version 3.7.0, current version 3.7.0)
	/usr/local/opt/boost/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_iostreams-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost-python3/lib/libboost_python37-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_atomic-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)

##Update

I downloaded the source code and attempted to build it. But it failed with the following error:
    
    Could not find the following Boost libraries:
    
    boost_python36

I checked my boost libraries like this:

    ➜  build git:(9d749e1) ✗ ls -l /usr/local/Cellar/boost-python3/*/lib
    total 28704
    -r--r--r--  1 mehdijjz  staff   934640 Apr 11  2018 libboost_numpy37-mt.a
    -r--r--r--  1 mehdijjz  staff    82416 Oct 11 18:18 libboost_numpy37-mt.dylib
    -r--r--r--  1 mehdijjz  staff   934640 Apr 11  2018 libboost_numpy37.a
    -r--r--r--  1 mehdijjz  staff    82320 Oct 11 18:18 libboost_numpy37.dylib
    -r--r--r--  1 mehdijjz  staff  5896872 Apr 11  2018 libboost_python37-mt.a
    -r--r--r--  1 mehdijjz  staff   423732 Oct 11 18:18 libboost_python37-mt.dylib
    -r--r--r--  1 mehdijjz  staff  5896872 Apr 11  2018 libboost_python37.a
    -r--r--r--  1 mehdijjz  staff   423300 Oct 11 18:18 libboost_python37.dylib

And as you can see, there is no 36 in them.

**Comment by AndKram** [comment]
The latest MacOS binary release is build for Python 3.6. There is a pip3 installable version of Malmo so the simplest way to install would be "pip3 install malmo" (https://github.com/Microsoft/malmo/blob/master/scripts/python-wheel/README.md) which should get you going with Python 3.7.. You should be able to build from source but would need to edit Malmo/CMakeLists.txt to look for boost_python37 on MacOS using brew (assuming that's what you got when you brew installed boost_python), changing:
 - set( BOOST_PYTHON_NAME "python3" CACHE STRING ${BOOST_PYTHON_NAME_DESC} )
+  set( BOOST_PYTHON_NAME "python37" CACHE STRING ${BOOST_PYTHON_NAME_DESC} )
