### ISSUE TITLE
Movement 

### ISSUE THREAD

**Issue by ileonidmas** [Microsoft/malmo#767]
The agent always has continues movement. Is there a possibility to move the agent exactly one block or turn it exactly 90 degrees?

**Comment by AndKram** [comment]
The mission XML file defines the type of commands in use and these can be Continuous or Discrete. What you want is <DiscreteMovementCommands/>. For example, the "Catch the Mob" example from MarLo: https://github.com/crowdAI/marLo/blob/master/marlo/envs/CatchTheMob/templates/mission.xml

**Comment by ileonidmas** [comment]
Thank you for your reply. For some reason, when the movements are discrete, it can only move. It cant attack or rotate the camera. Was it intended this way?

**Comment by AndKram** [comment]
You can have "deny" lists but all discrete are: "move", "jumpmove", "strafe", "jumpstrafe", "turn", "movenorth", "moveeast",  "movesouth", "movewest", "jumpnorth", "jumpeast", "jumpsouth", "jumpwest", "jump", "look", "attack", "use", "jumpuse". What example are you looking at / modifying?

**Comment by ileonidmas** [comment]
Thats awesome. Thank you very much. Where did you get all the command list? Can you please give me a link? We would like to know all the commands for absolute movement commands.

**Comment by AndKram** [comment]
The XSD schema lists the commands (https://github.com/Microsoft/malmo/blob/master/Schemas/MissionHandlers.xsd). We currently duplicate that in C and Python code so if you create anything that extracts the info (say a python script) that would be useful as we could use it to create the C & Python lists at build time.

**Comment by AndKram** [comment]
Follow up in #768
