### ISSUE TITLE
Opening and closing chest

### ISSUE THREAD

**Issue by Keride** [Microsoft/malmo#772]
When you look at a chest and you use the command "use 1" the chest inventory gets open. However, I don't know how to close it... I have tried "use 0" and several other commands but nothing worked... 
 
Furthermore, for the moment, the inventory observation work on the line of sight (you know the content of a container by looking at it). It could be great to add an "harder" way by giving the content after an open command to look like as an human player does.

**Comment by AndKram** [comment]
use 1 again? You could try asking on the Malmo gitter channel: https://gitter.im/Microsoft/malmo
