### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by cherylyl** [Microsoft/malmo#777]
* What went wrong:
Could not resolve all dependencies for configuration ':forgeGradleUserDevPackage'.
> Could not resolve net.minecraftforge:forge:1.11.2-13.20.0.2228.
  Required by:
      com.microsoft.MalmoMod:Minecraft:0.35.6
   > Could not resolve net.minecraftforge:forge:1.11.2-13.20.0.2228.
      > Could not get resource 'https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2228/forge-1.11.2-13.20.0.2228.pom'.
         > Could not HEAD 'https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2228/forge-1.11.2-13.20.0.2228.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by AndKram** [comment]
Possibly a temporary networking issue but could you say what OS you are using and which Java version you have installed (java -version should say 8), thanks?

**Comment by irabkina** [comment]
Hello. I'm seeing the same issue with Malmo 0.36.1 on Windows 10 with Java 8.

**Comment by AndKram** [comment]
Hi, thanks for that info!

**Comment by AndKram** [comment]
Just to recap - new versions of Java 8 have the correct CA certificates for SSL.
