### ISSUE TITLE
error when trying to open tutorial 1 in the official docker image

### ISSUE THREAD

**Issue by mathronica496** [Microsoft/malmo#778]
the error message I got is: 

> Traceback (most recent call last):
>   File "tutorial_1.py", line 23, in <module>
>     from builtins import range
> ImportError: No module named builtins 

I guess this is due to the python version since the
version the official docker image has is:

> $ python -V
> Python 2.7.12

the `pip install future` solution described in [here](https://github.com/Microsoft/malmo/issues/660)
and [here](https://github.com/Microsoft/malmo/issues/669) didn't work:

> $ pip install future
> /bin/sh: 8: pip: not found　

can anyone help, please?

**Comment by AndKram** [comment]
You should be using python3 with anything "official" but I'm actually not sure which docker image you are using. Is it "andkram/malmo"? Could you try with python3 thanks?

**Comment by AndKram** [comment]
Please see docker example in Malmo/scripts/docker.
