### ISSUE TITLE
Package not found: installing via conda fails!

### ISSUE THREAD

**Issue by biggzlar** [Microsoft/malmo#783]
Hi there,

I was setting up a remote environment for the marlo competition but was not able to install Malmo through conda. For some reason the package can't be found in any of the channels. I followed each step as [described here](https://github.com/crowdAI/marlo-multi-agent-starter-kit) and it worked a couple of days ago on a different machine.

OS: Ubuntu 16.04
Conda: 4.5.11

Here's the full error message:
```
(marlo) ~$ conda install -c crowdai malmo
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - malmo

Current channels:

  - https://conda.anaconda.org/crowdai/linux-32
  - https://conda.anaconda.org/crowdai/noarch
  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-32
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by AndKram** [comment]
Did you do the following?
conda config --add channels conda-forge
(from https://github.com/crowdAI/marlo-multi-agent-starter-kit/)

**Comment by biggzlar** [comment]
Thank you!

**Comment by nehaljwani** [comment]
@biggzlar The conda package is available for linux-64, osx-64 and win-64 and not for linux-32. If you are on a 64 bit machine, please download the 64 bit version of Miniconda and start from scratch, OR, you can do:

```
CONDA_SUBDIR=linux-64 conda create -n marlo64 python=3.6 malmo -c crowdai -c conda-forge
conda activate marlo64
```

**Comment by AndKram** [comment]
MaLo issue that was fixed before competition ended.
