### ISSUE TITLE
Marlo fails after 124 missions. Possibly out of TCP ports.

### ISSUE THREAD

**Issue by AndKram** [microsoft/malmo#784]
https://gist.github.com/jeweljames/788a8517ea76b02fa8a40970ee934398

Reported on Gitter (18/12/2018).

oth Minecrafts seem to running a mission while one agent host (called from Python) is waiting on second to turn up and the second agent host is saying that all ports are in use. Which would indicate that previous missions are not finishing. Are you calling reset() before the step() function returns "done"?

**Comment by AndKram** [comment]
The agent host opens ports to allow Minecraft mod to connect back and send observations and video. The port range is 10000 to 11000 and all these are tried and all seem to be in use, causing "All ports in use" error.

**Comment by AndKram** [comment]
Possibly due to repeated close() before mission is done. Safer to call reset() and safer still to wait for mission to complete (step() return done == True).

**Comment by jeweljames** [comment]
@AndKram Got it. would you also suggest that a new environment with a newly generated join token be created each time an episode needs to be run? or can the join token be reused?

I would like to learn what the abstraction behind join_token is, to understand the best way to do this.

**Comment by AndKram** [comment]
join tokens are for a particular game but it's best to reuse them for missions, just doing a reset(). There's a example https://github.com/crowdAI/marLo/blob/master/examples/test_random_3game_mission.py that runs all the training missions but I would add an inner loop to that to repeatedly run the same mission multiple times (say 20 to 100) as then resets are very much faster. A new "internal server" is allocated in Minecraft when running a different world which is both costly and not without stability issues.

**Comment by jeweljames** [comment]
This error persists even after making sure that close is called only after step returns done as True. 
I also ran the run_episode function from https://github.com/crowdAI/marlo-multi-agent-starter-kit in a loop and the error can be reproduced .

@AndKram Thanks for the explanation.

**Comment by AndKram** [comment]
MarLo close() actually does nothing to close the AgentHost but it should be de-allocated by the Python garbage collector if the Env is garbage collected. The AgentHost destructor closes the TCP ports in use but that appears not to happen for you? I'd suggest using reset() instead of close(). You should only call init() once on a MarLo Env as close() does not really close the AgentHost. You could add a "del self.agent_host" to close() and it would be re-created  with "self.agent_host = AgentHost()" in env.init().

class MyEnv(marlo.Env):
        def close(): 
               del self.agent_host

**Comment by AndKram** [comment]
The TCP port close issues should be addressed by pull request #785. But still very much more efficient to call reset() rather than close/create new AgentHost.
