### ISSUE TITLE
Build Failed - no such version exists

### ISSUE THREAD

**Issue by ClementRomac** [Microsoft/malmo#795]
Hi,

I've been using Malmo (0.34) for more than a month now, and suddenly this morning I get a build failed error when I run the launchClient.bat: 
```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Malmo\Minecraft\build.gradle' line: 42

* What went wrong:
A problem occurred evaluating root project 'Minecraft'.
> No such version exists!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.225 secs

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Malmo\Minecraft\build.gradle' line: 42

* What went wrong:
A problem occurred evaluating root project 'Minecraft'.
> No such version exists!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.053 secs

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Malmo\Minecraft\build.gradle' line: 42

* What went wrong:
A problem occurred evaluating root project 'Minecraft'.
> No such version exists!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.011 secs
```

I tried on another computer where Malmo was running yesterday and I have the same error. Both my computers are running Windows 10 and have Java 1.8.0_201 installed.

Do you have any idea where that could come from ?
Thanks

**Comment by MadcowD** [comment]
Currently the Gradle (java package manger) for MinecraftForge (the mod of minecraft which decompiles it and lets malmo use deobfuscated game code) is down.

This is not a Malmo issue and it effects the whole Minecraft modding community. This is currently being fixed:

http://www.minecraftforge.net/forum/topic/68782-1122-setupdecompworkspace-no-such-version/

In the mean time I will look into a nethod which skips the ForgeGradle class path dependency.

**Comment by MadcowD** [comment]
Also just a note next time u get an error with malmo, do `./gradlew(.bat?) runClient --stacktrace` that will help the maintainers of this project actually help u.

**Comment by MadcowD** [comment]
Pinging ms folks so they know @AndKram

**Comment by unlut** [comment]
> In the mean time, I'll look into making a gradle script which skips rebuilding each time you run your client.

It would be great not having to build each time we run client, thanks for info!

**Comment by Unnoen** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/5477#issuecomment-464195569 For information on this issue and an updated comment with how to fix issues.

**Comment by MadcowD** [comment]
As Unnoen said: https://github.com/MinecraftForge/MinecraftForge/issues/5477#issuecomment-464195569 

@AndKram this is a shitshow to patch for everyone who's already got Malmo downloaded in its released form. They may all need to modify their launchClient.bat(.sh) to call `gradlew runClient --refresh-dependences` or something similar.

**Comment by Unnoen** [comment]
Deleting the gradle cache for ForgeGradle is also an option, but that will require users to find their cache folder and delete something, not entirely user friendly. 
But new users shouldn't have a problem, just those with the old version still cached.

**Comment by MadcowD** [comment]
Yep!
```
./gradlew setupDecompWorkspace --refresh-dependencies
./gradlew runClient
```
will also work

**Comment by ClementRomac** [comment]
Hi,

It works thank you very much !
