### ISSUE TITLE
Link used to download Doxygen in malmo_build.ps1 is down

### ISSUE THREAD

**Issue by u-pi** [Microsoft/malmo#799]
When running malmo_build.ps1, the script fails on installation of Doxygen due to a dead link.
I've noticed that the link from which Doxygen is being downloaded is down (http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.13.windows.x64.bin.zip). I've been checking back on it for the past 3 days and it's been down all this time, so there is a good chance it's not coming back up and should be replaced.

**Comment by AndKram** [comment]
Pull request #800.
