### ISSUE TITLE
Boost symbol not found on MacOS Mojave

### ISSUE THREAD

**Issue by jens321** [Microsoft/malmo#808]
When trying to install malmo from here: https://github.com/Microsoft/malmo/releases (I unzipped Malmo-0.36.0-Mac-64bit_withBoost_Python3.6.zip), I encountered the following error when running tutorial_1.py:

Traceback (most recent call last):
  File "tutorial_1.py", line 24, in <module>
    import MalmoPython
ImportError: dlopen(/Users/jens/Desktop/MalmoPlatform/Python_Examples/MalmoPython.so, 2): Symbol not found: __ZN5boost11basic_regexIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9do_assignEPKcS7_j
  Referenced from: /Users/jens/Desktop/MalmoPlatform/Python_Examples/MalmoPython.so
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /Users/jens/Desktop/MalmoPlatform/Python_Examples/MalmoPython.so

I am using Python version 3.7 with Anaconda. 

I realize this is likely related to [#445](https://github.com/Microsoft/malmo/issues/445), but I could not solve the issue above, and was thinking it might have something to do with me running it on MacOS Mojave and the boost-python3 library? Any suggestions are very welcome.

Thank you so much!

**Comment by AndKram** [comment]
Your Malmo binary version is for Python3.6 and you are using Python 3.7. The MarLo competition supported Anaconda on MacOS. https://github.com/crowdAI/marlo-multi-agent-starter-kit/ so you could try that path. Building from source on MacOS is not too difficult as a fall back.

**Comment by jens321** [comment]
Thanks a lot for your reply! 
Switching to python 3.6 and downloading the latest Malmo zip file from the releases page worked. Closing this issue.

**Comment by guyhoffman** [comment]
Switching to Python 3.6 requires libboost 3.6, which is no longer available through homebrew. Is there another option?

**Comment by AndKram** [comment]
You should be able to "pip install malmo" for Python 3.7 on MacOS. This allows (with a compatibility wrapper) to run the demos (https://github.com/Microsoft/malmo/blob/master/scripts/python-wheel/README.md). Going forward the pure Python GYMN environment removes the need for native code and will be the preferred malmo install in open ai gym environments.

**Comment by guyhoffman** [comment]
Running Python 3.7 with pip does not work, and results in the libboost error listed above. The solution that works for me, too, is to make a virtualenv with Python 3.6 and use the prebuilt folder from https://github.com/Microsoft/malmo/releases - It's slightly more difficult, since Python does not seem to have an official release of 3.6.9, but you can find 3.6.8 here: https://www.python.org/downloads/release/python-368/

**Comment by AndKram** [comment]
I've built and uploaded Malmo-0.37.0-Mac-64bit_withBoost_Python3.7.zip under the "MalmoEnv" release. Hope that helps.

**Comment by guyhoffman** [comment]
Thanks! Will try this out.
