### ISSUE TITLE
Different BOOST_PYTHON_NAME for recent Boost versions

### ISSUE THREAD

**Issue by kirillbobyrev** [Microsoft/malmo#812]
Currently, Malmö's `CMakeLists.txt` sets `BOOST_PYTHON_MODULE_NAME` to either `"python"` or `"python3"`. This causes CMake configuration failure for recent Boost versions (I'm currently using 1.69.0) because this should be `python{MAJOR}{MINOR}` now (excerpt from [CMake's FindBoost documentation](https://cmake.org/cmake/help/v3.13/module/FindBoost.html)):

> Note that Boost Python components require a Python version suffix (Boost 1.67 and later), e.g. `python36` or `python27` for the versions built against Python 3.6 and 2.7, respectively. This also applies to additional components using Python including `mpi_python` and `numpy`. Earlier Boost releases may use distribution-specific suffixes such as `2`, `3` or `2.7`. These may also be used as suffixes, but note that they are not portable.

A reasonable approach would probably be calling `/usr/bin/env python3 --version` and parsing the output with CMake regular expressions or simply calling `python -c "import sys; print('python' + str(sys.version_info[0]) + str(sys.version_info[1]))` and putting the output into the variable.

Cheap solution: make `BOOST_PYTHON_MODULE_NAME` an option and simply let users override it instead of hard-coding the version in `CMakeLists.txt` instead.

**Comment by AndKram** [comment]
We usually just override it (cheap option) but please see comment on review.

**Comment by kirillbobyrev** [comment]
@AndKram Thanks for the review, I have addressed the comments you left!
