### ISSUE TITLE
Что я сделал не так?

### ISSUE THREAD

**Issue by ZombiePm** [microsoft/malmo#814]
PS C:\Malmo-0.37.0-Windows-64bit_withBoost_Python3.6\Python_Examples> python tabular_q_learning.py
Traceback (most recent call last):
  File "tabular_q_learning.py", line 32, in <module>
    import MalmoPython
ImportError: DLL load failed: %1 не является приложением Win32.

**Comment by AndKram** [comment]
Possibly Python 3.7 on Windows. New binary release (and Python wheel) available now.
