### ISSUE TITLE
pip install malmo==0.36.0.0

### ISSUE THREAD

**Issue by ZombiePm** [microsoft/malmo#818]
![image](https://user-images.githubusercontent.com/20536989/58594457-59736f80-8276-11e9-8807-a4843bb2a977.png)

**Comment by ZombiePm** [comment]
что я делаю не так

**Comment by Rowing0914** [comment]
did you get it work??? I've got the same problem.... I am using python3.6 and it is not pip-able....

**Comment by ZombiePm** [comment]
> did you get it work??? I've got the same problem.... I am using python3.6 and it is not pip-able....

Thank, That solved my issues 
![image](https://user-images.githubusercontent.com/20536989/58824619-2863b800-8645-11e9-940a-2f6642d67e1a.png)

**Comment by Rowing0914** [comment]
hmm,, it seems working.. if possible, could you share me what was the issue??? what was your workaround??

**Comment by Rowing0914** [comment]
Sorry,,, I just found that it is not just compatible with Python3.6 on Linux...
https://pypi.org/project/malmo/0.36.0.0/#files
any time soon is it available for Python3.6 on Linux??

**Comment by AndKram** [comment]
New Python wheel and binary release for Windows / Python 3.7 have now been uploaded. Please give these a try.
