### ISSUE TITLE
How can I get a video frame?

### ISSUE THREAD

**Issue by neesetifa** [microsoft/malmo#819]
I tried using while world_state.number_of_video_frames_since_last_state < 1  waiting for frame, but after 40s it's still nothing. I can easily get other variables like world_state.observations, but not for video_frame,it's always empty. Is there anything special that I need to do before I try to get video_frame? Maybe like start recording video or something?  I'm new to this and it stuck me for days.
Thank you

**Comment by AndKram** [comment]
The mission XML needs to include a <VideoProducer/> element in the <AgentHandler>/ <AgentSection/>. One example would be the render_speed_test.py in Malmo/samples/Python_examples.
