### ISSUE TITLE
Can't seem to run ANYTHING

### ISSUE THREAD

**Issue by tikikevin** [microsoft/malmo#822]
I've downloaded multiple 'versions' (stable and otherwise) and it gives me errors all over the place! Depending on what I run it is all around "no module..."

The Modules so far are 'future', 'past', and 'malmo'

I haven't downloaded the "source" and I've gone through the requirements multiple times, and it appears to all be setup correctly.. 

Windows 10/Python 3.7.1

Any help welcome!

**Comment by tikikevin** [comment]
Add to the "no module..." list: MalmoPython

**Comment by AndKram** [comment]
The supported Python version is Python 3.6 on Windows. You could try the following pip install:
pip install -i https://test.pypi.org/simple/ malmo
And follow instructions for the pip installable package https://github.com/Microsoft/malmo/blob/master/scripts/python-wheel/README.md

**Comment by AndKram** [comment]
New python wheel and binary release have now been uploaded for Windows / Python 3.7. Please give these a try.
