### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by Project-Magenta** [microsoft/malmo#827]
Could you please add support for Python 3.7?
that includes prebuilt and right now i am not able to compile malmo using the linux instructions for python 3.7 due to the boost version.

am using Ubuntu 19.04

also, i tried replacing the boost with the latest (1.70.0)
same error.

**Comment by AndKram** [comment]
3.7 builds are available for Windows (https://github.com/microsoft/malmo/releases/download/0.37.0/Malmo-0.37.0-Windows-64bit_withBoost_Python3.7.zip) and MacOS (https://github.com/microsoft/malmo/releases/download/0.37.0/Malmo-0.37.0-Mac-64bit_withBoost_Python3.7.zip) as that's the official Python version on those OSs now. Boost 1.69 was used for those and could equally be used on Linux.

**Comment by Project-Magenta** [comment]
I am unable to compile. I am using Boost 1.69 to build and it says:
`Can't find boost version for: python37`

**Comment by AndKram** [comment]
Assuming you had Python 3.7 installed and boost found it when it was compiled. Try with malmo/CMakeLists.txt from line 52 replaced with:

if( INCLUDE_PYTHON )

  set( USE_PYTHON_VERSIONS_DESC "Specifies which version of Python to build Malmo with Python bindings" )

  set( USE_PYTHON_VERSIONS 3.7 CACHE STRING ${USE_PYTHON_VERSIONS_DESC} )

  set( BOOST_PYTHON_NAME_DESC "Specifies which Boost Python module to build Malmo with" )

  set( BOOST_PYTHON_NAME "python3" CACHE STRING ${BOOST_PYTHON_NAME_DESC} )

endif()

Possibly it should be looking for python3 and not python37?

**Comment by Project-Magenta** [comment]
ok will try thx

**Comment by ayoung012** [comment]
I was able to build the malmo project using Python 3.7 and boost 1.67 instead of 1.66 on Fedora 30  (1.66 resulted in an error during malmo build: something about being unable to find the boost_python37 library).

Below are my successful build steps, straying from doc/build_linux.md just before step 4iii):

```
# Build boost 1.67 instead of 1.66
wget http://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz
tar xvf boost_1_67_0.tar.gz
cd boost_1_67_0
export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python3.7m/"
./bootstrap.sh --prefix=.
./b2 link=static cxxflags=-fPIC install

# Build malmo, instead of 7viii)
cmake -DBoost_INCLUDE_DIR=home/$USER/boost/boost_1_67_0/include
-DCMAKE_BUILD_TYPE=Release ..
```

Hope this helps somebody!

This particular thread clued me in to trying 1.67, as the b2 script failed/skipped 3 libs related to python with the same compile error.

**Comment by Project-Magenta** [comment]
Oh that makes sense, I was using Boost 1.70.8
I'll try that when I get home.
Cheers!

**Comment by DaveyBiggers** [comment]
Thanks @ayoung012.
@Project-Magenta did you manage to build in the end?
I'm closing this issue for now, but if there are still problems please reopen and provide more details.
