### ISSUE TITLE
MalmoEnv obs reshape bugs

### ISSUE THREAD

**Issue by tomsilver** [microsoft/malmo#831]
This issue is reproducible by using `Env(reshape=True)`.

There are two bugs on this line:
https://github.com/microsoft/malmo/blob/master/MalmoEnv/malmoenv/core.py#L331

First, there is a call to [np.ndarray.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html) with an invalid keyword (`dtype`). This can be rewritten as `obs = obs.reshape((self.height, self.width, self.depth)).astype(np.uint8)`.

Second, this line should be un-indented so that it is outside the `while` loop and only called before `step` returns; otherwise we might try to reshape empty arrays.

Third, the `reset` function needs the same logic to handle reshaping observations. One option is to add

```
    if self.reshape:
            obs = obs.reshape((self.height, self.width, self.depth)).astype(np.uint8)
```

at the end of `_peek_obs`.

Let me know if you would like me to make these changes in a pull request. Thanks!

**Comment by AndKram** [comment]
Thanks for this. The reshape option came from adding some MarLo missions and missed a commit. But you have improved it further for reset(). I've created a new pull request #832.

**Comment by tomsilver** [comment]
Looks good, thanks!
