### ISSUE TITLE
Namespace specification resource is down

### ISSUE THREAD

**Issue by vkurenkov** [microsoft/malmo#834]
http://projectmalmo.microsoft.com/  is not responding 😢

**Comment by AndKram** [comment]
I believe the URI has never been live. Possibly not the best choice in the first place as ProjectMalmo.microsoft.com has uppercase characters but this is not actually causing any problems?

**Comment by DaveyBiggers** [comment]
Am closing this as I believe it's a non issue. Please reopen if it's causing problems.
