### ISSUE TITLE
Port Request.

### ISSUE THREAD

**Issue by border999** [microsoft/malmo#835]
Is there a version of this program's .jar file for 1.12.2 of minecraft? I would love to see what I can teach this to do in my super modded world, over 400 mods.

**Comment by AndKram** [comment]
Unfortunately not and Minecraft has moved on from 1.12.2 so unlikely to that particular version next.

**Comment by border999** [comment]
@AndKram Dude, 1.12.2 is the new 1.7.10. if you want people to use it, port it to the version the vast majority of people are using.

**Comment by DaveyBiggers** [comment]
We are hoping to update soon, though it will be to the latest Minecraft version, not 1.12.2.
Also, I think you may have misunderstood what Malmo is about - we don't provide an AI for you to teach, we simply allow you to write your own. And Malmo is not designed to interact with other mods - we don't test it in modded environments, and it's quite likely to be incompatible with at least some of them (especially if you have over 400!)

Sorry for any confusion.

**Comment by jpie726** [comment]
Most people use 1.12.2 not only for modding but just for general playing.
The most recent versions (1.13+) are highly unstable on servers and frequently lead to crashes if not configured near perfectly.
