### ISSUE TITLE
Byte array to String with no encoding specified

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/malmo#838]
https://github.com/microsoft/malmo/blob/29e1c057e6f5d8a6e01f512352e9275c657bd971/Minecraft/src/main/java/com/microsoft/Malmo/Client/MalmoEnvServer.java#L431

Converting data from byte arrays to String may result in data loss if no encoding is specified.

**Comment by AndKram** [comment]
Random ascii values generated in Java so probably safe but if you would like to create a pull request please do so.
