### ISSUE TITLE
Change mission after start

### ISSUE THREAD

**Issue by paulosoaresua** [microsoft/malmo#839]
Hi, is it possible to change the mission once it started? Like drawing/destroying blocks, for instance. 

I need this functionality and so far I haven’t been able to find anything related in the documents of the project.

Thanks!

**Comment by DaveyBiggers** [comment]
Malmo doesn't explicitly support this, but I believe you can access Minecraft's slash commands - use the agent's `chat` command to send, eg, a minecraft setblock command.
