### ISSUE TITLE
setObservationsPolicy

### ISSUE THREAD

**Issue by Bulbousonions13** [microsoft/malmo#844]
Hello,

How does one set the ObservationPolicy on an AgentHost so they can view all the chats sent by every agent/player ...

I have enabled ObservationFromChat in xml, and tried to set the observation policy ENUM

to KEEP_ALL_OBSERVATIONS, but I can't seem to get the syntax right.

I know it's along the lines of --> agent_host.setObservationsPolicy( "SOMETHING GOES HERE");

I'm using Python 3.6 with Boost --> Malmo 0.37

Thanks

**Comment by Bulbousonions13** [comment]
Nevermind, I found the solution. I was manually logging observations to a file and was missing the chats, but then checked the recording specs and the chats are in the observations.txt data dump. Either way this might help someone ...

Thanks!

**Comment by jeasinema** [comment]
@Bulbousonions13 could you please elaborate more on this? I've added `ObservationFromChat` to the XML but still cannot get the message in the chat box when calling `clients.step`. Thank you!
