### ISSUE TITLE
Running run_mission.py hangs

### ISSUE THREAD

**Issue by rohanpaleja27** [microsoft/malmo#845]
I am attempting to go through the tutorial and can launch MineCraft fine, but am unable to play any tutorials or missions. After running run_mission.py, I get a printout of the experiment id and that's it. 

I am running Malmo-.37 on Ubuntu 18.04 which Python 3.6.

**Comment by INFCsapi** [comment]
Can you try 
`MALMO_XSD_PATH=YourMalmoDir/Schemas/ ` 
in your terminal before starting a mission? ( Do replace the path to your own Malmo directory )
