### ISSUE TITLE
Position of DrawingDecorator 

### ISSUE THREAD

**Issue by kimbring2** [microsoft/malmo#858]
I find little error in ServerSection of XML file.

First XML setting is working well.
![1](https://user-images.githubusercontent.com/11064407/72952876-962c4200-3dd6-11ea-8aaa-80662c0fd820.png)

However, second XML is not working. It gives a 'Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.' message.
![2](https://user-images.githubusercontent.com/11064407/72952854-7c8afa80-3dd6-11ea-8cb0-b6ce4440cf26.png)

Why am I presenting this bug is that `my_mission = MalmoPython.MissionSpec()` code makes a XML like a above order when I run a 'human_action.py'.

Futhermore, `my_mission.setTimeOfDay(1000, False)` line also makes an error in 'human_action.py'.

**Comment by DaveyBiggers** [comment]
@kimbring2 I'm puzzled that one of these works and the other doesn't - can you provide any more details? Minecraft logs, for instance? The "Failed to find an available client" message usually means that you don't have an available instance of Minecraft running - are you trying to run two missions at once, with only one running Minecraft?

What error do you get from "setTimeOfDay"?

It's worth noting that this API (my_mission.setTimeOfDay, etc.etc.) isn't really the recommended way of doing things (despite being part of the sample!) - much better to specify the XML directly. See #354 for a brief discussion of the rationale behind this.

**Comment by kimbring2** [comment]
Thank you for good advice. 

I will try set a setTimeOfDay in XML directly

From Dohyeong
