### ISSUE TITLE
"move 1" in DiscreteMovementCommands does not work with FileWorldGenerator

### ISSUE THREAD

**Issue by vidhiJain** [microsoft/malmo#859]
I am trying to make agent with Discrete Movement commands to move in a saved world (in Minecraft/run/saves/). However, the command seems to fail for forward and backward motion. 
I tried running the command multiple times (~ 100 times) but it doesn't change the coordinates of the agent (visible on Minecraft screen by F3). "turn 1" and "turn -1" do execute and produce a 90 degrees rotation left or right respectively. 
I am using Malmo 0.37.0 with Minecraft 1.11.2 in Ubuntu 18.04.

**Comment by zacharyhorvitz** [comment]
FYI if DiscreteMovementCommands are not working, it's good to make sure to initialize the agent's z and x position at half steps (e.g. x="4.5" instead x="4"). Otherwise discete moves will fail.

It would be great to see this mentioned in the documentation.
