### ISSUE TITLE
./launchClient.sh crashes during RunClient portion

### ISSUE THREAD

**Issue by rohanpaleja27** [microsoft/malmo#863]
Previously, I had a working version of Minecraft. Since then, I have upgraded cuda and done several standard ubuntu updates suggested by the software center.

I have attached the output of ./launchClient.sh, ran with debug and stacktrace.
[error.txt](https://github.com/microsoft/malmo/files/4187830/error.txt)

I have tried to reinstall java several times, pulled a new malmo folder, and reinstall gradle.

**Comment by adarshp** [comment]
@rohanpaleja27 you'll need to downgrade your Java version - right now you have 1.8.0_242, which doesn't work - we had to manually install version 1.8.0_232 to get it to work on Ubuntu.

**Comment by rohanpaleja27** [comment]
Thanks for the reply @adarshp 
How did you manually go about installing version 1.8.0_232?

I am using 
`sudo apt-get install openjdk-8-jdk=1.8.0_232`
and finding that the version is not found.
