### ISSUE TITLE
Observation for nearby entities

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#89]
(Entities are the moving things like creepers, animals and other players.)

Observations might include: position, orientation, action, carrying.

Let us know if this observation is important to you.

**Comment by MiniDigger** [comment]
Entity are basically everything that is somewhat dynamic in minecraft.(dropped) Items are entities, mobs are entities. The weather is a entity. What you are referring to are living entities, a sub class of entity.

**Comment by TGlas** [comment]
As I see it, all of these dynamic things are potentially useful, i.e., as groud truth data for supervised training of computer vision methods, or at least for performance assessment. However, those entities that don't affect the gameplay directly (like the weather) should be of low priority.

**Comment by einsteinsci** [comment]
Weather can affect gameplay directly through snow, which can add an extra block the agent has to dig through before reaching the ground. Also, if for some odd reason you want the agent to make snowballs, it needs to find a snowy biome or wait for it to rain in a cold biome.

I never knew that weather even inherited from `Entity`. I must be so used to `EntityLiving` to consider the stranger entities. Do particles inherit from `Entity`? Those can be useful sources of information to the agent sometimes.

**Comment by MiniDigger** [comment]
yeah, particles inherit from Entity too, there is a EntityFX class where all particles inherit from. it extends entity. 
just generated javadocs from the deobfuscated sources and there are 120 subclasses (direct and indirect) of entity. So basically everything is a entity ^^
as said above, everything that is dynamic in some way is a entity. only tileentities (blocks with "special abilities") are not entities.

**Comment by NoahReifsnyder** [comment]
Is there the ability to get the entities orientation from Observation from nearby entities?

**Comment by DaveyBiggers** [comment]
@NoahReifsnyder not currently - feel free to make a feature request by creating a new issue.
