### ISSUE TITLE
Observation for nearby items

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#90]
(Items are the small floating pictures of tools, blocks etc.)

There is currently a reward handler for collecting (and discarding) items but no observation producer.

In this category we might want to include the circular blobs of 'xp' that can be collected after mining coal or breeding an animal, for example.

For stacked items the observation should include the number of items in the stack.

**Comment by DaveyBiggers** [comment]
I'm closing this as it will be covered by #89.
