### ISSUE TITLE
ModuleNotFoundError: No module named 'malmopy'

### ISSUE THREAD

**Issue by itzdrli** [microsoft/malmo#915]
im new on malmo or coding,when i try to run the malmo-challenge/pig-chase,i do 'python pig_chase_human_vs_agent.py',it says

c:\malmo\malmo-challenge\ai_challenge\pig_chase>python pig_chase_eval_sample.py
Traceback (most recent call last):
  File "pig_chase_eval_sample.py", line 19, in <module>
    from evaluation import PigChaseEvaluator
  File "c:\malmo\malmo-challenge\ai_challenge\pig_chase\evaluation.py", line 23, in <module>
    from agent import PigChaseChallengeAgent
  File "c:\malmo\malmo-challenge\ai_challenge\pig_chase\agent.py", line 31, in <module>
    from malmopy.agent import AStarAgent
ModuleNotFoundError: No module named 'malmopy'

my malmo is installed by 'pip install malmo' and using python3.6,also the release of malmo is 0.36.1,i installed,windows 11 64x, and others programs like Git or ffmpeg i all installed,but idk y still tell me no model of malmopy.

pls,help me.thank u so much :)

**Comment by llt12213** [comment]
> 你能分享输出`pip install -e .`吗？

Uhhhhh i closed the windows of cmd and also the computer,time is 0:03 right now :(,but i remember the output is installed 2 or 3 things and success. :)

**Comment by kachayev** [comment]
It seems like the error comes from line https://github.com/microsoft/malmo-challenge/blob/a1dec75d0eb4cccc91f9d818a4ecae5fa1ac906f/ai_challenge/pig_chase/pig_chase_human_vs_agent.py#L28

But in your case it's modified. Error message

```
 ModuleNotFoundError: No module named 'malmopy.viFsualization'
```

Note letter `F` in `viFsualization`. Make sure that the file was not modified after the repo was cloned.
