### ISSUE TITLE
ModuleNotFoundError: No module named 'malmopy'

### ISSUE THREAD

**Issue by StackoverflowEnjoyer** [microsoft/malmo#920]
Every time I try to run pig_chase_human_vs_agent.py, I get this error
`Traceback (most recent call last):
  File "D:\malmo-challenge\ai_challenge\pig_chase\pig_chase_human_vs_agent.py", line 26, in <module>
    from malmopy.agent import RandomAgent
ModuleNotFoundError: No module named 'malmopy'`
I have already ran malmo-challange\setup.py

**Comment by addis2123** [comment]
I don't know if this will help you, but I can remember running into this and having to run the pip install instructions to get it working. May give that a try. I don't think the devs are coming back to this project unfortunately.
